Add Redis example
oscarlab/graphene-tests pull request #17
Opened 2019-07-26 00:55 UTC by dimakuv

This PR adds a Redis example.

**Note!** There is still a TODO on inability to unset environment variables in Graphene. We first need to change it in Graphene code and then remove that comment from this Redis example.

**Note!** There is still a TODO on some error when Redis tries to finish the RDB snapshot file when gracefully shutting down (Ctrl-C). Currently we don't use the file system (`--save ''`) but this should be debugged and fixed.

2019-08-29 17:36 UTC, chiache submitted a review, later dismissed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-08-29 18:59 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: all files reviewed, 9 unresolved discussions (waiting on @dimakuv)

___
*[redis/Makefile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTgRlt2WEsfCr9AtIr:-LnTgRlt2WEsfCr9AtIs:bls6lxt) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/Makefile#L7)):*
> ```Makefile
> # - make SGX=1 DEBUG=1 -- create SGX debug-log manifest
> #
> # Any of these invocations clones Redis git repository and builds Redis in
> ```

clones Redis -> clones Redis'
___
*[redis/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTh8bdCxZWfUZcW-2O:-LnTh8bdCxZWfUZcW-2P:bjj88go) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/Makefile#L27)):*
> ```Makefile
> endif
> 
> .PHONY=all
> ```

.PHONY= -> .PHONY: (Thanks for copying that mistake! ;)
___
*[redis/Makefile, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnThEwt8ezSABAUuBFh:-LnThEwt8ezSABAUuBFi:b-89a4rb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/Makefile#L89)):*
> ```Makefile
> ################################## CLEANUP ####################################
> 
> .PHONY=clean
> ```

Dito.
___
*[redis/Makefile, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnThGo08N4Mbd65s2hO:-LnThGo08N4Mbd65s2hP:b-89a4rb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/Makefile#L93)):*
> ```Makefile
> 	$(RM) *.token *.sig *.manifest.sgx *.manifest pal_loader redis-server *.rdb
> 
> .PHONY=distclean
> ```

Dito.
___
*[redis/README, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnThZgE5AoEsf8siVRa:-LnThZgE5AoEsf8siVRb:b-weiwt7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/README#L35)):*
> ```
> # Why this Redis config?
> 
> Notice that we run Redis with two configs: `save ''` and `protected-mode no`:
> ```

configs -> parameters
___
*[redis/redis-server.manifest.template, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTi47u4LCzaiOsrVe4:-LnTi47u4LCzaiOsrVe5:b-kq5ms3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/redis-server.manifest.template#L43)):*
> ```
> # TODO(dimakuv): Graphene's PAL incorrectly handles this currently. See
> # `read_environments()`, the end of function. Below strings create envvars
> # with empty strings, which forces Redis to do incorrect things like thinking
> ```

Why does the manifest have the env vars UPSTART_JOB and NOTIFY_SOCKET in the first place? Is this more of a notice to yourself? Why not create an issue instead of lamenting this here?
___
*[redis/redis-server.manifest.template, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTihY16ohka-yjANmn:-LnTihY16ohka-yjANmo:b-g3u3sz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/redis-server.manifest.template#L82)):*
> ```
> # default port used by Redis. Note how a missing interface name means "any
> # interface".
> net.allow_bind.redisport = :6379
> ```

I was always under the impression this is ignored by Graphene anyway? Might be wrong though.
___
*[redis/redis-server.manifest.template, line 153 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTjSyCENx2SV6wJ47q:-LnTjSyCENx2SV6wJ47r:b-j2tk2o) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/redis-server.manifest.template#L153)):*
> ```
> ############################# SGX: ALLOWED FILES ###############################
> 
> # Specify all non-static files used by app. These files may be opened by
> ```

opened -> accessed
___
*[redis/redis-server.manifest.template, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTjUvf9LkJ3D2hvWaW:-LnTjUvf9LkJ3D2hvWaX:b-a1j7hk) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/redis-server.manifest.template#L154)):*
> ```
> 
> # Specify all non-static files used by app. These files may be opened by
> # Graphene-SGX but modifications to them are not detected (Graphene-SGX does
> ```

but there integrity is not verified


<!-- Sent from Reviewable.io -->

2019-09-05 23:36 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: 0 of 3 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @chiache and @thomasknauth)

___
*[redis/Makefile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTgRlt2WEsfCr9AtIr:-Lo2jxycCuk3bIvNr1NR:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/Makefile#L7)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

clones Redis -> clones Redis'
</blockquote></details>

Done.
___
*[redis/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTh8bdCxZWfUZcW-2O:-Lo2k2WG0bczX9HYyDcg:b-ls7wav) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/Makefile#L27)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

.PHONY= -> .PHONY: (Thanks for copying that mistake! ;)
</blockquote></details>

Done. You're welcome :)
___
*[redis/Makefile, line 89 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnThEwt8ezSABAUuBFh:-Lo2k5ja6eVbB0w8--X9:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/Makefile#L89)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Dito.
</blockquote></details>

Done.
___
*[redis/Makefile, line 93 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnThGo08N4Mbd65s2hO:-Lo2k633-9jH7VRxg1IK:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/Makefile#L93)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Dito.
</blockquote></details>

Done.
___
*[redis/README, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnThZgE5AoEsf8siVRa:-Lo2kKeT2GS_ZhVmaEYZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/README#L35)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

configs -> parameters
</blockquote></details>

Done.
___
*[redis/redis-server.manifest.template, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTi47u4LCzaiOsrVe4:-Lo2lMwa0npMDIh0shoV:b-mkjvs0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/redis-server.manifest.template#L43)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Why does the manifest have the env vars UPSTART_JOB and NOTIFY_SOCKET in the first place? Is this more of a notice to yourself? Why not create an issue instead of lamenting this here?
</blockquote></details>

Done. Removed this from here completely (so as to not confuse users) and added a comment in https://github.com/oscarlab/graphene/issues/870.
___
*[redis/redis-server.manifest.template, line 82 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTihY16ohka-yjANmn:-Lo2lWFx9mCY4NG6wmsg:b1312bk) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/redis-server.manifest.template#L82)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

I was always under the impression this is ignored by Graphene anyway? Might be wrong though.
</blockquote></details>

It's supposed to work one day. So I will leave it even though it is a no-op currently.
___
*[redis/redis-server.manifest.template, line 153 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTjSyCENx2SV6wJ47q:-Lo2lhVc0QK-UVuPrl2Q:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/redis-server.manifest.template#L153)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

opened -> accessed
</blockquote></details>

Done.
___
*[redis/redis-server.manifest.template, line 154 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LnTjUvf9LkJ3D2hvWaW:-Lo2ltXV-7rlsPUygJHc:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a4034a6f3161564cef4b0f08e583783ede08efc4/redis/redis-server.manifest.template#L154)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

but there integrity is not verified
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-09 11:52 UTC, thomasknauth reviewed
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: 1 of 3 files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @chiache)



<!-- Sent from Reviewable.io -->

2019-09-10 17:34 UTC, chiache submitted a review, later dismissed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-10 22:17 UTC, mkow requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: all files reviewed, 6 unresolved discussions (waiting on @dimakuv)

___
*[redis/Makefile, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoS9Nr13BzyyCim5uK0:-LoS9Nr27IDl281SmGWm:b76fomv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/Makefile#L42)):*
> ```Makefile
> 	git clone --recursive https://github.com/antirez/redis $(SRCDIR)
> 	cd $(SRCDIR) && git checkout $(COMMIT)
> 	cd $(SRCDIR) && make -j4
> ```

`cd $(SRCDIR) && make -j4` -> `$(MAKE) -C $(SRCDIR)`
___
*[redis/README, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSBAX04Uy2MkgPoP7f:-LoSBAX04Uy2MkgPoP7g:b-o7zpwv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L8)):*
> ```
> 
> The Makefile and the template manifest contain extensive comments and are made
> self-explanatory. Please review them to gain understanding in Graphene-SGX
> ```

`in` -> `of`? I'm not 100% sure though
___
*[redis/README, line 20 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSC3j49mZWDFKdcCqF:-LoSC3j49mZWDFKdcCqG:b-8ta4yp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L20)):*
> ```
> ./redis-server --save '' --protected-mode no &
> src/src/redis-benchmark
> killall redis-server
> ```

`redis-server` -> `%%`
___
*[redis/README, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSC5O1-Jq1o10aTprm:-LoSC5O1-Jq1o10aTprn:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L25)):*
> ```
> ./pal_loader redis-server --save '' --protected-mode no &
> src/src/redis-benchmark
> killall pal-Linux
> ```

ditto
___
*[redis/README, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSC5zm7kKxFOzBc4Pn:-LoSC5zm7kKxFOzBc4Po:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L30)):*
> ```
> SGX=1 ./pal_loader redis-server --save '' --protected-mode no &
> src/src/redis-benchmark
> killall pal-Linux-SGX
> ```

ditto
___
*[redis/README, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSCHlW0wtbZp7fizu0:-LoSCHlW0wtbZp7fizu1:bqdbb8o) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L38)):*
> ```
> 
> - `save ''` disables saving DB to disk (both RDB snapshots and AOF logs). We
>   use this parameter to side-step some bugs during graceful shutdown of Redis.
> ```

`some bugs during` -> `some bugs in Graphene triggered during`


<!-- Sent from Reviewable.io -->

2019-09-10 22:32 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: 1 of 3 files reviewed, 6 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @chiache, @mkow, and @thomasknauth)

___
*[redis/Makefile, line 42 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoS9Nr13BzyyCim5uK0:-LoSFaUS1vPKkoUthMAg:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/Makefile#L42)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`cd $(SRCDIR) && make -j4` -> `$(MAKE) -C $(SRCDIR)`
</blockquote></details>

Done.
___
*[redis/README, line 8 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSBAX04Uy2MkgPoP7f:-LoSFi6MABhmCeSC-iT5:b-qjkxmc) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`in` -> `of`? I'm not 100% sure though
</blockquote></details>

Done. `of`.
___
*[redis/README, line 20 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSC3j49mZWDFKdcCqF:-LoSFoNr0hLw-tUWVoA8:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`redis-server` -> `%%`
</blockquote></details>

Done.
___
*[redis/README, line 25 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSC5O1-Jq1o10aTprm:-LoSFqYEBUZ8Isgiq2jF:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[redis/README, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSC5zm7kKxFOzBc4Pn:-LoSFwsR9-7J3XUuKIyA:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[redis/README, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/17#-LoSCHlW0wtbZp7fizu0:-LoSG5_v83Ze4PZN5nBf:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e35f13468357e60714ae789aeafe91905706711/redis/README#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`some bugs during` -> `some bugs in Graphene triggered during`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-10 22:38 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-10 22:46 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-10 22:52 UTC, yamahata approved these changes
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-10 22:55 UTC, chiache approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/17)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-11 00:36 UTC, merged