Add Memcached example
oscarlab/graphene-tests pull request #2
Opened 2019-07-02 08:50 UTC by dimakuv

This PR adds a Memcached example.

**Note!** There is still one TODO on inability to unset environment variables in Graphene. We first need to change it in Graphene code and then remove that comment from this Memcached example.

2019-07-02 19:22 UTC, mkow requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/2)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[memcached/Makefile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinNiAU6RhpFwLpTaYj:-LinNiAU6RhpFwLpTaYk:bgc853y) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/Makefile#L7)):*
> ```Makefile
> # - make SGX=1 DEBUG=1 -- create SGX debug-log manifest
> #
> # Any of these invokations clones Memcached git repository and builds Memcached
> ```

`invokations` -> `invocations`
___
*[memcached/Makefile, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinNtQIEMiCv6vflKgB:-LinNtQIEMiCv6vflKgC:b-jxhyyh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/Makefile#L8)):*
> ```Makefile
> #
> # Any of these invokations clones Memcached git repository and builds Memcached
> # in default configuration and of latest (master branch) version.
> ```

`of` -> `in the`
___
*[memcached/Makefile, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinQSZlBiyfxyBe7lj0:-LinQSZm2csD3oTn1InT:bhrcglz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/Makefile#L63)):*
> ```Makefile
> # procedure measures all Memcached dependencies (shared libraries and trusted
> # files), measures Memcached code/data pages, and adds measurements in the
> # resulting manifest.sgx file (along other, less important SGX options).
> ```

`along` -> `among`
___
*[memcached/memcached.manifest.template, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinVNCGB2QvrjApNeDk:-LinVNCGB2QvrjApNeDl:bnvof1i) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/memcached.manifest.template#L68)):*
> ```
> 
> # General notes:
> # - There is only one supported type of mount points 'chroot'.
> ```

`mount points` -> `mount points:`
___
*[memcached/memcached.manifest.template, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinWts_0KZGS1smSJ4J:-LinWtsaA2GcJBaJwygQ:bevj414) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/memcached.manifest.template#L136)):*
> ```
> # Specify all libraries used by Memcached and its dependencies (including all
> # libraries which can be loaded at runtime via dlopen). The paths to libraries
> # are host-OS paths. These libraries will be found at in-Graphene visible paths
> ```

`found at` -> `searched for in`
___
*[memcached/memcached.manifest.template, line 176 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinY16_7ZNll8On5tbH:-LinY16_7ZNll8On5tbI:b-5aie6p) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/memcached.manifest.template#L176)):*
> ```
> # Trusted no-library files include configuration files, read-only files, and
> # other static files. It is useful to specify such files here to make sure
> # they are not maliciously modified (modifications will be detect as hash
> ```

`detect` -> `detected`
___
*[memcached/memcached.manifest.template, line 197 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinYVVB2lnAamCr4qPO:-LinYVVB2lnAamCr4qPP:b-aek0fs) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/memcached.manifest.template#L197)):*
> ```
> 
> # getaddrinfo(3) configuration file. Glibc reads this file to correctly find
> # network address. For more info, see 'man gai.conf'.
> ```

`address` -> `addresses`
___
*[memcached/README, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinZCOlCmIHFs-AjAWt:-LinZ6zy9iacQG5QxtvC:b-66yoc3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/README#L24)):*
> ```
> 
> # run Memcached in non-SGX Graphene against a benchmark
> # (note -u nobody, for explanation see manifest.template file)
> ```

`manifest.template file` -> `memcached.manifest.template`


<!-- Sent from Reviewable.io -->

2019-07-02 21:39 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/2)* status: 0 of 3 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[memcached/Makefile, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinNiAU6RhpFwLpTaYj:-LiobMbl6JpUEaGBSEL5:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/Makefile#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`invokations` -> `invocations`
</blockquote></details>

Done.
___
*[memcached/Makefile, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinNtQIEMiCv6vflKgB:-LiobPJjBOkx-hEKq7iR:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/Makefile#L8)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`of` -> `in the`
</blockquote></details>

Done.
___
*[memcached/Makefile, line 63 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinQSZlBiyfxyBe7lj0:-LiobSXn1kj9RdRF6dS6:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/Makefile#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`along` -> `among`
</blockquote></details>

Done.
___
*[memcached/memcached.manifest.template, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinVNCGB2QvrjApNeDk:-LiobXwo9uoQvUYZMxAG:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/memcached.manifest.template#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`mount points` -> `mount points:`
</blockquote></details>

Done.
___
*[memcached/memcached.manifest.template, line 136 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinWts_0KZGS1smSJ4J:-LiobgPmCMOhlt1lz0jX:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/memcached.manifest.template#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`found at` -> `searched for in`
</blockquote></details>

Done.
___
*[memcached/memcached.manifest.template, line 176 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinY16_7ZNll8On5tbH:-LiobjSAEJKUwR5s6N1I:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/memcached.manifest.template#L176)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`detect` -> `detected`
</blockquote></details>

Done.
___
*[memcached/memcached.manifest.template, line 197 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinYVVB2lnAamCr4qPO:-LiobnQe3IKFW1vnkFDI:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/memcached.manifest.template#L197)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`address` -> `addresses`
</blockquote></details>

Done.
___
*[memcached/README, line 24 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/2#-LinZCOlCmIHFs-AjAWt:-LiobvCo9ZsN7DJduJ_C:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8e56271812a6bd9ccc54f451092abaad03b736ad/memcached/README#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`manifest.template file` -> `memcached.manifest.template`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-07-02 22:39 UTC, mkow submitted a review, later dismissed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/2)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2019-08-20 19:52 UTC, chiache submitted a review, later dismissed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/2)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-08-20 22:23 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/2)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-08-20 23:18 UTC, merged