include Makefile.Test instead of Makefile and remove level variable
oscarlab/graphene-tests pull request #25
Opened 2019-08-16 06:28 UTC by yamahata

LibOS/shim/test/Makefile has confusion that it's makefile for
the directory of LibOS/shim/test/ and common function for
each tests. It causes unnecessary complexity.
create Makefile.Test for common functions and use it.

Signed-off-by: Isaku Yamahata <isaku.yamahata@gmail.com>

2019-08-16 06:33 UTC, yamahata reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: 0 of 15 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/25#-LmO7S_305o0lXugZIhv:-LmO7S_305o0lXugZIhw:bk826cv) (no related file):*
This depends on https://github.com/oscarlab/graphene/pull/931

---


<!-- Sent from Reviewable.io -->

2019-08-16 15:09 UTC, mkow submitted a review, later dismissed
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required) (waiting on @HW42)



<!-- Sent from Reviewable.io -->

2019-08-16 17:58 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: all files reviewed, 1 unresolved discussion (waiting on @HW42)



<!-- Sent from Reviewable.io -->

2019-08-20 14:45 UTC, HW42 approved these changes
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2019-08-20 14:46 UTC, HW42 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: all files reviewed, 1 unresolved discussion (waiting on @HW42)



<!-- Sent from Reviewable.io -->

2019-08-26 22:44 UTC, mkow requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @HW42 and @yamahata)

___
*[apache/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/25#-LnF4YqN3ON6eTAEbG5M:-LnF4YqN3ON6eTAEbG5N:bfunhx4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d204eb6ea7a324a292a859c958757baa8b655a54/apache/Makefile#L1)):*
> ```Makefile
> HOST ?= 127.0.0.1
> ```

FYI: this will be included after rebasing to master.
___
*[lighttpd/benchmark-http.sh, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/25#-LnF4u166YRBXtkWuZLQ:-LnF4u166YRBXtkWuZLR:b-jg25ju) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d204eb6ea7a324a292a859c958757baa8b655a54/lighttpd/benchmark-http.sh#L17)):*
> ```Shell
> RESULT=result-$(date +%y%m%d-%H%M%S)
> 
> netstat --tcp --listen --program || true
> ```

What's the reason for this change?
___
*[lighttpd/Makefile, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/25#-LnF5FD-5mZQmF6vFwWq:-LnF5FD-5mZQmF6vFwWr:b-w1kbr2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d204eb6ea7a324a292a859c958757baa8b655a54/lighttpd/Makefile#L23)):*
> ```Makefile
> 	build/lib/mod_indexfile.so \
> 	build/lib/mod_dirlisting.so \
> 	build/lib/mod_staticfile.so
> ```

Already included in https://github.com/oscarlab/graphene-tests/pull/32, so I'd prefer to merge that PR first.


<!-- Sent from Reviewable.io -->

2019-08-27 14:26 UTC, yamahata reviewed
I rebased this on top of #32.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25#-:-LnIT15Y0lpeTUxCL9OW:b-qtj8tt)* status: 10 of 13 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @HW42 and @mkow)

___
*[lighttpd/benchmark-http.sh, line 17 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/25#-LnF4u166YRBXtkWuZLQ:-LnISvax7kvQTq1omxcl:bxyuqgn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d204eb6ea7a324a292a859c958757baa8b655a54/lighttpd/benchmark-http.sh#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

What's the reason for this change?
</blockquote></details>

Done. dropped this.
___
*[lighttpd/Makefile, line 23 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/25#-LnF5FD-5mZQmF6vFwWq:-LnISyg1DE7PULHWiHfY:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d204eb6ea7a324a292a859c958757baa8b655a54/lighttpd/Makefile#L23)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Already included in https://github.com/oscarlab/graphene-tests/pull/32, so I'd prefer to merge that PR first.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-27 18:42 UTC, HW42 submitted a review, later dismissed
> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: all files reviewed, 3 unresolved discussions (waiting on @HW42 and @mkow)



<!-- Sent from Reviewable.io -->

2019-09-03 00:27 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: all files reviewed, 1 unresolved discussion (waiting on @HW42)



<!-- Sent from Reviewable.io -->

2019-09-03 12:56 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: all files reviewed, 1 unresolved discussion (waiting on @HW42)



<!-- Sent from Reviewable.io -->

2019-09-03 18:08 UTC, yamahata reviewed
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/25)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-03 18:55 UTC, merged