Rewrite R example
oscarlab/graphene-tests pull request #28
Opened 2019-08-21 03:37 UTC by chiache

2019-08-21 18:36 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[r/R.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp8vYc4nZGKdYzO5ki:-Lmp8vYc4nZGKdYzO5kj:bix75x3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L10)):*
> ```
> 
> # The executable to load in Graphene. By default, $(R_HOME) points to the R
> # system installation. To run a locally-install R, specify R_HOME when running
> ```

`locally-install` -> `locally-installed`
___
*[r/R.manifest.template, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpBw1B23SJMoAx3I0C:-LmpBw1CBA7A__KRbahl:b-uu1srr) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L68)):*
> ```
> # threads than the number of TCSes. Note that Graphene also creates an internal
> # thread for handling inter-process communication (IPC), so the actual number
> # of threads that the application can create is (sgx.thread_num - 1).
> ```

Shouldn't this be `2`? See memcached example: https://github.com/oscarlab/graphene-tests/blob/35d76947e245d1a3b08c5c29eea51c0dd6497f1f/memcached/memcached.manifest.template#L126-L130
___
*[r/R.manifest.template, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpCSCE0pDB4H2e0vwk:-LmpCSCE0pDB4H2e0vwl:b-1aq00r) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L92)):*
> ```
> sgx.allowed_files.r_lib = file:$(R_HOME)/library
> 
> # Allow creating child enclaves for sh (dash)
> ```

Why `dash`? This can be any other shell and depends on the particular distribution you run this thing on.
___
*[r/README.md, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpCsEF1Agt_IMudgHt:-LmpCsEF1Agt_IMudgHu:b8d564s) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L5)):*
> ```
> The application is tested on Ubuntu 16.04, with both normal Linux and SGX platforms.
> ```

Could you create a matching PR in the main repo and add this to Jenkins? Assuming that we want to test it in CI in current state. If not, please change `is` to `was`.
___
*[r/README.md, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDGgECGNWmekUt7_N:-LmpDGgECGNWmekUt7_O:b-9d0boe) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L9)):*
> ```Markdown
> # Generating the manifest
> 
> ## Build for Linux
> ```

`Build` -> `Building` (same for other headlines in this readme)
___
*[r/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDR6WBKfgvWHZ4uBF:-LmpDR6WBKfgvWHZ4uBG:b-1lk4p5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L19)):*
> ```Markdown
> ## Build with a local R installation
> 
> By default, the `make` command build the manifest against the system R binary.
> ```

`build` -> `builds`
___
*[r/README.md, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDaHKDrApVeQmuq59:-LmpDaHKDrApVeQmuq5A:bgxy3nm) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L20)):*
> ```
> directly compiled from the source code
> ```
I'd remove this, it totally doesn't matter. What if someone downloaded a tarball? ;)
___
*[r/README.md, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDwbw0hW3CnhS4EPB:-LmpDwbw0hW3CnhS4EPC:b-mwtss7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L21)):*
> with the `R_HOME` variable

->

> with the `R_HOME` variable set accordingly
___
*[r/README.md, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpEpXp4I6tMJs4ol3w:-LmpEpXp4I6tMJs4ol3x:b-4hqzqg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L31)):*
> ```Markdown
> When running R with Graphene, please use the `--vanilla` or `--no-save` option.
> 
> Here's an example of running a R script into Graphene:
> ```

`a R script` -> `an R script`
___
*[r/sh.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpF3nj65YBq9APdVVn:-LmpF3nj65YBq9APdVVo:b9fow14) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L1)):*
> ```
> # sh (dash) manifest example
> ```

It's not always dash (see my previous comment).
___
*[r/sh.manifest.template, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpFPZA0Coj2hUgWwNq:-LmpFPZA0Coj2hUgWwNr:bdypsy7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L26)):*
> ```
> # SGX general options
> 
> # Set the virtual memory size of the SGX enclave to 256MB. For SGX v1, the enclave
> ```

Please remove `to 256MB` from the sentence, it's not too helpful and easy to get out-of-sync with the real value below.
___
*[r/sh.manifest.template, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpF_kwCppwKofMtZPt:-LmpF_kwCppwKofMtZPu:b-w1a56b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L28)):*
> ```
> If R needs virtual memory for more than 1GB, Graphene will not be able to allocate any more memory.
> ```

For example, this got out of sync with the code below ;) (ad my previous comment)
We're not running R here, nor giving it 1GB limit.
___
*[r/sh.manifest.template, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpFrdN0AOARyxrupWA:-LmpFrdN0AOARyxrupWB:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L35)):*
> ```
> # threads than the number of TCSes. Note that Graphene also creates an internal
> # thread for handling inter-process communication (IPC), so the actual number
> # of threads that the application can create is (sgx.thread_num - 1).
> ```

ditto
___
*[r/scripts/R-benchmark-25.R, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpRQNd628Ugv1Va1Gr:-LmpRQNe5suWWXBMH8CY:b-uz9q0f) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/scripts/R-benchmark-25.R#L26)):*
> ```
> # Reference for Escoufier's equivalents vectors (test III.5):
> # Escoufier Y., 1970. Echantillonnage dans une population de variables
> # aleatoires r�elles. Publ. Inst. Statis. Univ. Paris 19 Fasc 4, 1-47.
> ```

This file has broken encoding, could you fix this?
___
*[r/scripts/R-benchmark-25.R, line 34 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpRc5W6317lqxHvMP-:-LmpRc5X8EdPVY41L5SM:b4to63f) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/scripts/R-benchmark-25.R#L34)):*
> ```
> require(Matrix)		# Optimized matrix operations
> require(SuppDists)	# Optimized random number generators
> #Runif <- rMWC1019	# The fast uniform number generator
> ```

Was this line changed by us? Seems to differ from the original (I used this one to compare against: https://github.com/jtalbot/riposte/blob/master/benchmarks/other/R-benchmark-25.R)
If so, could you add a comment that this was commented out by us and the reason?
___
*[r/scripts/R-benchmark-25.R, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpRv3RDWFq [...]

2019-08-21 19:10 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[r/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp_Nzu4amYO2Wj7VUY:-Lmp_Nzv8G-hswyxgJbb:b-2m51ir) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/Makefile#L26)):*
> ```Makefile
> 
> GREP = grep
> LDD  = ldd
> ```

If LDD failed for any reason, the build is still continued, so a repeated call to `make` says `make: Nothing to be done for 'all'.`.


<!-- Sent from Reviewable.io -->

2019-08-21 19:39 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[r/R.manifest.template, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpfiJ88pHxF754V6x5:-LmpfiJ88pHxF754V6x6:bejd4wq) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L59)):*
> ```
> # SGX general options
> 
> # Set the virtual memory size of the SGX enclave to 4GB. For SGX v1, the enclave
> ```

Please remove `to 4G` from the sentence, it's not too helpful and easy to get out-of-sync with the real value below.
___
*[r/R.manifest.template, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmpfotj531qqw9PVveB:-Lmpfotj531qqw9PVveC:bub4k77) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L60)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave to 4GB. For SGX v1, the enclave
> # size must be specified during signing. If R needs virtual memory for more than
> ```

`needs virtual memory for more than` -> `needs more virtual memory than`
___
*[r/R.manifest.template, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpfeGGDswDdy-S-dxt:-LmpfeGHBPWtJUd-fSlH:b-g2skwd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L61)):*
> ```
> # Set the virtual memory size of the SGX enclave to 4GB. For SGX v1, the enclave
> # size must be specified during signing. If R needs virtual memory for more than
> # the enclave size, Graphene will not be able to allocate any more memory.
> ```

`allocate any more memory` -> `allocate it`
___
*[r/README.md, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmpdfcn5jxbp51K2ifV:-Lmpdfcn5jxbp51K2ifW:b-5nzfxo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L31)):*
> ```Markdown
> When running R with Graphene, please use the `--vanilla` or `--no-save` option.
> 
> Here's an example of running a R script into Graphene:
> ```

`into` -> `under`
___
*[r/sh.manifest.template, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmpg0ta4CP3gm1eQbph:-Lmpg0ta4CP3gm1eQbpi:bub4k77) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L27)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave to 256MB. For SGX v1, the enclave
> # size must be specified during signing. If R needs virtual memory for more than
> ```

`needs virtual memory for more than` -> `needs more virtual memory than`
___
*[r/sh.manifest.template, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmpet5ND1wVL9kCHbyW:-Lmpet5ND1wVL9kCHbyX:b-g2skwd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L28)):*
> ```
> # Set the virtual memory size of the SGX enclave to 256MB. For SGX v1, the enclave
> # size must be specified during signing. If R needs virtual memory for more than
> # 1GB, Graphene will not be able to allocate any more memory.
> ```

`allocate any more memory` -> `allocate it`


<!-- Sent from Reviewable.io -->

2019-08-27 15:36 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: 3 of 7 files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

___
*[r/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp_Nzu4amYO2Wj7VUY:-LnIfMff47Q5rIxWClm9:bod6jfy) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/Makefile#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If LDD failed for any reason, the build is still continued, so a repeated call to `make` says `make: Nothing to be done for 'all'.`.
</blockquote></details>

Done. Added an error if `ldd` has failed.
___
*[r/R.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp8vYc4nZGKdYzO5ki:-LnIfQZ8-fDiZsx4ggXL:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`locally-install` -> `locally-installed`
</blockquote></details>

Done.
___
*[r/R.manifest.template, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpfiJ88pHxF754V6x5:-LnIfVq41qv6JJrFbHNn:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please remove `to 4G` from the sentence, it's not too helpful and easy to get out-of-sync with the real value below.
</blockquote></details>

Done.
___
*[r/R.manifest.template, line 60 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmpfotj531qqw9PVveB:-LnIfWHW5yF6-GnidSGL:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`needs virtual memory for more than` -> `needs more virtual memory than`
</blockquote></details>

Done.
___
*[r/R.manifest.template, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpfeGGDswDdy-S-dxt:-LnIfX40EzvS5IJZBJvi:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`allocate any more memory` -> `allocate it`
</blockquote></details>

Done.
___
*[r/R.manifest.template, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpBw1B23SJMoAx3I0C:-LnIfZpT7l4r1l48Ai-D:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't this be `2`? See memcached example: https://github.com/oscarlab/graphene-tests/blob/35d76947e245d1a3b08c5c29eea51c0dd6497f1f/memcached/memcached.manifest.template#L126-L130
</blockquote></details>

Done.
___
*[r/R.manifest.template, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpCSCE0pDB4H2e0vwk:-LnIfiNjAJSKO41M-s2V:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L92)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why `dash`? This can be any other shell and depends on the particular distribution you run this thing on.
</blockquote></details>

Done.
___
*[r/README.md, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpCsEF1Agt_IMudgHt:-LnIfryH42NHCdLwklBG:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> The application is tested on Ubuntu 16.04, with both normal Linux and SGX platforms.
> ```

Could you create a matching PR in the main repo and add this to Jenkins? Assuming that we want to test it in CI in current state. If not, please change `is` to `was`.
</blockquote></details>

Done.
___
*[r/README.md, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDGgECGNWmekUt7_N:-LnIfsPZ6_M2Ddf7oGLu:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Build` -> `Building` (same for other headlines in this readme)
</blockquote></details>

Done.
___
*[r/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDR6WBKfgvWHZ4uBF:-LnIfsqDBgmadcnykiSm:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`build` -> `builds`
</blockquote></details>

Done.
___
*[r/README.md, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDaHKDrApVeQmuq59:-LnIgIWD0LGEo6myDisl:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> directly compiled from the source code
> ```
I'd remove this, it totally doesn't matter. What if someone downloaded a tarball? ;)
</blockquote></details>

Done.
___
*[r/README.md, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDwbw0hW3CnhS4EPB:-LnIfxKBANwDTM5s36Ja:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> with the `R_HOME` variable

->

> with the `R_HOME` variable set accordingly
</blockquote></details>

Done.
___
*[r/README.md, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpEpXp4I6tMJs4ol3w:-LnIgJVy6oWNzqOnZQh3:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`a R script` -> `an R script`
</blockquote></details>

Done.
___
*[r/README.md, line 31 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmpdfcn5jxbp51K2ifV:-LnIgL2R5CYNCNQVsWuW:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L31)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`into` -> `under`
</blockquote></details>

Done.
___
*[r/sh.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpF3nj65YBq9APdVVn:-LnIgM-P9e3Yyjs2Cqq4:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It's not always dash (see my previous comment).
</blockquote></details>

Done.
___
*[r/scripts/R-benchmark-25.R, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpRQNd628Ugv1Va1Gr:-LnIhuWQ7mLqufCFlZ2G:bd6h20n) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/scripts/R-benchmark-25.R#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary [...]

2019-08-27 15:54 UTC, donporter submitted a review, later dismissed
> Reviewed 3 of 7 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 24 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

___
*[r/R.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp8vYc4nZGKdYzO5ki:-LnIlfDyAmvJH63G9btX:b-xaqfw1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L10)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove the dash - "-ly" words are not hyphenated 


<!-- Sent from Reviewable.io -->

2019-08-29 23:33 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 4 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

___
*[r/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDR6WBKfgvWHZ4uBF:-LnUgpw78WQ0NPOpasn_:b-4k941) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L19)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now that "against" doesn't work well here (after you changed that `build`)
___
*[r/scripts/R-benchmark-25.R, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpRQNd628Ugv1Va1Gr:-LnUhshy-jxIjDs_lvVk:buz3hr6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/scripts/R-benchmark-25.R#L26)):*
Probably auto-detection in your editor managed to guess it correctly. From what I see it's in Windows-1252. Could you recode it to utf-8?

> I don't think we should change the license claim.

I don't want you to change the license, I didn't asked for anything like this.


<!-- Sent from Reviewable.io -->

2019-08-30 01:18 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 5 unresolved discussions, not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

___
*[r/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp_Nzu4amYO2Wj7VUY:-LnV5Plj7iEQ7F3sH0G-:b-ler49u) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/Makefile#L26)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done. Added an error if `ldd` has failed.
</blockquote></details>

It still doesn't work if only some of the `ldd` inputs failed (which is a common case when someone is missing libraries). In this case some of them will be resolved, but for others you'll get errors, but the whole build will (incorrectly) succeed.


<!-- Sent from Reviewable.io -->

2019-09-03 15:07 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: 3 of 7 files reviewed, 5 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @donporter and @mkow)

___
*[r/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp_Nzu4amYO2Wj7VUY:-Lnrddg035uiW8xccUCI:b-f54ji3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/Makefile#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It still doesn't work if only some of the `ldd` inputs failed (which is a common case when someone is missing libraries). In this case some of them will be resolved, but for others you'll get errors, but the whole build will (incorrectly) succeed.
</blockquote></details>

I decide to use the same script I used for Apache and Lighttpd, which runs the `ldd` command under Makefile targets. However, I don't think this can elegantly solve the problem. To be honest, I don't know any simple fix to this problem because the error checking can be extremely complicated (I don't think `ldd` itself does it very well). I don't want to make this PR any more complicated and neither do I consider this effort worthwhile.
___
*[r/R.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp8vYc4nZGKdYzO5ki:-LnrbIgK93SgR0tlUG-l:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L10)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Remove the dash - "-ly" words are not hyphenated 
</blockquote></details>

Done.
___
*[r/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpDR6WBKfgvWHZ4uBF:-LnrbGCRA8azdHWrJW0j:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/README.md#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

now that "against" doesn't work well here (after you changed that `build`)
</blockquote></details>

Done.
___
*[r/sh.manifest.template, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpF_kwCppwKofMtZPt:-LnraDuO8TRwOC5B5LrG:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> If R needs virtual memory for more than 1GB, Graphene will not be able to allocate any more memory.
> ```

For example, this got out of sync with the code below ;) (ad my previous comment)
We're not running R here, nor giving it 1GB limit.
</blockquote></details>

Done.
___
*[r/scripts/R-benchmark-25.R, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpRQNd628Ugv1Va1Gr:-LnrbDTiAV-9ZxpJoaWi:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/scripts/R-benchmark-25.R#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Probably auto-detection in your editor managed to guess it correctly. From what I see it's in Windows-1252. Could you recode it to utf-8?

> I don't think we should change the license claim.

I don't want you to change the license, I didn't asked for anything like this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-03 22:23 UTC, mkow requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @donporter, and @mkow)

___
*[r/Makefile, line 124 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntDN1d73eBto2ZiF5b:-LntDN1d73eBto2ZiF5c:bmjfaqv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cfb1060f316b55b97b1100f0a0a50fcb88331fc5/r/Makefile#L124)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	rm -f *.manifest *.manifest.sgx *.token *.sig pal_loader
> ```

Why have you changed `$(RM)` to `rm`?
___
*[r/R.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp8vYc4nZGKdYzO5ki:-Lnt98o0900bBDZOZVnm:bmtc9dv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L10)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no luck again! ;)
should be `R`, not `a R` (and even if, it should be `an`, not `a` ;) ).


<!-- Sent from Reviewable.io -->

2019-09-03 22:34 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: 5 of 7 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @mkow)

___
*[r/Makefile, line 124 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntDN1d73eBto2ZiF5b:-LntEwWxEUqJEX4FqpqB:bjbcabp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cfb1060f316b55b97b1100f0a0a50fcb88331fc5/r/Makefile#L124)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why have you changed `$(RM)` to `rm`?
</blockquote></details>

Huh, I didn't know `$(RM)` is a default variable in Makefile. Fixed.
___
*[r/R.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-Lmp8vYc4nZGKdYzO5ki:-LntFsBlANVlqnXKPoP5:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/R.manifest.template#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

no luck again! ;)
should be `R`, not `a R` (and even if, it should be `an`, not `a` ;) ).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-03 22:39 UTC, mkow requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[r/sh.manifest.template, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpF_kwCppwKofMtZPt:-LntH0lu2aW_5OAKt2Bh:bfhqml6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L28)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done.


<!-- Sent from Reviewable.io -->

2019-09-03 22:42 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: 6 of 7 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @donporter and @mkow)

___
*[r/sh.manifest.template, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LmpF_kwCppwKofMtZPt:-LntHdNH9zuW66OS0CXx:bmsoso1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf176d3b9935f41e2988d318eff88edcf6779860/r/sh.manifest.template#L28)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Not done.
</blockquote></details>

Changed `R` to `sh`.


<!-- Sent from Reviewable.io -->

2019-09-03 22:46 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-03 22:58 UTC, yamahata requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 3 unresolved discussions (waiting on @chiache)

___
*[r/Makefile, line 55 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntHtfmDkmjr93Mw-Rh:-LntHtfn2SpYzbNCWRvC:b-icedyn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cfb1060f316b55b97b1100f0a0a50fcb88331fc5/r/Makefile#L55)):*
> ```Makefile
> .INTERMEDIATE: R-ldd
> R-ldd:
> 	@for F in $(R_TARGETS); do ldd $$F >> $@ || exit 1; done
> ```

There is no point to use for because ldd accepts multiple files.
ldd $(R_TARGETS) > $@
___
*[r/Makefile, line 59 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntIFLMCu_L4Yab-6Va:-LntIFLMCu_L4Yab-6Vb:b-th6bk1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cfb1060f316b55b97b1100f0a0a50fcb88331fc5/r/Makefile#L59)):*
> ```Makefile
> .INTERMEDIATE: R-deps
> R-deps: R-ldd
> 	@cat $< | awk '{if ($$2 =="=>") {split($$1,s,/\./); print s[1]}}' \
> ```

it seems redundant to have R-ldd, R-deps and R-trusted-libs.
In short, one rule should do it. something like
ldd $(R_TARGETS) | awk '{if ($$2 == "=>") {...;N=...;printf("sgx.trusted_files."N" = file:"$$3)}}' | sort  | uniq | grep -v -x ... > $@
___
*[r/Makefile, line 76 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntK2tS2tqcgpxFHGiz:-LntK2tS2tqcgpxFHGj-:b-d57qsn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/49ca42b79783eed9531e73eae80554e13cdfdc7e/r/Makefile#L76)):*
> ```Makefile
> #       sgx.trusted_files.xxxx = file:xxxx
> 
> R.manifest: R.manifest.template R-trusted-libs
> ```

Those rule seems very redundant among apps.

Pal/src/host/Linux-SGX/Makefile.Test should be reused.
For now I don't block due to those because all the Makefile needs to be touched and the  stable release is soon.


<!-- Sent from Reviewable.io -->

2019-09-03 22:59 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 3 unresolved discussions (waiting on @chiache)



<!-- Sent from Reviewable.io -->

2019-09-03 22:59 UTC, yamahata approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 3 unresolved discussions (waiting on @chiache)



<!-- Sent from Reviewable.io -->

2019-09-03 23:14 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 3 unresolved discussions (waiting on @yamahata)

___
*[r/Makefile, line 55 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntHtfmDkmjr93Mw-Rh:-LntO9fx5JZm0IyfdTRw:bm73cwt) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cfb1060f316b55b97b1100f0a0a50fcb88331fc5/r/Makefile#L55)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

There is no point to use for because ldd accepts multiple files.
ldd $(R_TARGETS) > $@
</blockquote></details>

This was the way it was implemented before, but `ldd` doesn't handle failure well. If one of the binaries is missing, `ldd` will succeed without returning any error code.
___
*[r/Makefile, line 59 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntIFLMCu_L4Yab-6Va:-LntOWqR4Zy3Om3pn9ge:b-9cu4y7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cfb1060f316b55b97b1100f0a0a50fcb88331fc5/r/Makefile#L59)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

it seems redundant to have R-ldd, R-deps and R-trusted-libs.
In short, one rule should do it. something like
ldd $(R_TARGETS) | awk '{if ($$2 == "=>") {...;N=...;printf("sgx.trusted_files."N" = file:"$$3)}}' | sort  | uniq | grep -v -x ... > $@




</blockquote></details>

We separated the `ldd` rule from the rest of the command because the shell does not return exit status from the pipeline.
___
*[r/Makefile, line 76 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntK2tS2tqcgpxFHGiz:-LntOlay0bSJMC5EMoMR:b-9sgc2e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/49ca42b79783eed9531e73eae80554e13cdfdc7e/r/Makefile#L76)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

Those rule seems very redundant among apps.

Pal/src/host/Linux-SGX/Makefile.Test should be reused.
For now I don't block due to those because all the Makefile needs to be touched and the  stable release is soon.

</blockquote></details>

Actually, one purpose of cleaning up the applications is to make these applications independent from the main source code and can be built and signed out-of-tree. Using `Makefile.Test` defeats this purpose.

I think we should try to deprecate `Makefile.Test` in the long run.


<!-- Sent from Reviewable.io -->

2019-09-03 23:22 UTC, yamahata submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 1 unresolved discussion (waiting on @chiache)

___
*[r/Makefile, line 76 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntK2tS2tqcgpxFHGiz:-LntQK1gEoG1Fusxqwlh:bhrsqaz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/49ca42b79783eed9531e73eae80554e13cdfdc7e/r/Makefile#L76)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Actually, one purpose of cleaning up the applications is to make these applications independent from the main source code and can be built and signed out-of-tree. Using `Makefile.Test` defeats this purpose.

I think we should try to deprecate `Makefile.Test` in the long run.
</blockquote></details>

My concern is that we're duplicating similar recipe in Makefies.
We should create Makefile.lib (or something) in graphene-tests and re-use it.


<!-- Sent from Reviewable.io -->

2019-09-03 23:33 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)

___
*[r/Makefile, line 76 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/28#-LntK2tS2tqcgpxFHGiz:-LntTIyp515jsiSYh8o3:b-uifhez) ([raw file](https://github.com/oscarlab/graphene-tests/blob/49ca42b79783eed9531e73eae80554e13cdfdc7e/r/Makefile#L76)):*
<details><summary><i>Previously, yamahata wrote…</i></summary><blockquote>

My concern is that we're duplicating similar recipe in Makefies.
We should create Makefile.lib (or something) in graphene-tests and re-use it.


</blockquote></details>

That could be a good idea. We should discuss this after the stable release.


<!-- Sent from Reviewable.io -->

2019-09-03 23:54 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: all files reviewed, 1 unresolved discussion (waiting on @yamahata)



<!-- Sent from Reviewable.io -->

2019-09-03 23:57 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/28)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-04 00:49 UTC, merged