Rewrite Python example
oscarlab/graphene-tests pull request #29
Opened 2019-08-21 08:41 UTC by chiache

2019-08-21 16:04 UTC, donporter submitted a review, later dismissed
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab)

___
*[python/resolv.conf, line 0 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmoumTu-vFSiQ5DN8Iy:-LmoumTv2aLBv8L7s07I:b-4ebzmj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/resolv.conf#L0)):*
I think we needed this for one test to work in Jenkins.  Make sure to test this before merging.


<!-- Sent from Reviewable.io -->

2019-08-21 19:39 UTC, mkow requested changes
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpWdiRDRuCI9Ujt-Mm:-LmpWdiS8pUCIT2knxF4:be8u5ze) (no related file):*
Could you please create a matching PR in the main repo? This way we could test this on Jenkins.

---
___
*[python/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpZhf7Ev-XvY7yikf8:-LmpZhf7Ev-XvY7yikf9:b-8k4jnf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L27)):*
> ```Makefile
> 
> GREP = grep
> LDD  = ldd
> ```

If LDD failed for any reason, the build is still continued.

I got:
```
ldd: /usr/lib/python2.7/dist-packages/numpy/linalg/lapack_lite.x86_64-linux-gnu.so: No such file or directory
```
And the next, repeated `make` said `make: Nothing to be done for 'all'.` instead of trying again
___
*[python/Makefile, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpaCXq8HuB2k8gPD72:-LmpaCXq8HuB2k8gPD73:bua2qty) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L94)):*
> ```Makefile
> 	ln -s $(GRAPHENEDIR)/Runtime/pal_loader $@
> 
> regression:
> ```

this should be `.PHONY`
Also, I don't think we use this target name in any other example?
___
*[python/Makefile, line 98 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpax_z1pxD7w0hnymK:-Lmpax_z1pxD7w0hnymL:b-xf8kbi) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L98)):*
> ```Makefile
> 	@$(MAKE) >> /dev/null 2>&1
> 
> 	@echo "\n\nRun helloworld.py:"
> ```

`Run` -> `Running` (same in other places)
___
*[python/Makefile, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpat2t8yGkeloLyGYS:-Lmpat2t8yGkeloLyGYT:bb1jdwb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L106)):*
> ```Makefile
> 	./pal_loader python.manifest scripts/fibonacci.py  > OUTPUT
> 	$(GREP) -q "fib2              55" OUTPUT
> 	@$(RM) -f OUTPUT
> ```

why `-f`?
___
*[python/Makefile, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpb3zh7GNoZifRbQ6L:-Lmpb3zh7GNoZifRbQ6M:b-8ir2a) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L116)):*
> ```Makefile
> 	./web-test.sh
> 
> # Clean up
> ```

This comment is useless, please remove
___
*[python/python.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpfEoc3AKiqUJkYAl_:-LmpfEod-TWvdpSLtsZU:bix75x3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L10)):*
> ```
> 
> # The executable to load in Graphene. By default, $(PYTHONHOME) points to the
> # system installation. To run a locally-install Python, specify PYTHONHOME when
> ```

`locally-install` -> `locally-installed`
___
*[python/python.manifest.template, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpeYON4J5scW5v-ASm:-LmpeYON4J5scW5v-ASn:b-977nsz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L59)):*
> ```
> # SGX general options
> 
> # Set the virtual memory size of the SGX enclave to 1GB. For SGX v1, the enclave
> ```

Please remove `to 1G` from the sentence, it's not too helpful and easy to get out-of-sync with the real value below.
___
*[python/python.manifest.template, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpel6u79HejE8FOFfp:-Lmpel6u79HejE8FOFfq:b-g2skwd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L61)):*
> ```
> # Set the virtual memory size of the SGX enclave to 1GB. For SGX v1, the enclave
> # size must be specified during signing. If Python needs more virtual memory
> # than the enclave size, Graphene will not be able to allocate any more memory.
> ```

`allocate any more memory` -> `allocate it`
___
*[python/python.manifest.template, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpf1SM2CrsB1-D1N3V:-Lmpf1SM2CrsB1-D1N3W:b-b8votu) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L68)):*
> ```
> # threads than the number of TCSes. Note that Graphene also creates an internal
> # thread for handling inter-process communication (IPC), so the actual number
> # of threads that the application can create is (sgx.thread_num - 1).
> ```

Should be `2`. See https://github.com/oscarlab/graphene-tests/blob/35d76947e245d1a3b08c5c29eea51c0dd6497f1f/memcached/memcached.manifest.template#L126-L130
___
*[python/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpcXW96l-7HuKT9MFL:-LmpcXW96l-7HuKT9MFM:b-gacp3z) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L1)):*
> ```Markdown
> # Python 2.7 example
> ```

FYI: we should convert this to Python 3 quite soon, Python 2 will be deprecated globally in the near future.
___
*[python/README.md, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpczifAkmQYwxRPFSC:-LmpczifAkmQYwxRPFSD:bgmdr5v) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L9)):*
> ```Markdown
> # Generating the manifest
> 
> ## Build for Linux
> ```

`Build` -> `Building` (same for other places in this file)
___
*[python/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpd7X23_YJMgQOS3H6:-Lmpd7X23_YJMgQOS3H7:b-1lk4p5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L19)):*
> ```Markdown
> ## Build with a local Python installation
> 
> By default, the `make` command build the manifest against the system installation.
> ```

`build` -> `builds`
___
*[python/README.md, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpfUx159_2puYF-m2G:-LmpfUx159_2puYF-m2H:b8nx34a) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L20)):*
> ```
> directly compiled from the source code
> ```

I'd remove this, it totally doesn't matter. What if someone downloaded a tarball? ;)
___
*[python/README.md, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpdD8CB9r76qXegfKB:-LmpdD8CB9r76qXegfKC:bpraanb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L21)):*
> with the `PYTHONHOME` variable

->

> with the `PYTHONHOME` variable set accordingly
___
*[python/README.md, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpdNu83eP2ykS3ImV4:-LmpdNu83eP2ykS3ImV5:b-5nzfxo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L29)):*
> ```Markdown
> # Run Python with Graphene
> 
> Here's an example of running a Python script into Graphene:
> ```

`into` -> `under`
___
*[python/scripts/test-numpy.py, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpbROsC024Wj1e3BbQ:-LmpbROt21oM_96Qh5Is:b-pd4797) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/scripts/test-numpy.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

`py [...]

2019-08-27 16:34 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: 8 of 15 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @donporter, and @mkow)

___
*[python/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpZhf7Ev-XvY7yikf8:-LnImYU5EGg3q3SsiSEl:blc5zsp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

If LDD failed for any reason, the build is still continued.

I got:
```
ldd: /usr/lib/python2.7/dist-packages/numpy/linalg/lapack_lite.x86_64-linux-gnu.so: No such file or directory
```
And the next, repeated `make` said `make: Nothing to be done for 'all'.` instead of trying again
</blockquote></details>

Done. Added an error when `ldd` fails.
___
*[python/Makefile, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpaCXq8HuB2k8gPD72:-LnIurDk5J1bNeyYdNu_:b-8cu52i) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L94)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

this should be `.PHONY`
Also, I don't think we use this target name in any other example?
</blockquote></details>

Right, the `regression` target is not a convention in the `apps` directory. I've moved the command to `run-tests.sh`. I will make the change in the Jenkins files.
___
*[python/Makefile, line 106 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpat2t8yGkeloLyGYS:-LnIv-HF7PxmgXa3zubw:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L106)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why `-f`?
</blockquote></details>

Done.
___
*[python/Makefile, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpb3zh7GNoZifRbQ6L:-LnIv07cApZjvz3vunz-:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L116)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This comment is useless, please remove
</blockquote></details>

Done.
___
*[python/python.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpfEoc3AKiqUJkYAl_:-LnIvBWp1oWq4_mk_mEC:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`locally-install` -> `locally-installed`
</blockquote></details>

Done.
___
*[python/python.manifest.template, line 59 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpeYON4J5scW5v-ASm:-LnIqPU66lKqzb-1SeDX:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please remove `to 1G` from the sentence, it's not too helpful and easy to get out-of-sync with the real value below.
</blockquote></details>

Done.
___
*[python/python.manifest.template, line 61 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpel6u79HejE8FOFfp:-LnIqOe9Chcy7eprLAjW:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L61)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`allocate any more memory` -> `allocate it`
</blockquote></details>

Done.
___
*[python/python.manifest.template, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpf1SM2CrsB1-D1N3V:-LnIqCHvBW1ZE2kXHCrW:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Should be `2`. See https://github.com/oscarlab/graphene-tests/blob/35d76947e245d1a3b08c5c29eea51c0dd6497f1f/memcached/memcached.manifest.template#L126-L130
</blockquote></details>

Done.
___
*[python/README.md, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpczifAkmQYwxRPFSC:-LnIqEJK0gS_PGPAT_0c:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L9)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Build` -> `Building` (same for other places in this file)
</blockquote></details>

Done.
___
*[python/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpd7X23_YJMgQOS3H6:-LnIqEoQC9LwphXUDaPa:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`build` -> `builds`
</blockquote></details>

Done.
___
*[python/README.md, line 20 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpfUx159_2puYF-m2G:-LnIqFQ-Ez7BhTIc6x6q:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L20)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> directly compiled from the source code
> ```

I'd remove this, it totally doesn't matter. What if someone downloaded a tarball? ;)
</blockquote></details>

Done.
___
*[python/README.md, line 21 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpdD8CB9r76qXegfKB:-LnIqGn1A5eVHGJ5-Dtv:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> with the `PYTHONHOME` variable

->

> with the `PYTHONHOME` variable set accordingly
</blockquote></details>

Done.
___
*[python/README.md, line 29 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpdNu83eP2ykS3ImV4:-LnIqHdq69erwjjkBJT3:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L29)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`into` -> `under`
</blockquote></details>

Done.
___
*[python/scripts/test-numpy.py, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpbROsC024Wj1e3BbQ:-LnIvE9uCAj-jD3-MliS:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/scripts/test-numpy.py#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`python2`
</blockquote></details>

Done.
___
*[python/scripts/test-scipy.py, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpc515DyZs0n8smosv:-LnIvDbx-fD8hNr91dVX:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/scripts/test-scipy.py#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`python2`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-27 16:43 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: 8 of 15 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @donporter, and @mkow)

___
*[python/Makefile, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpaCXq8HuB2k8gPD72:-LnIxLk5-k6I3rAozBvH:b-40x59r) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L94)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Right, the `regression` target is not a convention in the `apps` directory. I've moved the command to `run-tests.sh`. I will make the change in the Jenkins files.
</blockquote></details>

Renamed the rule to `test`.
___
*[python/Makefile, line 98 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpax_z1pxD7w0hnymK:-LnIxUvAC3iC67qOnRnU:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L98)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Run` -> `Running` (same in other places)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-08-30 01:27 UTC, mkow requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[python/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpZhf7Ev-XvY7yikf8:-LnV4tFJCAfrsWCd8CAw:b-ler49u) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L27)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done. Added an error when `ldd` fails.
</blockquote></details>

It still doesn't work if only some of the `ldd` inputs failed (which is a common case when someone is missing libraries). In this case some of them will be resolved, but for others you'll get errors, but the whole build will (incorrectly) succeed.
___
*[python/python.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpfEoc3AKiqUJkYAl_:-LnV5r1M9gcTVmNb5hUJ:bc49ozf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L10)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actually, this should be written without the hyphen (see Don's comment under the R PR)
___
*[python/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpd7X23_YJMgQOS3H6:-LnV671Q0-LzeE13Xomv:bui0aky) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L19)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now it doesn't look good in connection with `against`
___
*[python/run-tests.sh, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV74nOCj4p9YGI_Z97:-LnV74nP3OUgg_HeaLhs:bskj8oz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L5)):*
> ```Shell
> set -e
> 
> echo "\n\nRunning helloworld.py:"
> ```

`-e` is missing
___
*[python/run-tests.sh, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV77Hd346hLNBKElPq:-LnV77Hd346hLNBKElPr:bskj8oz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L10)):*
> ```Shell
> rm OUTPUT
> 
> echo "\n\nRunning fibonacci.py:"
> ```

`-e` is missing
___
*[python/run-tests.sh, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV7ETp7I5vWFfLCewe:-LnV7ETp7I5vWFfLCewf:b-g5k02m) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L11)):*
> ```Shell
> 
> echo "\n\nRunning fibonacci.py:"
> ./pal_loader python.manifest scripts/fibonacci.py  > OUTPUT
> ```

please remove double space
___
*[python/run-tests.sh, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV77wICAtar_FmGbv5:-LnV77wICAtar_FmGbv6:bskj8oz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L15)):*
> ```Shell
> rm OUTPUT
> 
> echo "\n\nRunning test-numpy.py:"
> ```

`-e` is missing
___
*[python/run-tests.sh, line 18 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV7MJk2YrHB9-DSw2W:-LnV7MJk2YrHB9-DSw2X:b-6dm1l) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L18)):*
> ```Shell
> ./pal_loader python.manifest scripts/test-numpy.py > OUTPUT
> grep -q "maxint: " OUTPUT && echo "[ SUCCESS ]"
> cat OUTPUT
> ```

why do we need this `cat`?
___
*[python/run-tests.sh, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV78aG4yPCXUG5uZ3-:-LnV78aG4yPCXUG5uZ30:bskj8oz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L21)):*
> ```Shell
> rm OUTPUT
> 
> echo "\n\nRunning test-scipy.py:"
> ```

`-e` is missing
___
*[python/run-tests.sh, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV7OF7-G0xu026Yvmd:-LnV7OF7-G0xu026Yvme:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L24)):*
> ```Shell
> ./pal_loader python.manifest scripts/test-scipy.py > OUTPUT
> grep -q "cholesky: " OUTPUT && echo "[ SUCCESS ]"
> cat OUTPUT
> ```

ditto


<!-- Sent from Reviewable.io -->

2019-08-30 18:30 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

___
*[python/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpZhf7Ev-XvY7yikf8:-LnYlBVPCp9Ev7kDtjgE:bgh2u0v) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

It still doesn't work if only some of the `ldd` inputs failed (which is a common case when someone is missing libraries). In this case some of them will be resolved, but for others you'll get errors, but the whole build will (incorrectly) succeed.
</blockquote></details>

To be fair, some of the test actually succeed to run, since Python loads the .so files dynamically. In my case, python-scipy was missing, but I was able to run helloworld, fibonacci and numpy. Maybe hardcoding and documenting what distribution packages should be installed is a better alternative?
___
*[python/Makefile, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnTpmkg95dFG7-Y_ZLn:-LnTpmkg95dFG7-Y_ZLo:b-mg85sh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/Makefile#L60)):*
> ```Makefile
> 
> ifeq ($(PY_ALL_DEPS),)
> $(error "`$(LDD) $(PY_LIBS)` failed.")
> ```

This only fires if PY_ALL_DEPS is empty, but not if only some of the PY_LIBS are missing, right? Just checking if that is the intention.
___
*[python/README.md, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnYmMOW55N1TnYevjQ9:-LnYmMOW55N1TnYevjQA:bb3ty6p) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/README.md#L7)):*
> ```Markdown
> tested on Ubuntu 16.04, with both normal Linux and SGX platforms. Python 3 is not
> yet tested in Graphene.
> ```

Mention which Ubuntu packages we assume are installed? Most importantly num and scipy, I assume.


<!-- Sent from Reviewable.io -->

2019-09-03 21:09 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: 11 of 15 files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @mkow, and @thomasknauth)

___
*[python/Makefile, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpZhf7Ev-XvY7yikf8:-LnstWos83poXZxjE2jD:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/Makefile#L27)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

To be fair, some of the test actually succeed to run, since Python loads the .so files dynamically. In my case, python-scipy was missing, but I was able to run helloworld, fibonacci and numpy. Maybe hardcoding and documenting what distribution packages should be installed is a better alternative?
</blockquote></details>

Fixed.
___
*[python/Makefile, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnTpmkg95dFG7-Y_ZLn:-LnstWS57bXBlTCy1mSQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/Makefile#L60)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

This only fires if PY_ALL_DEPS is empty, but not if only some of the PY_LIBS are missing, right? Just checking if that is the intention.
</blockquote></details>

Done.
___
*[python/python.manifest.template, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LmpfEoc3AKiqUJkYAl_:-Lnst_HZ5W8eUmERApy1:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/python.manifest.template#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

actually, this should be written without the hyphen (see Don's comment under the R PR)
</blockquote></details>

Done.
___
*[python/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lmpd7X23_YJMgQOS3H6:-LnsuGlD-Ye9nQFqDUbq:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d4663b49952bcd16cee4e8833a0aaed633cad026/python/README.md#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

now it doesn't look good in connection with `against`
</blockquote></details>

Done.
___
*[python/README.md, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnYmMOW55N1TnYevjQ9:-Lnsth6CExI8CLvsxxo-:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/README.md#L7)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Mention which Ubuntu packages we assume are installed? Most importantly num and scipy, I assume.
</blockquote></details>

Done.
___
*[python/run-tests.sh, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV74nOCj4p9YGI_Z97:-LnsufhM6luyevDpT7mf:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`-e` is missing
</blockquote></details>

Done.
___
*[python/run-tests.sh, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV77Hd346hLNBKElPq:-LnsufuaC-09tdYV2i5z:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`-e` is missing
</blockquote></details>

Done.
___
*[python/run-tests.sh, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV7ETp7I5vWFfLCewe:-LnsugJ-Ebft4Vo_Bx07:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please remove double space
</blockquote></details>

Done.
___
*[python/run-tests.sh, line 15 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV77wICAtar_FmGbv5:-LnsujP29N1V-ZOMYM8Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`-e` is missing
</blockquote></details>

Done.
___
*[python/run-tests.sh, line 18 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV7MJk2YrHB9-DSw2W:-Lnsunhg9JWttKqkH7ix:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

why do we need this `cat`?
</blockquote></details>

Done.
___
*[python/run-tests.sh, line 21 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV78aG4yPCXUG5uZ3-:-Lnsuo0H9651kyf5EI9P:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`-e` is missing
</blockquote></details>

Done.
___
*[python/run-tests.sh, line 24 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnV7OF7-G0xu026Yvmd:-LnsuoYt337jG0P2DxjT:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/run-tests.sh#L24)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-04 00:19 UTC, mkow requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @thomasknauth)

___
*[python/Makefile, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnTpmkg95dFG7-Y_ZLn:-LntaxUp44lK0wb8Bjl4:bpw92fi) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/Makefile#L60)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@chiache that doesn't sound like an answer to Thomas' question ;)
___
*[python/Makefile, line 46 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LntaJOo79F3uQoP6Q3o:-LntaJOo79F3uQoP6Q3p:bl9o806) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d232fb8cd9500b95bf1660fdd518915fb1bd6248/python/Makefile#L46)):*
> ```Makefile
> # We need to replace Glibc dependencies with Graphene-specific Glibc. The Glibc
> # binaries are already listed in the manifest template, so we can skip them
> # from the ldd results
> ```

Please end the sentence with either `:` or `.`.
___
*[python/README.md, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lntbtd11I7ObbIEfhmz:-Lntbtd50-fkax82Llpn:bw849gq) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d232fb8cd9500b95bf1660fdd518915fb1bd6248/python/README.md#L13)):*
> ```Markdown
> 
> For generating the manifest and running the test scripts, please run the following
> command to install the required Python packages:
> ```

Please mention that this is Debian/Ubuntu-specific.


<!-- Sent from Reviewable.io -->

2019-09-04 00:54 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 2 unresolved discussions (waiting on @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-09-04 00:55 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 2 unresolved discussions (waiting on @thomasknauth)

___
*[python/Makefile, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LnTpmkg95dFG7-Y_ZLn:-LntddDL6jGBepiqQ-sG:bhisxdo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/96f66884756adc14fc4ccbea9411749a0a2c6b7c/python/Makefile#L60)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@chiache that doesn't sound like an answer to Thomas' question ;)
</blockquote></details>

Sorry, I should explain that the check for empty`PY_ALL_DEPS` is no longer used. 
___
*[python/Makefile, line 46 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LntaJOo79F3uQoP6Q3o:-LnteP0J5UaZXoW4SbDQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d232fb8cd9500b95bf1660fdd518915fb1bd6248/python/Makefile#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please end the sentence with either `:` or `.`.
</blockquote></details>

Done.
___
*[python/README.md, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lntbtd11I7ObbIEfhmz:-LnteQU96Vt-nglSqI4M:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d232fb8cd9500b95bf1660fdd518915fb1bd6248/python/README.md#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please mention that this is Debian/Ubuntu-specific.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-04 11:02 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 2 unresolved discussions (waiting on @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-09-05 22:38 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 9 unresolved discussions (waiting on @chiache and @thomasknauth)

___
*[python/Makefile, line 51 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lo2YGVe8Wjq95GM_JOY:-Lo2YGVe8Wjq95GM_JOZ:blnuqum) ([raw file](https://github.com/oscarlab/graphene-tests/blob/35d76947e245d1a3b08c5c29eea51c0dd6497f1f/python/Makefile#L51)):*
> ```Makefile
> 	rm -f python.manifest.sgx
> 
> distclean: clean
> ```

Can we add distclean target as an alias to clean. Just for uniformity with other apps.
___
*[python/Makefile, line 85 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lo2Y7Vd3TGf0Yr7WQUx:-Lo2Y7Vd3TGf0Yr7WQUy:b-d23v5s) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf8fd144b804a9fe09dc2ef91d120dd9e6ec16b4/python/Makefile#L85)):*
> ```Makefile
> # Python manifests:
> #   For each dependency, generate a rule as follows:
> #       sgx.trusted_files.xxxx = file:xxxx
> ```

This looks like a useless comment
___
*[python/python.manifest.template, line 11 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lo2YZC36shfWuSTu-uC:-Lo2YZC36shfWuSTu-uD:b-agz1cv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf8fd144b804a9fe09dc2ef91d120dd9e6ec16b4/python/python.manifest.template#L11)):*
> ```
> # The executable to load in Graphene. By default, $(PYTHONHOME) points to the
> # system installation. To run Python from a local installation, specify PYTHONHOME
> # when running `make` in this directory.
> ```

Why are you talking about `PYTHONHOME` in the comment? The code uses `PYTHONEXEC`.
___
*[python/python.manifest.template, line 24 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lo2YlDW9LdA6R-nV2jk:-Lo2YlDX7lFegst8AuOS:b-a6qfqh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf8fd144b804a9fe09dc2ef91d120dd9e6ec16b4/python/python.manifest.template#L24)):*
> ```
> loader.env.USERNAME =
> loader.env.HOME =
> loader.env.PWD =
> ```

Are these three envvars actually needed by Python?
___
*[python/python.manifest.template, line 82 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lo2Yv7b4KGUtiKWYs_q:-Lo2Yv7b4KGUtiKWYs_r:bqn3s8y) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf8fd144b804a9fe09dc2ef91d120dd9e6ec16b4/python/python.manifest.template#L82)):*
> ```
> sgx.trusted_files.libutil = file:$(GRAPHENEDIR)/Runtime/libutil.so.1
> sgx.trusted_files.libpthread = file:$(GRAPHENEDIR)/Runtime/libpthread.so.0
> sgx.trusted_files.libz = file:/lib/x86_64-linux-gnu/libz.so.1
> ```

Libz in not part of Glibc, must be in a separate list
___
*[python/python.manifest.template, line 84 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lo2Yzd93qIbjQe1iLKc:-Lo2Yzd93qIbjQe1iLKd:bdo7f96) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf8fd144b804a9fe09dc2ef91d120dd9e6ec16b4/python/python.manifest.template#L84)):*
> ```
> sgx.trusted_files.libz = file:/lib/x86_64-linux-gnu/libz.so.1
> 
> # Other libraries (for numpy)
> ```

Why do you say `for numpy`? These are all trusted libs, not only numpy-related.
___
*[python/README.md, line 32 at r5](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lo2ZWzB0faBHaywUvFG:-Lo2ZWzCBD3P2c8s66Kg:b-gb4imh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/cf8fd144b804a9fe09dc2ef91d120dd9e6ec16b4/python/README.md#L32)):*
> ```Markdown
> 
> ```
> make PYTHONHOME=<install path>/lib/python2.7 SGX=1
> ```

Shouldn't the user also change `PYTHONEXEC` if she changes `PYTHONHOME`?


<!-- Sent from Reviewable.io -->

2019-10-31 20:31 UTC, dimakuv commented
I took ownership of this PR and moving it to Python3

2019-10-31 23:31 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: 9 of 18 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @chiache and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LsZ8CqGAJMuCALMlEgY:-LsZ8CqGAJMuCALMlEgZ:b-i31yzf) (no related file):*
I started re-writing this PR for Python3. I pushed some changes, but there are still many things to debug and fix:

- Linux PAL fails with segfault on numpy and scipy scripts for no obvious reason -- need to investigate.
- Both Linux and Linux-SGX PALs fail on web-test -- they cannot resolve the URL it seems.
- Not all dynamically loaded Python libs are handled by our Makefile -- there are more Python libs, and they depend on more Linux libs.

In general, Python is a nightmare. There are so many libraries loaded at run-time, and they are non-trivial. Our Makefile partially hides this complexity (by trying to automatically detect the transitive closure of all libs) but this becomes unreadable and incomprehensible. We need a better strategy to deal with library explosion.

---


<!-- Sent from Reviewable.io -->

2019-11-14 00:52 UTC, dimakuv approved these changes
> Reviewed 17 of 18 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LsZ8CqGAJMuCALMlEgY:-LtbNjgC0JAlhEi6TYOO:b-ogfb32) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I started re-writing this PR for Python3. I pushed some changes, but there are still many things to debug and fix:

- Linux PAL fails with segfault on numpy and scipy scripts for no obvious reason -- need to investigate.
- Both Linux and Linux-SGX PALs fail on web-test -- they cannot resolve the URL it seems.
- Not all dynamically loaded Python libs are handled by our Makefile -- there are more Python libs, and they depend on more Linux libs.

In general, Python is a nightmare. There are so many libraries loaded at run-time, and they are non-trivial. Our Makefile partially hides this complexity (by trying to automatically detect the transitive closure of all libs) but this becomes unreadable and incomprehensible. We need a better strategy to deal with library explosion.
</blockquote></details>

Done. Fixed all the above issues. Some of the require bug fixes in Graphene: https://github.com/oscarlab/graphene/pull/1123 and https://github.com/oscarlab/graphene/pull/1145.

---
___
*[python-simple/python.manifest.template, line 243 at r7](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LtbOET96-MHQ_oIcy_r:-LtbOETA-qOSZyaN7H4X:b-r1nql) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7c43fa23563643a3d306c6a154341a42a197b844/python-simple/python.manifest.template#L243)):*
> ```
> sgx.trusted_files.pythonhttp119 = file:$(PYTHONDISTHOME)/apport/packaging.py
> sgx.trusted_files.pythonhttp120 = file:$(PYTHONHOME)/encodings/idna.py
> sgx.trusted_files.pythonhttp121 = file:$(PYTHONHOME)/stringprep.py
> ```

Do I hate Python? Yes, I do hate Python. 121 scripts just to run a simple web server.


<!-- Sent from Reviewable.io -->

2019-11-14 01:01 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-11-15 13:46 UTC, donporter submitted a review, later dismissed
> Reviewed 17 of 18 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-11-18 19:53 UTC, donporter requested changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @chiache)

___
*[python-simple/run-tests.sh, line 27 at r9](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lu-3o5QAFNPUx2PSscQ:-Lu-3o5QAFNPUx2PSscR:b5144co) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a51f3f54b87ff4f813c62336720be07119c0dcd4/python-simple/run-tests.sh#L27)):*
> ```Shell
> echo >> OUTPUT2  # include newline since wget doesn't add it
> diff -q OUTPUT1 OUTPUT2 && echo "[ Success 3/3 ]"
> kill `cat server.PID` | true
> ```

do you really want a pipe here?
___
*[python-simple/Makefile, line 117 at r9](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lu-3rrI1MrjSNXA3rEV:-Lu-3rrI1MrjSNXA3rEW:b-vma2ss) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a51f3f54b87ff4f813c62336720be07119c0dcd4/python-simple/Makefile#L117)):*
> ```Makefile
> regression: all
> 	./run-tests.sh
> 	exit 0
> ```

Do we not want to propagate an error code out?


<!-- Sent from Reviewable.io -->

2019-11-18 20:00 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @donporter)

___
*[python-simple/run-tests.sh, line 27 at r9](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lu-3o5QAFNPUx2PSscQ:-Lu-5YotE388XgCEUsfT:bi3q0dg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a51f3f54b87ff4f813c62336720be07119c0dcd4/python-simple/run-tests.sh#L27)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

do you really want a pipe here?
</blockquote></details>

I should have mentioned not to review this PR yet. I am actively debugging the issues with our Jenkins pipelines, so these changes are for test purposes only. (I marked these commits as "DO NOT USE".)
___
*[python-simple/Makefile, line 117 at r9](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lu-3rrI1MrjSNXA3rEV:-Lu-5GNk7eMpfMvFZu15:bi3q0dg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a51f3f54b87ff4f813c62336720be07119c0dcd4/python-simple/Makefile#L117)):*
<details><summary><i>Previously, donporter (Don Porter) wrote…</i></summary><blockquote>

Do we not want to propagate an error code out?
</blockquote></details>

I should have mentioned not to review this PR yet. I am actively debugging the issues with our Jenkins pipelines, so these changes are for test purposes only. (I marked these commits as "DO NOT USE".)


<!-- Sent from Reviewable.io -->

2019-11-19 21:18 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 2 unresolved discussions (waiting on @donporter)

___
*[python-simple/run-tests.sh, line 27 at r9](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lu-3o5QAFNPUx2PSscQ:-Lu4WnXi-4emTFaCkgg8:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a51f3f54b87ff4f813c62336720be07119c0dcd4/python-simple/run-tests.sh#L27)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I should have mentioned not to review this PR yet. I am actively debugging the issues with our Jenkins pipelines, so these changes are for test purposes only. (I marked these commits as "DO NOT USE".)
</blockquote></details>

Done.
___
*[python-simple/Makefile, line 117 at r9](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-Lu-3rrI1MrjSNXA3rEV:-Lu4WicrEsILoEoakl45:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/a51f3f54b87ff4f813c62336720be07119c0dcd4/python-simple/Makefile#L117)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I should have mentioned not to review this PR yet. I am actively debugging the issues with our Jenkins pipelines, so these changes are for test purposes only. (I marked these commits as "DO NOT USE".)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-11-19 21:50 UTC, donporter submitted a review, later dismissed
> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-11-25 22:03 UTC, mkow requested changes
> Reviewed 13 of 19 files at r7, 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 14 unresolved discussions (waiting on @chiache)

___
*[python-scipy-insecure/Makefile, line 59 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZQ8Qq0cR7MYDHTez9:-LuZQ8Qq0cR7MYDHTezA:bwiu23q) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/Makefile#L59)):*
> ```Makefile
> 	  "sgx.trusted_files.ctypes = file:$(PYTHONHOME)/lib-dynload/_ctypes.cpython-$(PYTHONSHORTVERSION)m-x86_64-linux-gnu.so\\\\n" \
> 	  "sgx.trusted_files.ssl = file:$(PYTHONHOME)/lib-dynload/_ssl.cpython-$(PYTHONSHORTVERSION)m-x86_64-linux-gnu.so\\\\n" \
> 	  "sgx.trusted_files.lalack_lite = file:$(PYTHONDISTHOME)/numpy/linalg/lapack_lite.cpython-$(PYTHONSHORTVERSION)m-x86_64-linux-gnu.so\\\\n" \
> ```

lalack? ;)
___
*[python-scipy-insecure/Makefile, line 113 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZSg4WA6usXOaCM6Qv:-LuZSg4X9AEkKL3pIAjo:b-i74n81) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/Makefile#L113)):*
> ```Makefile
> 
> .PHONY: regression
> regression: all
> ```

I think we decided to use `check` instead of `regression`?
___
*[python-simple/python.manifest.template, line 243 at r7](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LtbOET96-MHQ_oIcy_r:-LuZYVCu285xOd_71j2K:b-3stmd2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7c43fa23563643a3d306c6a154341a42a197b844/python-simple/python.manifest.template#L243)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Do I hate Python? Yes, I do hate Python. 121 scripts just to run a simple web server.
</blockquote></details>

Sounds like you haven't seen the JS ecosystem yet :)
___
*[python-simple/python.manifest.template, line 4 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZXNGvCFub-blugO7f:-LuZXNGvCFub-blugO7g:b-k9y1ye) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/python.manifest.template#L4)):*
> ```
> #
> # This manifest was prepared and tested on Ubuntu 16.04/18.04 and tested with
> # Python v3.5 and v3.6.
> ```

For Python usually people don't prefix version numbers with `v`.
___
*[python-simple/README.md, line 16 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZZiNHAsgY2erpxpXT:-LuZZiNI88aRAApeuYj6:bsqwi0d) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/README.md#L16)):*
> ```Markdown
> ## Building for SGX
> 
> Run `make SGX=1` (non-debug) or `make SGX=1 DEBUG=1` (debug) in the directory.
> ```

I get:

```
Exception: Cannot resolve file:/lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2 or the file does not exist.
```

When trying to build with SGX. Does it require anything special to be installed?
___
*[python-scipy-insecure/python.manifest.template, line 63 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZT8Qn8HcSqR9fk1MX:-LuZT8Qn8HcSqR9fk1MY:bvvn5f6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/python.manifest.template#L63)):*
> ```
> fs.mount.etc.uri = file:/etc
> 
> # Grahene general options
> ```

`Grahene` -> `Graphene`
___
*[python-scipy-insecure/README.md, line 19 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZRgG_Dn0tAH-GroHF:-LuZRgG_Dn0tAH-GroHG:b78lku7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/README.md#L19)):*
> ```Markdown
> command to install the required Python packages (Ubuntu-specific):
> 
>     sudo apt-get install -f python3-numpy python3-scipy
> ```

Why is this `-f` here?
___
*[python-scipy-insecure/scripts/test-numpy.py, line 11 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZUclp91qZiLt4JZDc:-LuZUclq-Zh-SOgBOumI:b8px3yd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-numpy.py#L11)):*
> ```Python
>     print('FAST BLAS')
> except ImportError:
>     print('slow blas')
> ```

Please clean up those log messages, I was a bit confused what do they mean when I saw them when running the test.
___
*[python-scipy-insecure/scripts/test-numpy.py, line 13 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZUnwq377Ua_7IGdFf:-LuZUnwq377Ua_7IGdFg:b-qv8gk9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-numpy.py#L13)):*
> ```Python
>     print('slow blas')
> 
> print("version: " + numpy.__version__)
> ```

`version` -> `numpy version`
___
*[python-scipy-insecure/scripts/test-numpy.py, line 21 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZUvQF6Schj8IAZTDl:-LuZUvQF6Schj8IAZTDm:b-fizc17) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-numpy.py#L21)):*
> ```Python
> 
> t = timeit.Timer("numpy.dot(x, x.T)", setup=setup)
> print("dot: " + str(t.timeit(count)/count) + " sec")
> ```

`dot` -> `numpy.dot`
___
*[python-scipy-insecure/scripts/test-scipy.py, line 12 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZVJn69a8x4i-DgtS2:-LuZVJn7544praa_lkxq:b-mcix9z) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-scipy.py#L12)):*
> ```Python
> 
> t = timeit.Timer("linalg.cholesky(z, lower=True)", setup=setup)
> print("cholesky: " + str(t.timeit(count)/count) + "sec")
> ```

`cholesky` -> `linalg.cholesky`
___
*[python-scipy-insecure/scripts/test-scipy.py, line 15 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZVNwr99S57kwLG-KZ:-LuZVNwr99S57kwLG-K_:b-lqbxn9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-scipy.py#L15)):*
> ```Python
> 
> t = timeit.Timer("linalg.svd(z)", setup=setup)
> print("svd: " + str(t.timeit(count)/count) + "sec")
> ```

`svd` -> `linalg.svd`
___
*[python-simple/Makefile, line 127 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZWIGWCXp5HucBviPx:-LuZWIGX4un99JnE3Fwq:b-y5c1ic) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/Makefile#L127)):*
> ```Makefile
> 
> .PHONY: regression
> regression: all
> ```

ditto (target name)
___
*[python-simple/Makefile, line 129 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZWcwA8rC17bmUga89:-LuZWcwA8rC17bmUga8A:bbapcq7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/Makefile#L129)):*
> ```Makefile
> regression: all
> 	./run-tests.sh > OUTPUT_TEST 2> /dev/null
> 	@sleep 5  # to make sure Python processes finish under Graphene-SGX
> ```

Shouldn't waiting for this be `run-tests.sh` responsibility?
___
*[python-simple/scripts/benchrun.py, line 100 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZ_BYL2rMajmqMGqMr:-LuZ_BYM0FUAVkLIN5Ec:b-ak3vrj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/scripts/benchrun.py#L100)):*
> ```Python
>             ts += " (x faster than " + (str(self.reference_value)) + ")"
>         print("  " + "   ".join([str(r).ljust(colwidth) for r in self.pnames + [ts]]))
>         print("-"*79)
> ```

spaces around `*`


<!-- Sent from Reviewable.io -->

2019-11-26 01:52 UTC, dimakuv submitted a review, later dismissed
> Reviewed 10 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 14 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[python-scipy-insecure/Makefile, line 59 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZQ8Qq0cR7MYDHTez9:-Lu_H2Zk5bP-XC1RT7zN:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/Makefile#L59)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

lalack? ;)
</blockquote></details>

Done
___
*[python-scipy-insecure/Makefile, line 113 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZSg4WA6usXOaCM6Qv:-Lu_H5-CDf97TVy2oTq7:b-5jizkw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/Makefile#L113)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think we decided to use `check` instead of `regression`?
</blockquote></details>

Done. There is a lot of inconsistency in our examples. I moved to `check` for Python. We'll need to have a unifying PR to change everything to `check`.
___
*[python-simple/python.manifest.template, line 4 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZXNGvCFub-blugO7f:-Lu_J8hqASrx_S7SDtI1:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/python.manifest.template#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

For Python usually people don't prefix version numbers with `v`.
</blockquote></details>

Done
___
*[python-simple/README.md, line 16 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZZiNHAsgY2erpxpXT:-Lu_G267EHLvAzNw15gF:b-3ccfhy) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/README.md#L16)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I get:

```
Exception: Cannot resolve file:/lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2 or the file does not exist.
```

When trying to build with SGX. Does it require anything special to be installed?
</blockquote></details>

Done. `sudo apt install libnss-mdns`. I mention it in the README now.
___
*[python-scipy-insecure/python.manifest.template, line 63 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZT8Qn8HcSqR9fk1MX:-Lu_Ha_S2zKWnYiptnZV:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/python.manifest.template#L63)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Grahene` -> `Graphene`
</blockquote></details>

Done
___
*[python-scipy-insecure/README.md, line 19 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZRgG_Dn0tAH-GroHF:-Lu_HrNd5uow9knlyuFU:b-4l90h3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/README.md#L19)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why is this `-f` here?
</blockquote></details>

Done. Removed it. I guess Chia-Che wanted a `--fix-broken` feature of apt-get. But it's not really our problem if user has broken packages.
___
*[python-scipy-insecure/scripts/test-numpy.py, line 11 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZUclp91qZiLt4JZDc:-Lu_ITno2G5cXifueR9F:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-numpy.py#L11)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please clean up those log messages, I was a bit confused what do they mean when I saw them when running the test.
</blockquote></details>

Done
___
*[python-scipy-insecure/scripts/test-numpy.py, line 13 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZUnwq377Ua_7IGdFf:-Lu_IUMk3P7xBFLETSmH:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-numpy.py#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`version` -> `numpy version`
</blockquote></details>

Done
___
*[python-scipy-insecure/scripts/test-numpy.py, line 21 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZUvQF6Schj8IAZTDl:-Lu_I_V_CgZk15eSwUMQ:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-numpy.py#L21)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`dot` -> `numpy.dot`
</blockquote></details>

Done
___
*[python-scipy-insecure/scripts/test-scipy.py, line 12 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZVJn69a8x4i-DgtS2:-Lu_Idm60T6wm4ZZZcfw:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-scipy.py#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`cholesky` -> `linalg.cholesky`
</blockquote></details>

Done
___
*[python-scipy-insecure/scripts/test-scipy.py, line 15 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZVNwr99S57kwLG-KZ:-Lu_IgZfEdWl8veBmS8z:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-scipy-insecure/scripts/test-scipy.py#L15)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`svd` -> `linalg.svd`
</blockquote></details>

Done
___
*[python-simple/Makefile, line 127 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZWIGWCXp5HucBviPx:-Lu_Ii7BCySGIbNW7NSr:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/Makefile#L127)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (target name)
</blockquote></details>

Done
___
*[python-simple/Makefile, line 129 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZWcwA8rC17bmUga89:-Lu_IunfDqifJYz48xW0:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/Makefile#L129)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't waiting for this be `run-tests.sh` responsibility?
</blockquote></details>

Done
___
*[python-simple/scripts/benchrun.py, line 100 at r10](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LuZ_BYL2rMajmqMGqMr:-Lu_JgyYCWe69JoYGhtS:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/463752d90dcf15a4e47533b5b6609b6ae63a40b4/python-simple/scripts/benchrun.py#L100)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

spaces around `*`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2019-11-26 11:57 UTC, mkow requested changes
> Reviewed 10 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @chiache)

___
*[python-simple/run-tests.sh, line 30 at r11](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LubZKVn7S7gJSe4dy1x:-LubZKVn7S7gJSe4dy1y:b-9td069) ([raw file](https://github.com/oscarlab/graphene-tests/blob/72bfea621158d34aad75e1855da8c5dfd198fb7b/python-simple/run-tests.sh#L30)):*
> ```Shell
> rm -f OUTPUT1 OUTPUT2 server.PID
> 
> sleep 5  # to make sure Python processes finish under Graphene-SGX
> ```

Actually, why is this needed in the first place?


<!-- Sent from Reviewable.io -->

2019-11-26 18:29 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[python-simple/run-tests.sh, line 30 at r11](https://reviewable.io/reviews/oscarlab/graphene-tests/29#-LubZKVn7S7gJSe4dy1x:-LucyAcO6WuJseGcdvjh:b-ditnz4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/72bfea621158d34aad75e1855da8c5dfd198fb7b/python-simple/run-tests.sh#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Actually, why is this needed in the first place?
</blockquote></details>

Done. You are right, this was not needed. Removed it.


<!-- Sent from Reviewable.io -->

2019-11-26 18:56 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-11-27 21:52 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-11-27 23:07 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/29)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-11-27 23:15 UTC, merged