Rewrite LMBench 2.5 example
oscarlab/graphene-tests pull request #33
Opened 2019-08-27 19:32 UTC by chiache

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene-tests/33)

2019-08-30 18:31 UTC, HW42 submitted a review, later dismissed
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYdC36DmAjNwEIQ5sk:-LnYdC36DmAjNwEIQ5sl:b-ovj0lh) (no related file):*
Please download the lmbench source instead of including it.

---
___
*[lmbench/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYaNYADYrzbs7cJNT7:-LnYaNYADYrzbs7cJNT8:b-ldkhfn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L6)):*
> ```Makefile
> # - make DEBUG=1
> # - make SGX=1
> # - make SGX=1 DEBUG=1
> ```

clarify
___
*[lmbench/Makefile, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYa_UZ56awS1hpRw9B:-LnYa_UZ56awS1hpRw9C:bjdqao8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L12)):*
> ```Makefile
> # Constants
> 
> # Source code and install directory of LMBench
> ```

redundant
___
*[lmbench/Makefile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYb6l8CU1U6D0ZXMCd:-LnYb6l8CU1U6D0ZXMCe:b-75ywm7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L42)):*
> ```Makefile
> 
> export CC
> export CFLAGS
> ```

why is this needed?
___
*[lmbench/Makefile, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYbAnK0VdSdCuP0pBa:-LnYbAnLCjDnd91P7DAb:bdpjc49) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L44)):*
> ```Makefile
> export CFLAGS
> 
> # Building LMBench 2.5
> ```

drop version or maybe complete comment
___
*[lmbench/Makefile, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYbEdA-9ek3gKjXUHq:-LnYbEdB-m6uzihjF_cW:bk0ct0e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L46)):*
> ```Makefile
> # Building LMBench 2.5
> 
> $(INSTALLDIR):
> ```

don't use directory as target
___
*[lmbench/Makefile, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYcVbRBWIPnRlh7v46:-LnYcVbRBWIPnRlh7v47:b-qr9ddw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L68)):*
> ```Makefile
> 
> .PHONY: sgx
> sgx: $(INSTALLDIR) $(INSTALLDIR)/sh.manifest.sgx $(INSTALLDIR)/hello.manifest.sgx
> ```

Could you please do this in make instead of using a phony target and implementing it in shell.
___
*[lmbench/Makefile, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYmMI265--EDESPrx5:-LnYmMI32zilMI94B-5z:b37h87g) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L75)):*
> ```Makefile
> 				-libpal $(GRAPHENEDIR_FROM_INSTALLDIR)/Runtime/libpal-Linux-SGX.so \
> 				-key $(GRAPHENEDIR_FROM_INSTALLDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem \
> 				-manifest manifest -output $$f.manifest.sgx && \
> ```

Did you forget to push something. `-exec` is missing here and therefore non of the test run (enclave init fails because of bad measurement).
___
*[lmbench/Makefile, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYmlJHEQhziLOdYEph:-LnYmlJHEQhziLOdYEpi:b-aikyhy) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L81)):*
> ```Makefile
> 	done
> 
> $(INSTALLDIR)/sh.manifest.sgx $(INSTALLDIR)/hello.manifest.sgx: %.sgx: %
> ```

Please explain somewhere why `hello` is special.
___
*[lmbench/Makefile, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYe2dZ87fDo2v2x0aP:-LnYe2dZ87fDo2v2x0aQ:b-rw5hiu) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L94)):*
> ```Makefile
> # - make run-native:   run the whole test suite natively (with configuration)
> # - make run-graphene: run the whole test suite under Graphene (with configuration)
> # - make test:         run LMBench for CI (without configuration)
> ```

"configuration" -> "configuration prompt"


<!-- Sent from Reviewable.io -->

2019-08-30 19:22 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @HW42)

___
*[lmbench/Makefile, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYmMI265--EDESPrx5:-LnYxzptAJpkLM1zKDYn:b-fk0hkd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L75)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Did you forget to push something. `-exec` is missing here and therefore non of the test run (enclave init fails because of bad measurement).
</blockquote></details>

I don't see an enclave init fail, but for me after `[SGX=1] make run-graphene` it just sits there and does seemingly nothing.
```
...
The bigger the range, the more accurate the results, but larger sizes
take somewhat longer to run the benchmark.

MB [default 1024] 
```
___
*[lmbench/Makefile, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYwcnwAIhLKXg8vEHT:-LnYwcnx58Xj6_JA3NqY:bgmj3t3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L116)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(MAKE) -C $(LMBENCHDIR) clean
> ```

What about a distclean target for consistency?


<!-- Sent from Reviewable.io -->

2019-09-05 20:20 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 16 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, and @thomasknauth)

___
*[lmbench/Makefile, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-Lo22pVX5UZ0vtXWxWDk:-Lo22pVX5UZ0vtXWxWDl:b-14yk8n) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L25)):*
> ```Makefile
> else
> GRAPHENEDIR_FROM_INSTALLDIR = ../../../$(GRAPHENEDIR)
> endif
> ```

What is the reason for this whole `GRAPHENEDIR_FROM_INSTALLDIR`? I don't see a need for it.
___
*[lmbench/Makefile, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYwcnwAIhLKXg8vEHT:-Lo23NIzCA85Vj-wYsSJ:b32v57) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L116)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

What about a distclean target for consistency?
</blockquote></details>

+1
___
*[lmbench/manifest.template, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-Lo23UdV1VVK501oThZA:-Lo23UdV1VVK501oThZB:bghxr81) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/manifest.template#L37)):*
> ```
> fs.mount.tmp.uri = file:/tmp
> 
> # Mount /var/tmp
> ```

Why do we need this?
___
*[lmbench/README.md, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-Lo245GM5fMIhmhSlMy_:-Lo245GM5fMIhmhSlMya:bhg2724) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/README.md#L27)):*
> ```Markdown
> or
> 
> cd lmbench-2.5/scripts && env OS=linux ./results
> ```

What's the point of showing this way? A curious user will just look into the makefile. I suggest to only keep `make run-native` here.
___
*[lmbench/README.md, line 47 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-Lo24HGC2UfFa05MnkV4:-Lo24HGC2UfFa05MnkV5:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/README.md#L47)):*
> ```Markdown
> or
> 
> cd lmbench-2.5/scripts && env LOADER=./pal_loader OS=linux RESULTS=results/graphene ./results
> ```

ditto
___
*[lmbench/README.md, line 66 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-Lo24MCz7UjWn5xIcj71:-Lo24MCz7UjWn5xIcj72:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/README.md#L66)):*
> ```Markdown
> or
> 
> cd lmbench-2.5/scripts && env SGX=1 LOADER=./pal_loader OS=linux RESULTS=results/graphene ./results
> ```

ditto


<!-- Sent from Reviewable.io -->

2019-09-09 00:25 UTC, mkow requested changes
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, and @thomasknauth)

___
*[lmbench/hello.manifest.template, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LoIL-OQAyWuIm0fdRhd:-LoIL-ORDw2QO7uL3YA7:b2o4e2v) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/hello.manifest.template#L27)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave. For SGX v1, the enclave size
> # must be specified during signing. If R needs more virtual memory than the
> ```

`R` -> `the application`
___
*[lmbench/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LoILo6tDNUsvY2a6A3H:-LoILo6tDNUsvY2a6A3I:bn35xq9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L1)):*
> ```Makefile
> # Build the manifest for LMBench 2.5:
> ```

I'd drop the version number here. Doesn't help and will quickly get out of sync with the real version.
___
*[lmbench/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LoIOZDg7SJ5e2omi4wi:-LoIOZDg7SJ5e2omi4wj:bhvkzsc) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/README.md#L1)):*
> ```Markdown
> # LMBench 2.5 example
> ```

Drop the version number
___
*[lmbench/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LoIOaag217PvAns9_GC:-LoIOaag217PvAns9_GD:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/README.md#L3)):*
> ```Markdown
> # LMBench 2.5 example
> 
> This directory contains an example for running LMBench 2.5 in Graphene, including
> ```

ditto
___
*[lmbench/sh.manifest.template, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LoIPCGY0WFKlRiQYhYC:-LoIPCGY0WFKlRiQYhYD:b2o4e2v) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/sh.manifest.template#L27)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave. For SGX v1, the enclave size
> # must be specified during signing. If R needs more virtual memory than the
> ```

`R` -> `the application`
___
*[lmbench/lmbench-2.5/lmbench-regression, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LoILdZc2OsZntSxpawA:-LoILdZc2OsZntSxpawB:b-1wn87o) ([raw file](https://github.com/oscarlab/graphene-tests/blob/937b59d5e998ac8ab9e3addb72f5f4a09efda659/lmbench/lmbench-2.5/lmbench-regression#L1)):*
> ```
> #!/bin/bash
> ```

While we are moving this, could you add `.sh` extension to it?


<!-- Sent from Reviewable.io -->

2019-11-19 18:55 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: 2 of 7 files reviewed, 22 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @HW42, @mkow, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYdC36DmAjNwEIQ5sk:-LntJiR34GzagJmo_6Ex:b-gigbrs) (no related file):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Please download the lmbench source instead of including it.
</blockquote></details>

We used a modified version of lmbench-2.5. Our modified source code is originally hosted in https://github.com/oscarlab/lmbench-2.5 and added as a submodule.

---
___
*[lmbench/hello.manifest.template, line 27 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LoIL-OQAyWuIm0fdRhd:-Lu3nhuy-N2cgGWOd3pC:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/hello.manifest.template#L27)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`R` -> `the application`
</blockquote></details>

Done.
___
*[lmbench/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LoILo6tDNUsvY2a6A3H:-Lu3nyJ-AVtFH7DbFkzs:b-ioumd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd drop the version number here. Doesn't help and will quickly get out of sync with the real version.
</blockquote></details>

LMBench 2.5 is the last version of LMBench 2, and they changed the design of LMBench 3 drastically. The current configuration will not work with LMBench 3+.

I've added an explanation in the README.
___
*[lmbench/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYaNYADYrzbs7cJNT7:-Lu3pkp90lEhNFyGDSIB:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L6)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

clarify
</blockquote></details>

Done.
___
*[lmbench/Makefile, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYa_UZ56awS1hpRw9B:-Lu3potg99MVMYblDCA1:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L12)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.
___
*[lmbench/Makefile, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-Lo22pVX5UZ0vtXWxWDk:-Lu3pw-H1t6IFhXv-U8P:bmyow2b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L25)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is the reason for this whole `GRAPHENEDIR_FROM_INSTALLDIR`? I don't see a need for it.
</blockquote></details>

To handle the relative path. The LMBench binaries will be installed in `lmbench-2.5/bin/linux`. If `GRAPHENEDIR` is a relative path to the current lmbench directory, we need to add prefixes to the path .
___
*[lmbench/Makefile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYb6l8CU1U6D0ZXMCd:-Lu3qMZH5zuVZ--6PO6O:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L42)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

why is this needed?
</blockquote></details>

Done.
___
*[lmbench/Makefile, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYbAnK0VdSdCuP0pBa:-Lu3qNf4-qI2Dvl60rPl:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L44)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

drop version or maybe complete comment
</blockquote></details>

Done.
___
*[lmbench/Makefile, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYbEdA-9ek3gKjXUHq:-Lu3qngQ4jTYqrNCmxlS:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L46)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

don't use directory as target
</blockquote></details>

Done.
___
*[lmbench/Makefile, line 68 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYcVbRBWIPnRlh7v46:-Lu3yhZU2wvVvtZ0-1Ik:b-q4y76q) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L68)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Could you please do this in make instead of using a phony target and implementing it in shell.
</blockquote></details>

In order to do so, I would need to list all the manifests for the LMBench tests as targets. There is no simple way of listing all these test binaries unless using a shell command with `find`.
___
*[lmbench/Makefile, line 75 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYmMI265--EDESPrx5:-Lu3y2QI-Frjv1t03Uqp:b-edyo86) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L75)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

I don't see an enclave init fail, but for me after `[SGX=1] make run-graphene` it just sits there and does seemingly nothing.
```
...
The bigger the range, the more accurate the results, but larger sizes
take somewhat longer to run the benchmark.

MB [default 1024] 
```
</blockquote></details>

You are right. I added the `-exec` parameter.

The stall that @thomasknauth sees is the configuration prompt of LMBench (which is normal).
___
*[lmbench/Makefile, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYmlJHEQhziLOdYEph:-Lu3yX109Qz9HKPEBhlV:bt5lr5w) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L81)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Please explain somewhere why `hello` is special.
</blockquote></details>

For `hello`, we used a slightly different template (simpler and does not do any `fork`/`exec`).
___
*[lmbench/Makefile, line 94 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYe2dZ87fDo2v2x0aP:-Lu3sRrCEHJJ_Gl_8RDZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L94)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

"configuration" -> "configuration prompt"
</blockquote></details>

Done.
___
*[lmbench/Makefile, line 116 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYwcnwAIhLKXg8vEHT:-Lu407P_2wL2J7uRFIG-:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L116)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[lmbench/manifest.template, line 37 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-Lo23UdV1VVK501oThZA:-Lu3rFjy2FjOanYQlLtN:b-5j8e8e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/manifest.template#L37)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

Some LMBench tests use `/var/tmp` as an alternative tmp directory.
___
*[lmbench/README.md, line 1  [...]

2019-11-20 23:50 UTC, dimakuv requested changes
> Reviewed 2 of 7 files at r1, 5 of 5 files at r2.
> Dismissed @HW42 from 10 discussions.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @chiache, @mkow, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYdC36DmAjNwEIQ5sk:-LuA8o5l3OsB2znVRQak:befzi3w) (no related file):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

We used a modified version of lmbench-2.5. Our modified source code is originally hosted in https://github.com/oscarlab/lmbench-2.5 and added as a submodule.
</blockquote></details>

But it is not a submodule in our graphene-tests repo... It is a literal subdirectory will all the files: https://github.com/oscarlab/graphene-tests/tree/master/lmbench/lmbench-2.5. I guess what you're saying is that there is no sense in downloading LMBench, since we support only our own specific LMBench version.

I'm fine with that, but could you give some historical context? Why did you have to modify LMBench v2.5 for Graphene?

---
___
*[lmbench/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYaNYADYrzbs7cJNT7:-LuA9_Ts4lB3Y-P3LKgX:bnvg12e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L6)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks like you forgot to remove the previous version, and now you have duplicated `make DEBUG=1 ...`, etc.
___
*[lmbench/Makefile, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYa_UZ56awS1hpRw9B:-LuA9hY1AiV4xF_rf0he:b-625pzv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L12)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done. I guess HW42 wanted this useless comment to be removed.
___
*[lmbench/README.md, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACJ0G8m_VSvJUsCVD:-LuACJ0H8J3DobZ_lfmp:btzl8o7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L22)):*
> ```Markdown
> ## Running natively
> 
> To run the whole test suite natively, use one of the following commands:
> ```

`use the following command`
___
*[lmbench/README.md, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACL236pF5eRzIKQeh:-LuACL236pF5eRzIKQei:btzl8o7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L38)):*
> ```Markdown
> ## Running with Graphene
> 
> To run the whole test suite under Graphene, use one of the following commands:
> ```

`use the following command`
___
*[lmbench/README.md, line 53 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACQAC3V3H2eOAggah:-LuACQAC3V3H2eOAggai:btzl8o7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L53)):*
> ```Markdown
> ## Running with Graphene-SGX
> 
> To run the whole test suite, use one of the following commands:
> ```

`use the following command`


<!-- Sent from Reviewable.io -->

2019-11-25 22:36 UTC, mkow requested changes
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @chiache, @dimakuv, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYdC36DmAjNwEIQ5sk:-LuZgBQdD8IgkKGMYqO0:b-4kmzof) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

But it is not a submodule in our graphene-tests repo... It is a literal subdirectory will all the files: https://github.com/oscarlab/graphene-tests/tree/master/lmbench/lmbench-2.5. I guess what you're saying is that there is no sense in downloading LMBench, since we support only our own specific LMBench version.

I'm fine with that, but could you give some historical context? Why did you have to modify LMBench v2.5 for Graphene?
</blockquote></details>

I'd definitely prefer to drop our custom changes if they are not absolutely required.

---
___
*[lmbench/Makefile, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYa_UZ56awS1hpRw9B:-LuZgcdN7iSIBVe5KPOu:bs34av7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not done. I guess HW42 wanted this useless comment to be removed.
</blockquote></details>

Seems to be done now?
___
*[lmbench/Makefile, line 114 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuZgzD27TArcFWkJmxv:-LuZgzD27TArcFWkJmxw:bnp4z3o) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/Makefile#L114)):*
> ```Makefile
> 	ln -s $(GRAPHENEDIR_FROM_INSTALLDIR)/Runtime/pal_loader $@
> 
> .PHONY: clean distclean
> ```

Please move this to a separate `.PHONY` right above the `distclean` target, as we do in all other places.


<!-- Sent from Reviewable.io -->

2019-12-03 12:27 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: 4 of 176 files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYdC36DmAjNwEIQ5sk:-LvAf9Sr1fmiamPvF2i7:bp2i0lj) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd definitely prefer to drop our custom changes if they are not absolutely required.
</blockquote></details>

I removed the custom version of LMBench from our repository and instead just download it from: https://sourceforge.net/projects/lmbench/

Giving some historical context, when writing our paper, we made a lot of efforts to improve lmbench, including adding new tests (especially fork-related tests) and calculating more precise statistics (Mean, Median, CI width). These changes are absolutely required.

For our future research, we will just manually download the code from https://github.com/oscarlab/lmbench-2.5

---
___
*[lmbench/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYaNYADYrzbs7cJNT7:-LvAfPyA6CSPwufBGn2_:b4g8dqb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L6)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It looks like you forgot to remove the previous version, and now you have duplicated `make DEBUG=1 ...`, etc.
</blockquote></details>

Done. Thank you for pointing this one.
___
*[lmbench/Makefile, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYa_UZ56awS1hpRw9B:-LvAfSUy0T3LRDVp0wx_:bbsuufh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/c8edb58b4b5ba6d3ae4d08a1865843e3a5bc9004/lmbench/Makefile#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Seems to be done now?
</blockquote></details>

This is done. HW42 asked for removing the comment "# Source code and install directory of LMBench".  "Constants" seems more explanatory to me.
___
*[lmbench/Makefile, line 114 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuZgzD27TArcFWkJmxv:-LvAga559mRjQmdq0gQH:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/Makefile#L114)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please move this to a separate `.PHONY` right above the `distclean` target, as we do in all other places.
</blockquote></details>

Done.
___
*[lmbench/README.md, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACJ0G8m_VSvJUsCVD:-LvAgIMm4L81z7l7bqRW:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L22)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`use the following command`
</blockquote></details>

Done.
___
*[lmbench/README.md, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACL236pF5eRzIKQeh:-LvAgKm5EvsBZEVCDSMA:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L38)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`use the following command`
</blockquote></details>

Done.
___
*[lmbench/README.md, line 53 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACQAC3V3H2eOAggah:-LvAgLDk1VlOpLhot1lg:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L53)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`use the following command`
</blockquote></details>

Done.
___
*[lmbench/lmbench-test-ci.sh, line 252 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LvAgcLG0bKXDZyAWOWz:-LvAgcLG0bKXDZyAWOX-:bv9i1qp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/lmbench-test-ci.sh#L252)):*
> ```Shell
> ## DEP 6/19/18: Temporarily remove dforkexec from the unit tests
> #			"lat_proc dforkexec"
> ## DEP 6/16/18: Temporarily remove shell from the unit tests
> ```

Removing these (commented-out) tests as they are not from the original LMBench source.


<!-- Sent from Reviewable.io -->

2019-12-03 14:51 UTC, mkow requested changes
> Reviewed 172 of 172 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @chiache, @dimakuv, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LnYdC36DmAjNwEIQ5sk:-LvBEGTaBrLbuUujXFZR:b-8jd8zd) (no related file):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

I removed the custom version of LMBench from our repository and instead just download it from: https://sourceforge.net/projects/lmbench/

Giving some historical context, when writing our paper, we made a lot of efforts to improve lmbench, including adding new tests (especially fork-related tests) and calculating more precise statistics (Mean, Median, CI width). These changes are absolutely required.

For our future research, we will just manually download the code from https://github.com/oscarlab/lmbench-2.5
</blockquote></details>

Sounds good. We may re-add those patches once we add performance measurements to our CI.

---
___
*[lmbench/Makefile, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LvBB6sECq7w0skq__Gs:-LvBB6sF4E44Tr1H8INH:bckjayt) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1432fb68129db8262969f199853d36c71dd84f37/lmbench/Makefile#L14)):*
> ```Makefile
> 
> LMBENCHURL = https://sourceforge.net/projects/lmbench/files/lmbench/2.5/lmbench-2.5.tgz/download
> LMBENCHCHECKSUM = e7431530a4cf4c44b5068e23454f95765dc0b51e7d98bc2bd70451b17d505bd9
> ```

checksum -> hash
___
*[lmbench/Makefile, line 51 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LvBBhm01ZFFGn-65VHA:-LvBBhm01ZFFGn-65VHB:bckjayt) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1432fb68129db8262969f199853d36c71dd84f37/lmbench/Makefile#L51)):*
> ```Makefile
> $(LMBENCHDIR)/src/Makefile: $(LMBENCHDIR).tgz
> 	[ "`sha256sum $<`" = "$(LMBENCHCHECKSUM)  $<" ] || \
> 		(echo "*** $< has a wrong checksum ***"; exit 255)
> ```

checksum -> hash
___
*[lmbench/README.md, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACJ0G8m_VSvJUsCVD:-LvBCOUmE4Z4h4JVetnK:b-9qg1u4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L22)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[lmbench/README.md, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACL236pF5eRzIKQeh:-LvBCcjB1K-0qQPYcbPo:b-9qg1u4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L38)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[lmbench/README.md, line 53 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACQAC3V3H2eOAggah:-LvBCef48nNCJWQAmEVO:b-9qg1u4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L53)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not done
___
*[lmbench/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LvBCZkA6Qc6KpO02TcX:-LvBCZkA6Qc6KpO02TcY:bpbb3q1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1432fb68129db8262969f199853d36c71dd84f37/lmbench/README.md#L12)):*
> ```Markdown
> This repository does not contain the source code of LMBench. Using the following
> building commands will automatically download the source code and unpack it into
> the current directory.
> ```

I think it actually unpacks it to a subdirectory ;)


<!-- Sent from Reviewable.io -->

2019-12-03 15:27 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab), "fixup! " found in commit messages' one-liners (waiting on @chiache, @dimakuv, @mkow, and @thomasknauth)

___
*[lmbench/Makefile, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LvBB6sECq7w0skq__Gs:-LvBMegf2P93mqbAV6PJ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1432fb68129db8262969f199853d36c71dd84f37/lmbench/Makefile#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

checksum -> hash
</blockquote></details>

Done.
___
*[lmbench/README.md, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACJ0G8m_VSvJUsCVD:-LvBMZW60BDyOURNabFB:b-l4s8c1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L22)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not done
</blockquote></details>

Thanks! I missed the "one of".
___
*[lmbench/README.md, line 38 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACL236pF5eRzIKQeh:-LvBMbXr4opwSH8hvs0v:bs4q9op) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not done
</blockquote></details>

Ditto.
___
*[lmbench/README.md, line 53 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LuACQAC3V3H2eOAggah:-LvBMcKh0d-5xPn99__r:bs4q9op) ([raw file](https://github.com/oscarlab/graphene-tests/blob/683d1c0078ee977c66b6ee8be9436eb2906b42de/lmbench/README.md#L53)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

not done
</blockquote></details>

Ditto.
___
*[lmbench/README.md, line 12 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/33#-LvBCZkA6Qc6KpO02TcX:-LvBMYmP9eGKRnDM_4Am:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1432fb68129db8262969f199853d36c71dd84f37/lmbench/README.md#L12)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I think it actually unpacks it to a subdirectory ;)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-03 15:30 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 7 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @chiache, @dimakuv, and @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-12-03 21:31 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 1 unresolved discussion, "fixup! " found in commit messages' one-liners (waiting on @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-12-03 21:54 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 1 unresolved discussion (waiting on @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-12-03 21:56 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: all files reviewed, 1 unresolved discussion (waiting on @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-12-03 22:46 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-12-03 22:50 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/33)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-12-03 23:41 UTC, merged