Rewrite Apache example
oscarlab/graphene-tests pull request #36
Opened 2019-08-28 05:57 UTC by chiache

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene-tests/36)

2019-08-30 17:32 UTC, HW42 requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYS8NZCcFGLu_eLQuc:-LnYS8NZCcFGLu_eLQud:bpx8kl8) (no related file):*
.gitignore needs cleanup

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYYpw-A6Lg1t4taMh8:-LnYYpw08FJZ5mjAOihE:b-s22x1f) (no related file):*
Does `benchmark-http.sh` work for you?

For me in the concurrency=256 run:
```
[...]
ab -k -n 10000 -c 256 http://127.0.0.1:8001/random/10K.1.html
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
apr_socket_recv: Connection reset by peer (104)
```

---
___
*[apache/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYMpfa-9IjXpWgvb6J:-LnYMpfa-9IjXpWgvb6K:b-ldkhfn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L6)):*
> ```Makefile
> # - make DEBUG=1
> # - make SGX=1
> # - make SGX=1 DEBUG=1
> ```

clarify
___
*[apache/Makefile, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYMvvnA0xZUheTROEZ:-LnYMvvnA0xZUheTROE_:bjdqao8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L18)):*
> ```Makefile
> INSTALL_DIR ?= install
> 
> # Source code directory and checksum of Apache
> ```

redundant
___
*[apache/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYU0db8w95jlInWrLR:-LnYU0dc-WMA9tY56Ecg:bptd97t) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L26)):*
> ```Makefile
> 	http://www-us.apache.org/dist/ \
> 	http://apache.cs.utah.edu/ \
> 	http://apache.mirror.anlx.net/
> ```

Please use https mirrors. Semi random selection from https://www.apache.org/mirrors/:
```
https://www-eu.apache.org/dist/
https://www-us.apache.org/dist/
https://ftp.fau.de/apache/httpd/
```
___
*[apache/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYUZyB4Jpfw4UuACzI:-LnYUZyB4Jpfw4UuACzJ:bla0oqa) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L26)):*
> ```Makefile
> 	http://www-us.apache.org/dist/ \
> 	http://apache.cs.utah.edu/ \
> 	http://apache.mirror.anlx.net/
> ```

We need to add https://archive.apache.org/dist/httpd/ since the mirrors only save a few recent versions.
___
*[apache/Makefile, line 28 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYN0b2BVH-6WkwNrmW:-LnYN0b2BVH-6WkwNrmX:b-kvyaf5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L28)):*
> ```Makefile
> 	http://apache.mirror.anlx.net/
> 
> # Host and port for testing the Apache server
> ```

Maybe better "Address and port on which Apache should listen."
___
*[apache/Makefile, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYNMIJ0VZkfsNHfcC5:-LnYNMIJ0VZkfsNHfcC6:bgt76ys) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L57)):*
> ```Makefile
> 
> # The commands for downloading and compiling the Apache source code, and
> # installing the binaries.
> ```

Since this comment refers not only to the directly following target please insert a blank line.

"The commands" -> "Make targets"

Or maybe just drop that comment.
___
*[apache/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYOPGoBmO6yYmIb94x:-LnYOPGpAPd37HuKg0g4:b-v4xq2t) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L58)):*
> ```Makefile
> # The commands for downloading and compiling the Apache source code, and
> # installing the binaries.
> $(INSTALL_DIR)/bin/httpd: $(HTTPD_SRC)
> ```

Using a directory as target is a bad idea.
___
*[apache/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYOWM904Zbjno4IPhM:-LnYOWM904Zbjno4IPhN:byr4ffv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L64)):*
> ```Makefile
> 	cd $(HTTPD_SRC) && $(MAKE) install
> 
> $(HTTPD_SRC): $(HTTPD_SRC).tar.gz
> ```

see above
___
*[apache/Makefile, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYNcy87XGbmPFQ1zK3:-LnYNcy87XGbmPFQ1zK4:brmwixo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L71)):*
> ```Makefile
> 		wget --timeout=10 $${MIRROR}httpd/$(HTTPD_SRC).tar.gz \
> 		&& break; \
> 	done
> ```

Please first download to temp file, then actually check the checksum and then rename to "real" name.
___
*[apache/Makefile, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYNo6d2rEwRyRZrw6o:-LnYNo6d2rEwRyRZrw6p:bqbed95) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L80)):*
> ```Makefile
> # The dependencies are generated from the ldd results.
> 
> # Skip the GLIBC libraries because they are already listed
> ```

explain why this is the case
___
*[apache/Makefile, line 111 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYPsAvBQet46ErOGWR:-LnYPsAw2p0p3UsqpKg_:b-rroy79) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L111)):*
> ```Makefile
> .INTERMEDIATE: httpd-trusted-libs
> httpd-trusted-libs: httpd-deps
> 	@HTTPD_LIBS="$(INSTALL_DIR)/bin/httpd `cat httpd-modules`" && \
> ```

Better add a explicit dependency on `httpd-modules`
___
*[apache/Makefile, line 149 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYQXpxBfLwzimgL1EB:-LnYQXpxBfLwzimgL1EC:b-n108a1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L149)):*
> ```Makefile
> # Apache configuration and test data
> #
> # The following changes are made in httpd.conf (copied as httpd-new.conf):
> ```

Please use a better name than `-new` (Maybe `-graphene` or `-patched`. `-new` sounds for my taste too much for the generate then replace patter like in:
```
some-command > x.new
more-stuff >> x.new
mv x.new x
```
___
*[apache/Makefile, line 261 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYZP8J8VviMlz5UCkp:-LnYZP8J8VviMlz5UCkq:b17i27d) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L261)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(RM) -f *.manifest *.manifest.sgx *.token *.sig pal_loader
> ```

`OUTPUT` and `result-*` are missing.
___
*[apache/README.md, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYROKz-Y41tMZTgNNE:-LnYROKz-Y41tMZTgNNF:bl16rg4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/README.md#L10)):*
> ```Markdown
> # Installing from the Apache source code
> 
> In this example, we build Apache from the source code instead use an existing
> ```

"instead of using", but better drop that part completely.
___
*[apache/README.md, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYRczy5uLk0uGy4969:-LnYRczy5uLk0uGy496A:b-gtmuuw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/README.md#L17)):*
> ```Markdown
> 
> After installing the pack [...]

2019-08-30 20:30 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnZBvyd5d6wUdajo3vZ:-LnZBvyeBejqbinNNSLW:bliqpxf) (no related file):*
Neither `make start-graphene-server SGX=1` nor `make start-graphene-multithreaded-server SGX=1` lead to a state where a subsequent wget actually succeeds.

For the former is see a bunch of

```
[     1] ---- return from shim_wait4(...) = 0
[     1] WARNING: shim_times not implemented
[     1] ---- shim_select(0,0x0,0x0,0x0,0xab7ab40) = 0
[     1] ---- shim_wait4(-1,0xab7ab2c,WNOHANG,0x0) ... wait4
```

Not sure if this is worrisome or not.

---


<!-- Sent from Reviewable.io -->

2019-08-30 20:50 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[apache/Makefile, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnZHmtE42mmud6Zwa4R:-LnZHmtF8WvAjNZNhfHM:b42mh0d) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L192)):*
> ```Makefile
> 	$(foreach n,1 2 3,100.$n.html)
> 
> TEST_DATA = $(addprefix $(RANDOM_DIR)/,$(random-data))
> ```

$(random-data) -> $(RANDOM_FILES)


<!-- Sent from Reviewable.io -->

2019-08-30 21:13 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 20 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnZBvyd5d6wUdajo3vZ:-LnZJLYo4CgUTu_B_5Iv:b4846s9) (no related file):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Neither `make start-graphene-server SGX=1` nor `make start-graphene-multithreaded-server SGX=1` lead to a state where a subsequent wget actually succeeds.

For the former is see a bunch of

```
[     1] ---- return from shim_wait4(...) = 0
[     1] WARNING: shim_times not implemented
[     1] ---- shim_select(0,0x0,0x0,0x0,0xab7ab40) = 0
[     1] ---- shim_wait4(-1,0xab7ab2c,WNOHANG,0x0) ... wait4
```

Not sure if this is worrisome or not.
</blockquote></details>

After fixing the $(RANDOM_FILE) problem, `make start-graphene-server SGX=1` actually does seem to work somewhat. Running ab against this, gives unusually high tail latencies for higher concurrency levels, e.g., -c 4 with longest request taking ~5 seconds. Sometimes ab reports close to 100% failed requests also.

`make start-graphene-multithreaded-server SGX=1` continues to create enclave after enclave though.

---


<!-- Sent from Reviewable.io -->

2019-09-02 09:45 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: 6 of 11 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYS8NZCcFGLu_eLQuc:-LnlCvk43fMDKVCMjmnx:b-896fix) (no related file):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

.gitignore needs cleanup
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYYpw-A6Lg1t4taMh8:-LnlCxgF5J6qj2dcNggM:b-buq7ct) (no related file):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Does `benchmark-http.sh` work for you?

For me in the concurrency=256 run:
```
[...]
ab -k -n 10000 -c 256 http://127.0.0.1:8001/random/10K.1.html
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
apr_socket_recv: Connection reset by peer (104)
```
</blockquote></details>

Gautham has reported the same problem when running the `ab` client on a different machine. On the same problem, I haven't encountered this problem.

I've also seen another problem. Almost all the HTTP requests have received a response of different length from the first one. This causes these requests to be marked as "failed", but some says this doesn't actually mean that they failed.

I will look into this issue a little more. But if I can't fix this problem with configuration, I will create another issue/PR for this.  

---
___
*[apache/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYMpfa-9IjXpWgvb6J:-LnlEMpc-UazvnXq3Det:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L6)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

clarify
</blockquote></details>

Done.
___
*[apache/Makefile, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYMvvnA0xZUheTROEZ:-LnlERi37GCY4YN15KAU:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L18)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.
___
*[apache/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYU0db8w95jlInWrLR:-LnlElau7NfYKHG3X3tm:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L26)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Please use https mirrors. Semi random selection from https://www.apache.org/mirrors/:
```
https://www-eu.apache.org/dist/
https://www-us.apache.org/dist/
https://ftp.fau.de/apache/httpd/
```
</blockquote></details>

Done.
___
*[apache/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYUZyB4Jpfw4UuACzI:-LnlEvbD13XPIGUySkMY:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L26)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

We need to add https://archive.apache.org/dist/httpd/ since the mirrors only save a few recent versions.
</blockquote></details>

Done.
___
*[apache/Makefile, line 57 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYNMIJ0VZkfsNHfcC5:-LnlFR0I3veeV5VvJJlU:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L57)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Since this comment refers not only to the directly following target please insert a blank line.

"The commands" -> "Make targets"

Or maybe just drop that comment.
</blockquote></details>

Done.
___
*[apache/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYOPGoBmO6yYmIb94x:-LnlGQ6XE0CE0kVQSblh:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L58)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Using a directory as target is a bad idea.
</blockquote></details>

Done.
___
*[apache/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYOWM904Zbjno4IPhM:-LnlGQkgBTShL1pSRbZQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L64)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

see above
</blockquote></details>

Done.
___
*[apache/Makefile, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYNcy87XGbmPFQ1zK3:-LnlGSZCD1zr1bCfDSdK:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L71)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Please first download to temp file, then actually check the checksum and then rename to "real" name.
</blockquote></details>

Done.
___
*[apache/Makefile, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYNo6d2rEwRyRZrw6o:-LnlMFNM-c3MIVqEWPJn:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L80)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

explain why this is the case
</blockquote></details>

Done.
___
*[apache/Makefile, line 111 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYPsAvBQet46ErOGWR:-LnlKgPQ4mvvQl1WQTNR:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L111)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Better add a explicit dependency on `httpd-modules`
</blockquote></details>

Done.
___
*[apache/Makefile, line 149 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYQXpxBfLwzimgL1EB:-LnlKXCx5LX509Dlb0V4:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L149)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Please use a better name than `-new` (Maybe `-graphene` or `-patched`. `-new` sounds for my taste too much for the generate then replace patter like in:
```
some-command > x.new
more-stuff >> x.new
mv x.new x
```
</blockquote></details>

Done.
___
*[apache/Makefile, line 192 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnZHmtE42mmud6Zwa4R:-LnlIx2K5NsN7DZ86Jte:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L192)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

$(random-data) -> $(RANDOM_FILES)
</blockquote></details>

Done.
___
*[apache/Makefile, line 261 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYZP8J8VviMlz5UCkp:-LnlJJ3Z2O9M9W_63L1N:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L261)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

`OUTPUT` and `result-*` are missing.
</blockquote></details>

Done.
___
*[apache/README.md, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYROKz-Y41tMZTgNNE:-LnlKt_n1rVPP0q1gf8O:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/README.md#L10)):*
<details><summary><i>Previousl [...]

2019-09-05 21:30 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, and @thomasknauth)

___
*[apache/httpd.manifest.template, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2GPN-96SEdnCFolr-:-Lo2GPN-96SEdnCFolr0:b-oammga) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L29)):*
> ```
> fs.mount.lib.uri = file:$(GRAPHENEDIR)/Runtime
> 
> # Host-level libraries (/lib/x86_64-linux-gnu) required by the Python executable
> ```

`Python`?
___
*[apache/httpd.manifest.template, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2GQwh7FbPnQULkKGg:-Lo2GQwh7FbPnQULkKGh:b-oammga) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L34)):*
> ```
> fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu
> 
> # Host-level directory (/usr) required by the Python executable
> ```

`Python`?
___
*[apache/httpd.manifest.template, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2ICZT-wNgWmDhAJO2:-Lo2ICZT-wNgWmDhAJO3:b-eqyviu) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L69)):*
> ```
> sgx.trusted_files.libutil = file:$(GRAPHENEDIR)/Runtime/libutil.so.1
> sgx.trusted_files.libpthread = file:$(GRAPHENEDIR)/Runtime/libpthread.so.0
> sgx.trusted_files.libz = file:/lib/x86_64-linux-gnu/libz.so.1
> ```

Not a Glibc library, must be in a separate list
___
*[apache/Makefile, line 123 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2Ixnk4TIF4vgVwxqG:-Lo2Ixnk4TIF4vgVwxqH:b-m04ow2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L123)):*
> ```Makefile
> # Apache manifests:
> #   For each dependency, generate a rule as follows:
> #       sgx.trusted_files.xxxx = file:xxxx
> ```

Why is this comment needed here? You generated these above, and I don't see a point in this 3-line comment.
___
*[apache/Makefile, line 266 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2K1Ye9qmy5ZV-Zi99:-Lo2K1Ye9qmy5ZV-Zi9A:b-tswk6b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L266)):*
> ```Makefile
> 	@echo "Listen on $(LISTEN_HOST):$(LISTEN_PORT)"
> 	$(PREFIX) ./pal_loader httpd.manifest -D FOREGROUND \
> 		-f conf/httpd-new.conf \
> ```

What is `httpd-new.conf`? Looks like you wanted `httpd-graphene.conf`


<!-- Sent from Reviewable.io -->

2019-09-09 14:19 UTC, mkow requested changes
> Reviewed 6 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 39 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @HW42)

___
*[apache/.gitignore, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoL2mdN55HdW1Lm7WlZ:-LoL2mdN55HdW1Lm7Wl_:b-pit0xv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/.gitignore#L3)):*
> ```ignore
> /httpd-*/*
> /*.tar.gz
> /install/*
> ```

Why "install", instead of "build"? We aren't installing it.
___
*[apache/httpd.manifest.template, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNqtVD6Zlh55hkXnY:-LoLNqtVD6Zlh55hkXnZ:byq3o82) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L13)):*
> ```
> loader.execname = httpd
> 
> # Graphene environment, including the path of the library OS and the debug
> ```

`of` -> `to`
___
*[apache/httpd.manifest.template, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLO-aW9in6PnhYORbE:-LoLO-aW9in6PnhYORbF:bxt80n2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L47)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave. For SGX v1, the enclave
> # size must be specified during signing. If Python needs more virtual memory
> ```

python?
___
*[apache/httpd.manifest.template, line 79 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLOBzX4qDerquFT6jp:-LoLOBzX4qDerquFT6jq:boe9yss) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L79)):*
> ```
> # SGX untrusted (allowed) files / directories
> sgx.allowed_files.htdocs = file:$(INSTALL_DIR)/htdocs
> sgx.allowed_files.conf = file:$(INSTALL_DIR)/conf
> ```

Shouldn't configuration be `trusted`?
___
*[apache/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoL48iF6ZhQxjbP1uPX:-LoL48iF6ZhQxjbP1uPY:b-jytjxm) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L1)):*
> ```Makefile
> # Build the manifest for Apache (HTTPD):
> ```

`HTTPD` -> `httpd`
___
*[apache/Makefile, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoL4j2RDD0md1UMx8ga:-LoL4j2S2dKMAU_xY_Hu:bf3r1jl) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L32)):*
> ```Makefile
> 
> # Number of the preforked workers in Apache
> PREFORK_WORKERS := 4
> ```

`:=` -> `=` (works the same in this case, so no reason to use `:=`)
___
*[apache/Makefile, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLIm2uEAyNqzrx2Bot:-LoLIm2v6VMNSeEJE2Lk:bqt9k5t) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L84)):*
> ```Makefile
> $(INSTALL_DIR)/conf/httpd.conf: $(INSTALL_DIR)
> 
> # Listing all the enabled modules in Apache, by Grep'ing httpd.conf
> ```

`Grep'ing` -> `greping`
___
*[apache/Makefile, line 230 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLK0E35xRAbpep1aiR:-LoLK0E35xRAbpep1aiS:b3zm53e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L230)):*
> ```Makefile
> .PHONY: clean-server
> clean-server:
> 	rm -f $(INSTALL_DIR)/logs/httpd-$(LISTEN_HOST)-$(LISTEN_PORT).pid
> ```

`rm -f` -> `$(RM)`
___
*[apache/README.md, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLKHZ9-ETji6GN7ufq:-LoLKHZ9-ETji6GN7ufr:b-vytvtz) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L3)):*
> ```Markdown
> # Apache example
> 
> This directory contains an example for running Apache (version 2.4.41)
> ```

Please drop the version number, it will get out of sync quickly.
___
*[apache/README.md, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLLYHS-LNBf-OKak_N:-LoLLYHS-LNBf-OKak_O:b-x311sq) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L32)):*
> ```Markdown
> ## Running Apache natively
> 
> First, start the Apache server. By default, the installed Apached server will
> ```

`Apached` -> `Apache`
___
*[apache/README.md, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLMzVQ-IScYLfL3TID:-LoLMzVQ-IScYLfL3TIE:b-x311sq) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L58)):*
> ```Markdown
> ## Running Apache in Graphene
> 
> First, start the Apache server. By default, the installed Apached server will
> ```

`Apached` -> `Apache`
___
*[apache/README.md, line 68 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLN91W1pss1MPjenXb:-LoLN91XEdpFwRwhtk_p:boqj5gp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L68)):*
> ```Markdown
>     make start-graphene-multithreaded-server
> 
> Because these commands will start the Apache server in the foreground, you will
> ```

Do we need to repeat everything here? Maybe just say that the rest of steps is same as in the native case?
___
*[apache/README.md, line 89 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNT520SK2LsvP6L88:-LoLNT5386K6v5p3Ka46:b-2a8z1w) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L89)):*
> ```Markdown
>     make SGX=1
> 
> Then, start the Apache server. By default, the installed Apached server will
> ```

ditto (`Apached`)
___
*[apache/README.md, line 99 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNZ8R-7tZCL1vb38r:-LoLNZ8R-7tZCL1vb38s:b-dhe5bl) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L99)):*
> ```Markdown
>     make start-graphene-multithreaded-server SGX=1
> 
> Because these commands will start the Apache server in the foreground, you will
> ```

ditto (repeating)
___
*[apache/README.md, line 117 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNgfB38j5Ub8Tc7uR:-LoLNgfC9dCMHdKsYgSB:bf5vw7y) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L117)):*
> ```Markdown
> There are two commands for cleaning up the directory:
> 
> * `make clean`: Clean up manifest, signature, and token files.
> ```

`Clean up` -> `Remove`
___
*[apache/README.md, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNj786PEZ09sPTpgB:-LoLNj786PEZ09sPTpgC:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L118)):*
> ```Markdown
> 
> * `make clean`: Clean up manifest, signature, and token files.
> * `make distclean`: Clean up the source code and the installation directory.
> ```

ditto


<!-- Sent from Reviewable.io -->

2019-09-11 15:49 UTC, HW42 requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYYpw-A6Lg1t4taMh8:-LoW-pNJ6kfbPF8OmyS5:baf4zla) (no related file):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Gautham has reported the same problem when running the `ab` client on a different machine. On the same problem, I haven't encountered this problem.

I've also seen another problem. Almost all the HTTP requests have received a response of different length from the first one. This causes these requests to be marked as "failed", but some says this doesn't actually mean that they failed.

I will look into this issue a little more. But if I can't fix this problem with configuration, I will create another issue/PR for this.  
</blockquote></details>

Don't know if this is related but now I also see:
```
*** An unexpected AEX vector occurred inside PAL. Exiting the thread. *** 
(vector = 0x2, type = 0x0 valid = 0, RIP = +0x00017744)
rax: 0x00000004 rcx: 0x00000000 rdx: 0x00000003 rbx: 0x7f2733165174
rsp: 0x06535740 rbp: 0x06535760 rsi: 0x04963660 rdi: 0x00000030
r8 : 0x06535788 r9 : 0x00000000 r10: 0x000a81c9 r11: 0x0048e611
r12: 0x04963660 r13: 0x7f2733165174 r14: 0x00000051 r15: 0x000a8000
rflags: 0x00010202 rip: 0x0b53e744
```

But the benchmark continues to run until it reached the error from above.

---
___
*[apache/.gitignore, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoL2mdN55HdW1Lm7WlZ:-LoVqLBoEW1JfnIMMeSc:b-kwl2n6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/.gitignore#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why "install", instead of "build"? We aren't installing it.
</blockquote></details>

It's "installed" with `./configure --prefix=...` and `make install`
___
*[apache/.gitignore, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoW-YxP7lJTUER7WCk6:-LoW-YxQ2ThThW8LwB-6:b-n1zqat) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/.gitignore#L5)):*
> ```ignore
> /install/*
> /result-*
> /*.html*
> ```

Where does this come from? (Same for the clean target)
___
*[apache/Makefile, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYMvvnA0xZUheTROEZ:-LoVr3b54TMdMmtP1ltE:b-dy7nqk) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L18)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think `INSTALL_DIR` and `HTTPD_SRC` need this comment.


<!-- Sent from Reviewable.io -->

2019-09-11 15:51 UTC, HW42 requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

___
*[apache/Makefile, line 274 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoW0Jxq0UuaNlK7KVnW:-LoW0Jxr6lbAO_0OUE7a:bed2a5y) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L274)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(RM) *.manifest *.manifest.sgx *.token *.sig pal_loader OUTPUT result-* *.html*
> ```

If wget fails it leaves a empty `tmp` file behind.


<!-- Sent from Reviewable.io -->

2019-09-16 20:49 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[apache/.gitignore, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoL2mdN55HdW1Lm7WlZ:-LovpGmQ5G8uwEsh57fR:b-21kkzp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/.gitignore#L3)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

It's "installed" with `./configure --prefix=...` and `make install`
</blockquote></details>

I missed `$(MAKE) install`, sorry. Resolving.


<!-- Sent from Reviewable.io -->

2019-09-19 18:19 UTC, dimakuv commented
I took ownership of this PR and will finish it.

2019-09-19 19:06 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 25 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @mkow)

___
*[apache/README.md, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lp9pSDG-MEmFEfVQi2_:-Lp9pSDHDUzcOro6NiFY:b-heini5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L1)):*
> ```Markdown
> # Apache example
> ```

FYI, I disliked the unnecessarily long and official format of the previous version. Compressed it significantly, similar to Memcached and Redis examples.
___
*[apache/README.md, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLKHZ9-ETji6GN7ufq:-Lp9ojqY1V6qo0Q1c3aU:b7bpzz3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please drop the version number, it will get out of sync quickly.
</blockquote></details>

I think it's important to clarify with which version we tested. (But I rewrote the whole thing, so check the text again.)
___
*[apache/README.md, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLLYHS-LNBf-OKak_N:-Lp9ufSJ8urCVSMUHhmj:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Apached` -> `Apache`
</blockquote></details>

Done
___
*[apache/README.md, line 58 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLMzVQ-IScYLfL3TID:-Lp9ug5GCw09_5hErDlK:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L58)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Apached` -> `Apache`
</blockquote></details>

Done
___
*[apache/README.md, line 68 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLN91W1pss1MPjenXb:-Lp9ugt5A9av_o0EWxBV:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L68)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we need to repeat everything here? Maybe just say that the rest of steps is same as in the native case?
</blockquote></details>

Done
___
*[apache/README.md, line 89 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNT520SK2LsvP6L88:-Lp9uher-nQL3afUy-1p:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L89)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (`Apached`)
</blockquote></details>

Done
___
*[apache/README.md, line 99 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNZ8R-7tZCL1vb38r:-Lp9uiEr9ZZ-eC6HUeEe:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L99)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (repeating)
</blockquote></details>

Done
___
*[apache/README.md, line 117 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNgfB38j5Ub8Tc7uR:-Lp9uioS-j3IyEWyKuDN:bpvc9g8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L117)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Clean up` -> `Remove`
</blockquote></details>

Done. Removed, this is trivial stuff, everyone knows it.
___
*[apache/README.md, line 118 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNj786PEZ09sPTpgB:-Lp9unH99DMSEouVZc49:bpvc9g8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/README.md#L118)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done. Removed, this is trivial stuff, everyone knows it.


<!-- Sent from Reviewable.io -->

2019-09-21 00:39 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, @mkow, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYYpw-A6Lg1t4taMh8:-LpG-pxcD7gb7bjZcwGD:b-98ap17) (no related file):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Don't know if this is related but now I also see:
```
*** An unexpected AEX vector occurred inside PAL. Exiting the thread. *** 
(vector = 0x2, type = 0x0 valid = 0, RIP = +0x00017744)
rax: 0x00000004 rcx: 0x00000000 rdx: 0x00000003 rbx: 0x7f2733165174
rsp: 0x06535740 rbp: 0x06535760 rsi: 0x04963660 rdi: 0x00000030
r8 : 0x06535788 r9 : 0x00000000 r10: 0x000a81c9 r11: 0x0048e611
r12: 0x04963660 r13: 0x7f2733165174 r14: 0x00000051 r15: 0x000a8000
rflags: 0x00010202 rip: 0x0b53e744
```

But the benchmark continues to run until it reached the error from above.
</blockquote></details>

Yes, this was indeed a cool bug: https://github.com/oscarlab/graphene/issues/1008.

I submitted a PR with a fix: https://github.com/oscarlab/graphene/pull/1012

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnZBvyd5d6wUdajo3vZ:-LpG3Qhz25cZOwKnghwb:bi3zg5o) (no related file):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

After fixing the $(RANDOM_FILE) problem, `make start-graphene-server SGX=1` actually does seem to work somewhat. Running ab against this, gives unusually high tail latencies for higher concurrency levels, e.g., -c 4 with longest request taking ~5 seconds. Sometimes ab reports close to 100% failed requests also.

`make start-graphene-multithreaded-server SGX=1` continues to create enclave after enclave though.


</blockquote></details>

- `WARNING: shim_times not implemented` is not important.

- `make start-graphene-multithreaded-server SGX=1` works fine for me.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LpGAcBlARw0o-SrcOYi:-LpGAcBlARw0o-SrcOYj:b-rm2r6c) (no related file):*
The correct run of `make start-graphene-server SGX=1` depends on https://github.com/oscarlab/graphene/pull/1012. We must merge that one first.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LpGEocsEuA5nhcMYDy-:-LpGEocsEuA5nhcMYDy0:bv5l1u1) (no related file):*
> apr_socket_recv: Connection reset by peer (104)

As far as I know, this is an old issue with our subpar `poll()/epoll()` implementation. It starts to break on heavy workloads. To fix this, we'll need to wait for a fix (currently WIP).

---
___
*[apache/.gitignore, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoW-YxP7lJTUER7WCk6:-LpG4UyaAdEomlRlpyAP:b-wnfmk9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/.gitignore#L5)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Where does this come from? (Same for the clean target)
</blockquote></details>

Done. Removed.
___
*[apache/httpd.manifest.template, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLNqtVD6Zlh55hkXnY:-LpG4lgx0S3CRROZsajT:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`of` -> `to`
</blockquote></details>

done
___
*[apache/httpd.manifest.template, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2GPN-96SEdnCFolr-:-LpG4woE6g179heDqZEI:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Python`?
</blockquote></details>

done
___
*[apache/httpd.manifest.template, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2GQwh7FbPnQULkKGg:-LpG4xWo2Stv8STy4bVd:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L34)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Python`?
</blockquote></details>

done
___
*[apache/httpd.manifest.template, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLO-aW9in6PnhYORbE:-LpG5wXO7NXT6kVFsvW5:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L47)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

python?
</blockquote></details>

Done
___
*[apache/httpd.manifest.template, line 69 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2ICZT-wNgWmDhAJO2:-LpG5ynp7IfhFwXodnTU:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L69)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not a Glibc library, must be in a separate list
</blockquote></details>

done
___
*[apache/httpd.manifest.template, line 79 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLOBzX4qDerquFT6jp:-LpG7ChS2pc2Wh8YwXJb:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/httpd.manifest.template#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Shouldn't configuration be `trusted`?
</blockquote></details>

done
___
*[apache/Makefile, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LnYMvvnA0xZUheTROEZ:-LpG7MuEAL7pMcmO3FN2:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/be2c2933768fafa36ba2990e858db7fc181914a2/apache/Makefile#L18)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

I don't think `INSTALL_DIR` and `HTTPD_SRC` need this comment.
</blockquote></details>

done
___
*[apache/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoL48iF6ZhQxjbP1uPX:-LpG7Ih61tBB2Zck2ar6:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`HTTPD` -> `httpd`
</blockquote></details>

done
___
*[apache/Makefile, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoL4j2RDD0md1UMx8ga:-LpG7Qda3uQf4pRZamfE:b73y2wj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`:=` -> `=` (works the same in this case, so no reason to use `:=`)
</blockquote></details>

done. Removed and just use the constant `4` below.
___
*[apache/Makefile, line 84 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LoLIm2uEAyNqzrx2Bot:-LpG7brG1-H1A2ce_PZd:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Grep'ing` -> `greping`
</blockquote></details>

done
___
*[apache/Makefile, line 123 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-Lo2Ixnk4TIF4vgVwxqG:-LpG7kfb16j1A2QPQlNR:bb7f2mf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/d17f7360b08e3549f25796b7ce2fd51bb578cec2/apache/Makefile#L123)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuva [...]

2019-09-23 00:13 UTC, mkow requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, and @thomasknauth)

___
*[apache/README.md, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LpQSFWQE95MQwdccoQS:-LpQSFWQE95MQwdccoQT:bj7lbdy) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b8f44286f4c8008abe21744a07f58ca8f6a25070/apache/README.md#L25)):*
> ```Markdown
> make start-native-server &
> ./benchmark-http.sh 127.0.0.1:8001
> killall -SIGINT httpd
> ```

Please use `kill` with `%%`
___
*[apache/README.md, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LpQSI77AH7z7iuzQ4Uo:-LpQSI782gSkfKz5VjWd:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b8f44286f4c8008abe21744a07f58ca8f6a25070/apache/README.md#L30)):*
> ```Markdown
> make start-graphene-server &
> ./benchmark-http.sh 127.0.0.1:8001
> killall -SIGINT pal-Linux
> ```

ditto
___
*[apache/README.md, line 35 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LpQSPFv2nvMG-GvsXpD:-LpQSPFv2nvMG-GvsXpE:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b8f44286f4c8008abe21744a07f58ca8f6a25070/apache/README.md#L35)):*
> ```Markdown
> SGX=1 make start-graphene-server &
> ./benchmark-http.sh 127.0.0.1:8001
> killall -SIGINT pal-Linux-SGX
> ```

ditto


<!-- Sent from Reviewable.io -->

2019-09-23 20:01 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, @mkow, and @thomasknauth)

___
*[apache/README.md, line 25 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LpQSFWQE95MQwdccoQS:-LpUJEEV9DpRDQcn8dTB:b-ml91nw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b8f44286f4c8008abe21744a07f58ca8f6a25070/apache/README.md#L25)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use `kill` with `%%`
</blockquote></details>

Done. The reason to use the specific names was that `%%` sends SIGINT to make and not to the underlying httpd process. And sending SIGINT to make makes it "fail" which can be confusing to the user. But it's just a README, soI don't mind using %%.
___
*[apache/README.md, line 30 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LpQSI77AH7z7iuzQ4Uo:-LpUhkLx9YffUMu2DDMG:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b8f44286f4c8008abe21744a07f58ca8f6a25070/apache/README.md#L30)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done
___
*[apache/README.md, line 35 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/36#-LpQSPFv2nvMG-GvsXpD:-LpUhlI-9cKfIGDY1TBN:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/b8f44286f4c8008abe21744a07f58ca8f6a25070/apache/README.md#L35)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2019-09-23 20:47 UTC, dimakuv reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, @mkow, and @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-09-24 00:23 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 6 unresolved discussions (waiting on @chiache, @HW42, and @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-09-25 03:31 UTC, HW42 approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 2 unresolved discussions (waiting on @chiache and @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-09-25 03:31 UTC, HW42 submitted a review, later dismissed
> Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: all files reviewed, 2 unresolved discussions (waiting on @chiache and @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-09-25 18:20 UTC, dimakuv submitted a review, later dismissed
> Dismissed @thomasknauth from a discussion.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-25 19:52 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-25 20:25 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/36)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-09-25 20:52 UTC, merged