Rewrite Lighttpd example
oscarlab/graphene-tests pull request #37
Opened 2019-08-28 07:00 UTC by chiache

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/oscarlab/graphene-tests/37)

2019-08-30 16:30 UTC, HW42 requested changes
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/37)* status: 7 of 9 files reviewed, 17 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[lighttpd/lighttpd.manifest.template, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYKmL56B_RpgyG0PCh:-LnYKmL56B_RpgyG0PCi:b-9yxycx) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/lighttpd.manifest.template#L81)):*
> ```
> 
> # SGX untrusted (allowed) files / directories
> sgx.allowed_files.html = file:html
> ```

Did you forget to commit part of your changes?

```
Accessing file:lighttpd.conf is denied. (Operation Denied) This file is not trusted or allowed.
```

And fixing this one, produces new similar errors.
___
*[lighttpd/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYDzEL9wCdAJ15rI7t:-LnYDzEL9wCdAJ15rI7u:b-971y8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L1)):*
> ```Makefile
> # Build the manifest for Lighttpd:
> ```

AFAICS, the official way of writing is "lighttpd" (i.e., no capitalization). Won't tag all other occurrences.
___
*[lighttpd/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYEbBQBnaUtUzpoKXc:-LnYEbBQBnaUtUzpoKXd:b-nl9gmo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L6)):*
> ```Makefile
> # - make DEBUG=1
> # - make SGX=1
> # - make SGX=1 DEBUG=1
> ```

Add a comment to make clear that the user should choose one variant.
___
*[lighttpd/Makefile, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYCgHl37EsdWz2_Gv6:-LnYCgHm2bHNtqcKBjbo:bnc2usl) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L15)):*
> ```Makefile
> # Constants
> 
> # Installation location of Lighttpd
> ```

comment looks redundant 
___
*[lighttpd/Makefile, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYCof7DYpTYZWq2zrg:-LnYCof7DYpTYZWq2zrh:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L18)):*
> ```Makefile
> INSTALL_DIR ?= install
> 
> # Source code directory and checksum of Lighttpd
> ```

ditto
___
*[lighttpd/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYCzmp3fl00vomaQPW:-LnYCzmq2vwMs1L3UYUV:b-haccpx) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L26)):*
> ```Makefile
> 	https://download.lighttpd.net/lighttpd/releases-1.4.x/
> 
> # Host and port for testing the Lighttpd server
> ```

Maybe it's just me, but sounds a bit odd to me. Maybe "Address and port on which Lighttpd should listen"
___
*[lighttpd/Makefile, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYDesw7NORj8kmAl4d:-LnYDesw7NORj8kmAl4e:b-coe2hg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L43)):*
> ```Makefile
> LDD  = ldd
> AWK  = awk
> RM   = rm
> ```

why not `?=`
___
*[lighttpd/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYFHP30LMGGp8l0cOu:-LnYFHP44HXwwqW-0Zgo:b-cjqtf2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L58)):*
> ```Makefile
> # The commands for downloading and compiling the Lighttpd source code, and
> # installing the binaries.
> $(INSTALL_DIR)/sbin/lighttpd: $(LIGHTTPD_SRC)
> ```

Using a directory as target is usually not a good idea. Probably best to just pick a file like `configure`
___
*[lighttpd/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYFRbK4aMr-YzLeeqy:-LnYFRbK4aMr-YzLeeqz:b-q64pkt) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L64)):*
> ```Makefile
> 	cd $(LIGHTTPD_SRC) && $(MAKE) install
> 
> $(LIGHTTPD_SRC): $(LIGHTTPD_SRC).tar.gz
> ```

See above.
___
*[lighttpd/Makefile, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYJvl78l3PwqDCq8rt:-LnYJvl81bPB-fYpvDLR:b6kku4r) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L71)):*
> ```Makefile
> 		wget --timeout=10 $${MIRROR}$(LIGHTTPD_SRC).tar.gz \
> 		&& break; \
> 	done
> ```

The checksum is never checked! Please first download it to a tempfile or so, then check the sha256 and only then rename it.
___
*[lighttpd/Makefile, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYFXmV11587H-hvjbQ:-LnYFXmV11587H-hvjbR:buuauii) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L80)):*
> ```Makefile
> # The dependencies are generated from the ldd results.
> 
> # Skip the GLIBC libraries because they are already listed
> ```

explain why
___
*[lighttpd/Makefile, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYIYtI1DhuaPjs99ME:-LnYIYtI1DhuaPjs99MF:bif795s) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L161)):*
> ```Makefile
> 	@echo "ssl.engine = \"enable\""                         >> $@
> 	@echo "ssl.pemfile = \"server.pem\""                    >> $@
> 	@echo "ssl.cipher-list = \"ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA\""	>> $@
> ```

Why can't we just use the default ciphers?
___
*[lighttpd/Makefile, line 241 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYIz5g18Iw3S-zyIfg:-LnYIz5g18Iw3S-zyIfh:b-t7nvca) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L241)):*
> ```Makefile
> .PHONY: distclean
> distclean: clean
> 	$(RM) -rf $(LIGHTTPD_SRC).tar.gz $(LIGHTTPD_SRC) $(INSTALL_DIR) $(TEST_DATA)
> ```

For my taste a bit odd that only `distclean` removes the lighttpd binaries. But ok.
___
*[lighttpd/README.md, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYGQmyAe4rCNwmgLhh:-LnYGQmyAe4rCNwmgLhi:baek6hw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/README.md#L11)):*
> ```Markdown
> 
> In this example, we build Lighttpd from the source code instead use an existing
> installation. To build Lighttpd on Ubuntu 16.04, please make sure that the
> ```

probably should read "instead of using", but I wold drop the whole "instead of" part of the sentence
___
*[lighttpd/README.md, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYHqLv-8mxvb_r3PPk:-LnYHqLwDMMVhEd0CbiK:b-ndpugn) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/README.md#L51)):*
> ```Markdown
>     wget http://127.0.0.1:8001/random/10K.1.html
> 
> You may also run the benchmark using `ab` from `L [...]

2019-08-30 16:43 UTC, HW42 requested changes
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/37)* status: 8 of 9 files reviewed, 18 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[lighttpd/README.md, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYP8LA-YCBTrdHQTpN:-LnYP8LBCswjjPIuUr-m:b-93wqr6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/README.md#L35)):*
> ```Markdown
> 
> First, start the Lighttpd server. By default, the installed Lighttpdd server will
> use the Prefork multi-processing module (MPM).
> ```

Isn't lighttpd single threaded by default?


<!-- Sent from Reviewable.io -->

2019-08-30 21:41 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/37)* status: 8 of 9 files reviewed, 21 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnZReSO9r3OxoFFpHr8:-LnZReSO9r3OxoFFpHr9:b-ev8dk9) (no related file):*
`make start-graphene-server` + `ab -k -n 10000 -c 2 http://127.0.0.1:8001/random/10K.1.html` gives

```
Completed 9000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 9954 requests completed
```

`make start-graphene-multithreaded-server` + `ab -k -n 10000 -c 1 http://127.0.0.1:8001/random/10K.1.html` gives

```
Completed 9000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 9976 requests completed
```

---
___
*[lighttpd/Makefile, line 150 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnZQ8P55RogPPo0X9Jh:-LnZQ8P55RogPPo0X9Ji:bfsiot8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L150)):*
> ```Makefile
> 	@rm -rf $@
> 	@echo "include \"lighttpd-server.conf\""                >> $@
> 	@echo "server.max-worker          = $(THREADS)"         >> $@
> ```

Where does $(THREADS) come from? Not set so far.
___
*[lighttpd/Makefile, line 212 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnZOwFzBKGQpyECv6o_:-LnZOwFzBKGQpyECv6oa:b-to0f4e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L212)):*
> ```Makefile
> 
> .PHONY: start-native-server
> start-native-server:
> ```

Missing dependency $(TEST_DATA). Same for all the other run targets.


<!-- Sent from Reviewable.io -->

2019-09-03 14:29 UTC, chiache reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/37)* status: 6 of 10 files reviewed, 19 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, and @thomasknauth)

___
*[lighttpd/lighttpd.manifest.template, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYKmL56B_RpgyG0PCh:-LnrOGU-1NDhAYfjx9QC:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/lighttpd.manifest.template#L81)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Did you forget to commit part of your changes?

```
Accessing file:lighttpd.conf is denied. (Operation Denied) This file is not trusted or allowed.
```

And fixing this one, produces new similar errors.
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYDzEL9wCdAJ15rI7t:-LnlRKxS69sayXntrzeA:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L1)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

AFAICS, the official way of writing is "lighttpd" (i.e., no capitalization). Won't tag all other occurrences.
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYEbBQBnaUtUzpoKXc:-LnrOHXp1jnhKVy8Hm9V:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L6)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Add a comment to make clear that the user should choose one variant.
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYCgHl37EsdWz2_Gv6:-LnrONdGAqHd--dy3PNM:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L15)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

comment looks redundant 
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYCof7DYpTYZWq2zrg:-LnrOO538BZzHEWnoKqz:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L18)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYDesw7NORj8kmAl4d:-LnlROR5Ec1dvVy7acvL:bss4a2b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L43)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

why not `?=`
</blockquote></details>

Removed.
___
*[lighttpd/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYFHP30LMGGp8l0cOu:-LnrOQtV3MHXg8Z9KDbx:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L58)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Using a directory as target is usually not a good idea. Probably best to just pick a file like `configure`
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYFRbK4aMr-YzLeeqy:-LnrORDbAywLOdPL3WiH:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L64)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

See above.
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 71 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYJvl78l3PwqDCq8rt:-LnrORzq8JQinbIrWwUn:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L71)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

The checksum is never checked! Please first download it to a tempfile or so, then check the sha256 and only then rename it.
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 80 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYFXmV11587H-hvjbQ:-LnrOlcu9fBUN0dqmSFK:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L80)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

explain why
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 150 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnZQ8P55RogPPo0X9Jh:-LnrPUMm2JpvcERHxFbR:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L150)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Where does $(THREADS) come from? Not set so far.
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 161 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYIYtI1DhuaPjs99ME:-LnrTYYG8RvCui288kcL:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L161)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Why can't we just use the default ciphers?
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 212 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnZOwFzBKGQpyECv6o_:-LnrTZcj1IfRcfHfJ94v:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L212)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Missing dependency $(TEST_DATA). Same for all the other run targets.
</blockquote></details>

Done.
___
*[lighttpd/README.md, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYGQmyAe4rCNwmgLhh:-LnrTagm3cFX1Er-m559:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/README.md#L11)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

probably should read "instead of using", but I wold drop the whole "instead of" part of the sentence
</blockquote></details>

Done.
___
*[lighttpd/README.md, line 35 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYP8LA-YCBTrdHQTpN:-LnrTboYEbCLvKoYejF4:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/README.md#L35)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Isn't lighttpd single threaded by default?
</blockquote></details>

Done.
___
*[lighttpd/README.md, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYHqLv-8mxvb_r3PPk:-LnrTcNm-hpBAekdO3nu:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/README.md#L51)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

`ab` if from `apache2-utils`
</blockquote></details>

Done.
___
*[lighttpd/README.md, line 77 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYI0Y85W1-NWRp1M-v:-LnrTdGbC-6RxJbgYwxC:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/README.md#L77)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[lighttpd/README.md, line 108 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYI9Qq5oN9Rm [...]

2019-09-05 18:34 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/37)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @HW42, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnZReSO9r3OxoFFpHr8:-Lo1bGzxEi8q9_K55UMe:b-lwva8q) (no related file):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

`make start-graphene-server` + `ab -k -n 10000 -c 2 http://127.0.0.1:8001/random/10K.1.html` gives

```
Completed 9000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 9954 requests completed
```

`make start-graphene-multithreaded-server` + `ab -k -n 10000 -c 1 http://127.0.0.1:8001/random/10K.1.html` gives

```
Completed 9000 requests
apr_pollset_poll: The timeout specified has expired (70007)
Total of 9976 requests completed
```
</blockquote></details>

Thomas, what if you run `ab` with an explicit timeout of say 120 seconds? Like this: `ab -s 120 ...`? I observed that Graphene-SGX-based web servers introduce a very long tail of latencies for some unlucky requests.

---
___
*[lighttpd/lighttpd.manifest.template, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYKmL56B_RpgyG0PCh:-Lo1d6js2otMmj2ry34y:bu0omoi) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/lighttpd.manifest.template#L81)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why not have the below files as trusted_files? They are clearly security-sensitive.
___
*[lighttpd/lighttpd.manifest.template, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1c8vW0vvZW2ZGFWwn:-Lo1c8vW0vvZW2ZGFWwo:bjiqzqg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L29)):*
> ```
> fs.mount.lib.uri = file:$(GRAPHENEDIR)/Runtime
> 
> # Host-level libraries (/lib/x86_64-linux-gnu) required by the Python executable
> ```

What is this `Python executable`? Seems like a copy-paste artifact.
___
*[lighttpd/lighttpd.manifest.template, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1cE7u9q1wYedxYKqV:-Lo1cE7u9q1wYedxYKqW:b-6yqyxf) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L34)):*
> ```
> fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu
> 
> # Host-level directory (/usr) required by the Python executable
> ```

What is this `Python executable`? Seems like a copy-paste artifact.

And why is `/usr` required by Lighttpd?
___
*[lighttpd/lighttpd.manifest.template, line 44 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1cQjv3ycY5obc_Dze:-Lo1cQjv3ycY5obc_Dzf:bmvu8l8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L44)):*
> ```
> fs.mount.html.uri = file:html
> 
> # Mount /var/tmp
> ```

Why is this required by Lighttpd?
___
*[lighttpd/lighttpd.manifest.template, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1cYJF5ev1Y91HL_w-:-Lo1cYJG5TJ0uU2wWb43:bnfi4nd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L52)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave. For SGX v1, the enclave
> # size must be specified during signing. If Python needs more virtual memory
> ```

`Python` again
___
*[lighttpd/lighttpd.manifest.template, line 74 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1chc361q2RNntDYpK:-Lo1chc361q2RNntDYpL:bqqfb08) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L74)):*
> ```
> sgx.trusted_files.libutil = file:$(GRAPHENEDIR)/Runtime/libutil.so.1
> sgx.trusted_files.libpthread = file:$(GRAPHENEDIR)/Runtime/libpthread.so.0
> sgx.trusted_files.libz = file:/lib/x86_64-linux-gnu/libz.so.1
> ```

This is not a Glibc library, should be moved out of this list. I guess it is an explicit dependency of Lighttpd?
___
*[lighttpd/lighttpd.manifest.template, line 85 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1etjF7ypUSXwUFTBV:-Lo1etjF7ypUSXwUFTBW:b-h0oa49) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L85)):*
> ```
> sgx.trusted_files.mod_openssl = file:$(INSTALL_DIR)/lib/mod_openssl.so
> 
> $(LIGHTTPD_TRUSTED_LIBS)
> ```

BTW, this is an arguable optimization. What if a new version of lighttpd looks for some lib in a new path not covered by the above mount points? Your solution is nice but looks only partial. In general, I would like an actual tool to create a manifest instead of these bash hacks.
___
*[lighttpd/Makefile, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1dYqb--6siYRhDzq6:-Lo1dYqb--6siYRhDzq7:b-1ky9rk) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/Makefile#L29)):*
> ```Makefile
> 
> # Number of lighttpd threads for multithreaded execution
> LIGHTTPD_THREADS ?= 25
> ```

This number is confusing. Any reason for it? Maybe add in a comment if there is a particular reason. Not blocking on this though.
___
*[lighttpd/Makefile, line 55 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1dvQ81I-n3gFqhaKN:-Lo1dvQ81I-n3gFqhaKO:bg0kbtw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/Makefile#L55)):*
> ```Makefile
> $(INSTALL_DIR)/sbin/lighttpd: $(LIGHTTPD_SRC)/configure
> 	cd $(LIGHTTPD_SRC) && ./configure --prefix=$(abspath $(INSTALL_DIR)) \
> 		--with-openssl --without-pcre --without-zlib --without-bzip2
> ```

So here you build lighttpd without `zlib` but you still have it in the manifest?
___
*[lighttpd/Makefile, line 147 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1fW_p53tLo-3FP-vm:-Lo1fW_p53tLo-3FP-vn:bp6eht) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/Makefile#L147)):*
> ```Makefile
> 
> lighttpd-server.conf:
> 	@rm -rf $@
> ```

I'd replace all `rm -rf` with `$(RM) -r`, but not blocking on this
___
*[lighttpd/Makefile, line 204 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1g-vv3CAsNL6IcFIQ:-Lo1g-vv3CAsNL6IcFIR:b-clgs8j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/Makefile#L204)):*
> ```Makefile
> #
> # - make start-graphene-server:
> #     Start the lighttpd server under Graphene in the foreground (single-thread)
> ```

`single-threaded`


<!-- Sent from Reviewable.io -->

2019-09-09 11:37 UTC, mkow requested changes
> Reviewed 6 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/37)* status: all files reviewed, 39 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, @HW42, and @thomasknauth)

___
*[lighttpd/.gitignore, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKnCvx-5ENPpxS5C9K:-LoKnCvx-5ENPpxS5C9L:b-lbfo1a) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/.gitignore#L4)):*
> ```ignore
> /result-*
> /OUTPUT
> /install/
> ```

Why have you renamed it to "install"? We aren't installing it, but just building.
___
*[lighttpd/lighttpd.manifest.template, line 81 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYKmL56B_RpgyG0PCh:-LoKeSHw-kqJLW_foQ1H:b-qe14mh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/lighttpd.manifest.template#L81)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not have the below files as trusted_files? They are clearly security-sensitive.
</blockquote></details>

+1, please also remember to update the comment above after fixing this.
___
*[lighttpd/lighttpd.manifest.template, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKeueb79wKXBm_LvVY:-LoKeueb79wKXBm_LvVZ:bcvq44w) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L1)):*
> ```
> # Lighttpd manifest example
> ```

`Lighttpd` -> `lighttpd`
___
*[lighttpd/lighttpd.manifest.template, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKf2cW0pYMOFs82eZA:-LoKf2cW0pYMOFs82eZB:bcvq44w) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L5)):*
> ```
> # This manifest was prepared and tested on Ubuntu 16.04.
> #
> # Lighttpd must be run with the pal_loader:
> ```

`Lighttpd` -> `lighttpd`
___
*[lighttpd/lighttpd.manifest.template, line 13 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKdFa147tozGBBUAdj:-LoKdFa2AHxCnjbeaUWv:byq3o82) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L13)):*
> ```
> loader.execname = lighttpd
> 
> # Graphene environment, including the path of the library OS and the debug
> ```

`of` -> `to`
___
*[lighttpd/lighttpd.manifest.template, line 18 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKf42t2x5KgsAx-Di4:-LoKf42t2x5KgsAx-Di5:bcvq44w) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L18)):*
> ```
> loader.debug_type = $(GRAPHENEDEBUG)
> 
> # Environment variables for Lighttpd
> ```

`Lighttpd` -> `lighttpd`
___
*[lighttpd/lighttpd.manifest.template, line 77 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKf7M392Ezzvtt_tAs:-LoKf7M392Ezzvtt_tAt:bcvq44w) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/lighttpd.manifest.template#L77)):*
> ```
> sgx.trusted_files.nss_files = file:/lib/x86_64-linux-gnu/libnss_files.so.2
> 
> # Lighttpd modules and dependencies
> ```

`Lighttpd` -> `lighttpd`
___
*[lighttpd/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYDzEL9wCdAJ15rI7t:-LoKfC9uBnJi2dr_gaYa:bcsf49q) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L1)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, there are still a few unfixed occurences.
___
*[lighttpd/Makefile, line 111 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKi2FZ8BQznx8Gn8cI:-LoKi2F_74_eY12VKhZk:bv2qq3u) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/Makefile#L111)):*
> ```Makefile
> # lighttpd manifests:
> #   For each dependency, generate a rule as follows:
> #       sgx.trusted_files.xxxx = file:xxxx
> ```

Isn't this comment about the code above, not below?
___
*[lighttpd/Makefile, line 147 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-Lo1fW_p53tLo-3FP-vm:-LoKiONr1n9FFW-aBYFZ:b15y88f) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/Makefile#L147)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I'd replace all `rm -rf` with `$(RM) -r`, but not blocking on this
</blockquote></details>

Please do this in the whole Makefile.
___
*[lighttpd/README.md, line 12 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKjrid4Mrtnbx2fEt-:-LoKjrid4Mrtnbx2fEt0:bcihi6u) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/README.md#L12)):*
> ```Markdown
> In this example, we build lighttpd from the source code instead of using an
> existing installation. To build lighttpd on Ubuntu 16.04, please make sure that
> the following packages are properly installed:
> ```

The command doesn't match the sentence. Please either really just list the packages, or say that the missing dependencies can be installed by the following command (and mention that it's Ubuntu/Debian-specific).
___
*[lighttpd/README.md, line 134 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKkMPB0isqdNOqDBNq:-LoKkMPB0isqdNOqDBNr:b-61qfdy) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/README.md#L134)):*
> ```Markdown
> terminate the server.
> 
> # Clean up the directory
> ```

Please be consistent: You use -ing in other headings in this file.
___
*[lighttpd/README.md, line 138 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKmXhd64-HCkTJzUVj:-LoKmXhd64-HCkTJzUVk:b-ctpw9r) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/README.md#L138)):*
> ```Markdown
> There are two commands for cleaning up the directory:
> 
> * `make clean`: Clean up manifest, signature, and token files.
> ```

`Clean up` -> `Remove` (we're "cleaning" the directory, not those particular files - those files are just removed)
___
*[lighttpd/README.md, line 139 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKm_Y13WckIrMTwv9O:-LoKm_Y13WckIrMTwv9P:b-jbwfg6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/README.md#L139)):*
> ```Markdown
> 
> * `make clean`: Clean up manifest, signature, and token files.
> * `make distclean`: Clean up the source code and the installation directory.
> ```

ditto + `source code` -> `lighttpd source code` + `installation` -> `build` (technically we don't run `make install`)


<!-- Sent from Reviewable.io -->

2019-09-11 14:31 UTC, HW42 requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/37)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, @HW42, @mkow, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoVijiBAZew_wtuR6np:-LoVijiBAZew_wtuR6nq:brlaqnx) (no related file):*
After startup wget-ing a single file works. But when I run the benchmark script I get a lot of `file_map - ocall returned -22` in lighttpd output and subsequent wgets return 500.

---
___
*[lighttpd/.gitignore, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKnCvx-5ENPpxS5C9K:-LoVcFdeDUG_vk44XRfl:b-g7qfuv) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/.gitignore#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Why have you renamed it to "install"? We aren't installing it, but just building.
</blockquote></details>

It's meant as in `make install`
___
*[lighttpd/Makefile, line 15 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LnYCgHl37EsdWz2_Gv6:-LoVdMIH0df-6GY-EHHf:b-q050u3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/50efd42241579f6b82a960d69c7543a0c0fe8f88/lighttpd/Makefile#L15)):*
<details><summary><i>Previously, chiache (Chia-Che Tsai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still think that `INSTALL_DIR` and `LIGHTTPD_SRC` don't need this comment.
___
*[lighttpd/Makefile, line 131 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoViJM-1IPyHQIqoH4w:-LoViJM0EC2ZUt6S207S:b-bteoo) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/Makefile#L131)):*
> ```Makefile
> 		-manifest $< -output $@
> 
> lighttpd.sig: lighttpd.manifest.sgx
> ```

This doesn't work if only `.sig` is missing. Use somehting like:

```diff
diff --git a/lighttpd/Makefile b/lighttpd/Makefile
index 8a16407..7bc1043 100644
--- a/lighttpd/Makefile
+++ b/lighttpd/Makefile
@@ -122,13 +122,11 @@ lighttpd.manifest: lighttpd.manifest.template lighttpd-trusted-libs
 #   Generating the SGX-specific manifest (lighttpd.manifest.sgx), the enclave signature,
 #   and the token for enclave initialization.
 
-lighttpd.manifest.sgx: lighttpd.manifest
+lighttpd.sig lighttpd.manifest.sgx: lighttpd.manifest
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
                -libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
                -key $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem \
-               -manifest $< -output $@
-
-lighttpd.sig: lighttpd.manifest.sgx
+               -manifest $< -output $<.sgx
 
 lighttpd.token: lighttpd.sig
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
```
___
*[lighttpd/README.md, line 139 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKm_Y13WckIrMTwv9O:-LoVeGDxAf2oX4NkjG9t:b-7hcwy0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/README.md#L139)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto + `source code` -> `lighttpd source code` + `installation` -> `build` (technically we don't run `make install`)
</blockquote></details>

we do


<!-- Sent from Reviewable.io -->

2019-09-16 20:44 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/37)* status: all files reviewed, 26 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, and @thomasknauth)

___
*[lighttpd/.gitignore, line 4 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKnCvx-5ENPpxS5C9K:-LovoEuD382HRNBi2biM:b-w9lodc) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/.gitignore#L4)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

It's meant as in `make install`
</blockquote></details>

Oh, I somehow missed `$(MAKE) install` call. Resolving then.
___
*[lighttpd/README.md, line 139 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/37#-LoKm_Y13WckIrMTwv9O:-LovoSz53HYbYqB0REai:b-75qoy8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/6183ee84767abf1904920550b8ab0fcbe10876cd/lighttpd/README.md#L139)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

we do
</blockquote></details>

ditto, resolving


<!-- Sent from Reviewable.io -->

2019-10-08 22:45 UTC, closed without merging