Rewrite Bash example
oscarlab/graphene-tests pull request #39
Opened 2019-08-29 04:21 UTC by chiache

2019-08-30 12:45 UTC, HW42 requested changes
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 9 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[bash/.gitignore, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXWhZMD1TCCRUgP62z:-LnXWhZMD1TCCRUgP63-:bk6rn9s) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/.gitignore#L1)):*
> ```ignore
> /scripts/*
> ```

This is wrong. It ignores committed files.

Please separate the scripts from the runtime test directory. AFAICS all tests files are empty anyway, so they can simply generated before running the tests.
___
*[bash/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXQxCH-vWMXOOXl797:-LnXQxCI45-lzbVbDpQI:b-ws0jfa) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L6)):*
> ```Makefile
> # - make DEBUG=1
> # - make SGX=1
> # - make SGX=1 DEBUG=1
> ```

Please clarify the comment that you should choose one of those commands. Not run them in ordner ;]
___
*[bash/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXREuG8TEvs8LOdzMi:-LnXREuG8TEvs8LOdzMj:beelq4t) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L26)):*
> ```Makefile
> GREP = grep
> LDD  = ldd
> AWK  = awk
> ```

Maybe `?=`, or is there are reason for this varaint?
___
*[bash/Makefile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXVorr-8SXbFZHz8vU:-LnXVorr-8SXbFZHz8vV:b-xt6znl) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L42)):*
> ```Makefile
> 
> # Skip the GLIBC libraries because they are already listed
> GLIBC_DEPS = linux-vdso /lib64/ld-linux-x86-64 libc libm librt libdl libpthread
> ```

Explain that this is because they are replaced by the graphene libs. 
___
*[bash/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXRmOC9Z12nDiUAP2a:-LnXRmOC9Z12nDiUAP2b:bi5a6j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L45)):*
> ```Makefile
> 
> # Listing all the Apache dependencies, besides Glibc libraries
> .INTERMEDIATE: $(addsuffix .deps,bash $(PROGRAMS))
> ```

 - Since this is supposed to be an easy to use example for others, please explain such make specialties.
 - Why is this needed at all?
___
*[bash/Makefile, line 95 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXUG37EZGfz_BPCQXK:-LnXUG37EZGfz_BPCQXL:b-2mu1js) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L95)):*
> ```Makefile
> 		-manifest $< -output $@
> 	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
> 		-output bash.token -sig bash.sig
> ```

Token and manifest.sgx+sig should be two targets. .sig should be declared as output.
___
*[bash/Makefile, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXUYy99-OekMZL8mwC:-LnXUYyA0wEyve1MJ6ro:b7msk0b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L103)):*
> ```Makefile
> 		-manifest $< -output $@
> 	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
> 		-output $(basename $<).token -sig $(basename $<).sig
> ```

ditto (2 targets, .sig)
___
*[bash/manifest.template, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXV7XF538jP4AK931t:-LnXV7XF538jP4AK931u:bethchr) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L9)):*
> ```
> 
> # The executable to load in Graphene. We replace the $(EXECPATH) variable for
> # each program that a manifest is generated for.
> ```

Do we really want to use Make style variables here, when it's not at all Make but just sed? AFAIK `@@VARIABLE@@` is quite common syntax for such constructs.
___
*[bash/manifest.template, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXW7rX8qmymM27aMhs:-LnXW7rY6TK5cCKohXxa:b3gg5rd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L79)):*
> ```
> sgx.trusted_files.libpthread = file:$(GRAPHENEDIR)/Runtime/libpthread.so.0
> sgx.trusted_files.libz = file:/lib/x86_64-linux-gnu/libz.so.1
> sgx.trusted_files.libnss_files = file:/lib/x86_64-linux-gnu/libnss_files.so.2
> ```

Why are the last 2 lines needed?


<!-- Sent from Reviewable.io -->

2019-08-30 15:44 UTC, HW42 requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 11 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache)

___
*[bash/Makefile, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXzmDVACP8PNlVWy5T:-LnXzmDX5Zy8EclVqRmz:b-qmcuvi) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L92)):*
> ```Makefile
> 	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
> 		-libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
> 		-key $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem \
> ```

Do we want to hard code the key path here? In the main repo that's configurable.
___
*[bash/Makefile, line 129 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnY0dInEG1jH0n7vg86:-LnY0dIp0OMM3LkDIAwP:b-hdc8v8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L129)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(RM) *.manifest *.manifest.sgx *.token *.sig pal_loader
> ```

`OUTPUT` and `scripts/testdir/x`are missing


<!-- Sent from Reviewable.io -->

2019-08-30 21:56 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 13 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @HW42)

___
*[bash/Makefile, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnZVEBq8e9iDeA9Nr-B:-LnZVEBq8e9iDeA9Nr-C:b-lbcv84) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L44)):*
> ```Makefile
> GLIBC_DEPS = linux-vdso /lib64/ld-linux-x86-64 libc libm librt libdl libpthread
> 
> # Listing all the Apache dependencies, besides Glibc libraries
> ```

Apache?
___
*[bash/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXRmOC9Z12nDiUAP2a:-LnZWQ8zEgGuxgECkwgC:b-bklvr0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L45)):*
> Why is this needed at al

I disagree. This is not a course in getting everyone and their mother up to speed on Makefiles or Graphene options. In general, I have the feeling the comments in the manifests and makefiles are way too verbose. Instead of explaining each and every option in all the makefiles/manifests, just link to some webpage where they are described.
___
*[bash/Makefile, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnZVHEYDxjfPGSiy9J3:-LnZVHEYDxjfPGSiy9J4:b-lbcv84) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L51)):*
> ```Makefile
> 		($(GREP) -v -x $(patsubst %,-e %,$(GLIBC_DEPS)) || true) > $@
> 
> # Generating manifest rules for Apache dependencies
> ```

Apache?


<!-- Sent from Reviewable.io -->

2019-09-05 20:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 21 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @HW42)

___
*[bash/Makefile, line 30 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-Lo20MNyCkY4oznEbrSr:-Lo20MNyCkY4oznEbrSs:b3osnha) ([raw file](https://github.com/oscarlab/graphene-tests/blob/937b59d5e998ac8ab9e3addb72f5f4a09efda659/bash/Makefile#L30)):*
> ```Makefile
> 
> 
> distclean: clean-manifests
> ```

We don't need a distclean target? At least make it an alias to clean, so users typing `make distclean` don't get confused.
___
*[bash/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-Lo1ztmpE5BTlAUkwuvS:-Lo1ztmpE5BTlAUkwuvT:b-pap508) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L58)):*
> ```Makefile
> 		N=`echo $$F | tr --delete '-'`; \
> 		echo -n "sgx.trusted_files.$$N = file:$$P\\\\n"; \
> 	done > $@
> ```

This ldd-based finding of trusted libs should be exactly the same as in your lighttpd example. Please copy-paste from there.
___
*[bash/Makefile, line 64 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-Lo2-JwG6VpDXLmlL2Mf:-Lo2-JwG6VpDXLmlL2Mg:b-7rgiol) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L64)):*
> ```Makefile
> 	@for F in $(PROGRAMS); do \
> 		echo -n "sgx.trusted_children.$$F = file:$$F.sig\\\\n"; \
> 		echo -n "sgx.trusted_files.$$F    = file:`which $$F`\\\\n"; \
> ```

Why do we need to specify these programs as trusted files additionally?
___
*[bash/Makefile, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXzmDVACP8PNlVWy5T:-Lo2-oHQ14Fg9gtuI8j2:b-j8quax) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L92)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Do we want to hard code the key path here? In the main repo that's configurable.
</blockquote></details>

For me, since this is just an example, this is acceptable. I haven't heard of anyone creating the key in a non-default path.
___
*[bash/Makefile, line 95 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXUG37EZGfz_BPCQXK:-Lo206ZA6DNPKcK4zzos:b32v57) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L95)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Token and manifest.sgx+sig should be two targets. .sig should be declared as output.
</blockquote></details>

+1
___
*[bash/Makefile, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXUYy99-OekMZL8mwC:-Lo207z9Cq3U6mnn7exM:b32v57) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L103)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

ditto (2 targets, .sig)
</blockquote></details>

+1
___
*[bash/manifest.template, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-Lo20Z3qDLBeGK2LdPoB:-Lo20Z3qDLBeGK2LdPoC:b-65aikm) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L4)):*
> ```
> #
> # This is a general manifest template for running Bash and core utility programs,
> # including ls, cat, cp, and rm.
> ```

`date` is also the utility run in Graphene. Please add to the list.
___
*[bash/manifest.template, line 9 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXV7XF538jP4AK931t:-Lo20l107CEcHrUVr4LE:bd56jo7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L9)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Do we really want to use Make style variables here, when it's not at all Make but just sed? AFAIK `@@VARIABLE@@` is quite common syntax for such constructs.
</blockquote></details>

For me, Make-style vars are fine. This is a historical thing, let's keep it for now (and maybe create a separate PR to fix it everywhere in the future).
___
*[bash/manifest.template, line 23 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-Lo211GA0Du7VzQZrsIG:-Lo211GA0Du7VzQZrsIH:b-26oynd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L23)):*
> ```
> loader.env.PATH = /bin:/usr/bin
> loader.env.USERNAME = root
> loader.env.HOME = /
> ```

Can we have some comments on USERNAME and HOME? What's the point of them for bash?
___
*[bash/manifest.template, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-Lo21CGU6_v66xAtR2ii:-Lo21CGU6_v66xAtR2ij:bdk7ku9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L38)):*
> ```
> fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu
> 
> # Mount /usr
> ```

Why is this needed?
___
*[bash/manifest.template, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-Lo21AVLExmdhAAeMFIR:-Lo21AVLExmdhAAeMFIS:b-t446ai) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L43)):*
> ```
> fs.mount.usr.uri = file:/usr
> 
> # Mount /usr
> ```

`Mount /bin`
___
*[bash/manifest.template, line 78 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-Lo21Ql0Cuj143Bu7xJB:-Lo21Ql0Cuj143Bu7xJC:b-g2yvn2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L78)):*
> ```
> sgx.trusted_files.libutil = file:$(GRAPHENEDIR)/Runtime/libutil.so.1
> sgx.trusted_files.libpthread = file:$(GRAPHENEDIR)/Runtime/libpthread.so.0
> sgx.trusted_files.libz = file:/lib/x86_64-linux-gnu/libz.so.1
> ```

libz is not a Glibc library. Move to its own list.
___
*[bash/manifest.template, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXW7rX8qmymM27aMhs:-Lo21VC9C7YddMEaZmya:b32v57) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L79)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Why are the last 2 lines needed?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2019-09-09 00:46 UTC, mkow requested changes
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 24 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache and @HW42)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LoITlkE1AkU5j5EeV8D:-LoITlkE1AkU5j5EeV8E:buvtnbc) (no related file):*
A lot of files from scripts/ seem to be unused. Do we really want them if we don't run them as a part of `make test`? Asking especially about the `looper`, as it's a binary file and seems to be unused.

---
___
*[bash/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXREuG8TEvs8LOdzMi:-LoIQO7GDeyp4q53m0qw:b-iph6oh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L26)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Maybe `?=`, or is there are reason for this varaint?
</blockquote></details>

`?=` works the same as `=` in this case, command-line arguments override both `?=` and `=` assignments.
___
*[bash/manifest.template, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LoISq2IEFZ1WSXIxcUj:-LoISq2IEFZ1WSXIxcUk:b-cmnxg5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L84)):*
> ```
> $(TRUSTED_LIBS)
> 
> # Listing all the signatures that can be created as child enclaves
> ```

`Listing` -> `List` (or the other way, but please be consistent in the whole file)
___
*[bash/README.md, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LoIT9cw4vpmvFqZJS-M:-LoIT9cw4vpmvFqZJS-N:b-y7esta) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/README.md#L17)):*
> ```Markdown
> Run `make SGX=1` (non-debug) or `make SGX=1 DEBUG=1` (debug) in the directory.
> 
> # Run Bash with Graphene
> ```

`Run` -> `Running`


<!-- Sent from Reviewable.io -->

2019-09-11 15:57 UTC, HW42 requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, @mkow, and @thomasknauth)

___
*[bash/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXREuG8TEvs8LOdzMi:-LoW0WVa3V5hrwKL2Xjs:b-nlvl8w) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`?=` works the same as `=` in this case, command-line arguments override both `?=` and `=` assignments.
</blockquote></details>

But not environment variables, IIRC.
___
*[bash/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXRmOC9Z12nDiUAP2a:-LoW0gf61Ic-o65bY8o0:bt0tjlm) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L45)):*
> This is not a course in getting everyone [...] up to speed [...]

My impression was that this is exactly the purpose. I'm fine either way, but then it should be consistent.

> Why is this needed at all?

This question still stands. I.e., why is this declared  as "INTERMEDIATE" in the first place.
___
*[bash/Makefile, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXzmDVACP8PNlVWy5T:-LoW1PFB4IjI-TF9JFWI:b3pkg2m) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L92)):*
> I haven't heard of anyone creating the key in a non-default path.

Guess why I noticed this ;]

But yes it's just an example. I wont block on this.


<!-- Sent from Reviewable.io -->

2019-09-16 20:56 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, @HW42, and @thomasknauth)

___
*[bash/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXREuG8TEvs8LOdzMi:-Lovpt5M0iWSMqFoF7dU:b-we5coh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L26)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

But not environment variables, IIRC.
</blockquote></details>

Yup, but do we want to take them from env? I don't know what's the convention (i.e. which settings should be read from env and which shouldn't), do you know maybe?
___
*[bash/Makefile, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXzmDVACP8PNlVWy5T:-Lovq_7a2K6fdzwQxq8L:bzabl8m) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L92)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

> I haven't heard of anyone creating the key in a non-default path.

Guess why I noticed this ;]

But yes it's just an example. I wont block on this.
</blockquote></details>

I'm also having the key in a non-standard location on one of our servers, would be nice to support it.


<!-- Sent from Reviewable.io -->

2019-09-25 03:48 UTC, HW42 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, @mkow, and @thomasknauth)

___
*[bash/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXREuG8TEvs8LOdzMi:-LpaWNIq0qQNkA0Sj-e9:b-huv7t2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Yup, but do we want to take them from env? I don't know what's the convention (i.e. which settings should be read from env and which shouldn't), do you know maybe?
</blockquote></details>

Not sure what's "the convention" is. I guess given the flexibility of Makefiles you will find a bunch of project for either side.

I think this should be configurable because it's sometimes much easier to set an env-var than changing command lines (usually in multiple places). And I don't see a down side here.


<!-- Sent from Reviewable.io -->

2019-09-25 13:49 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: OSCAR Lab) (waiting on @chiache, @dimakuv, @HW42, and @thomasknauth)

___
*[bash/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXREuG8TEvs8LOdzMi:-Lpcfd_Q6EVc5Jm4OG_r:bao6bw5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L26)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Not sure what's "the convention" is. I guess given the flexibility of Makefiles you will find a bunch of project for either side.

I think this should be configurable because it's sometimes much easier to set an env-var than changing command lines (usually in multiple places). And I don't see a down side here.
</blockquote></details>

Ok, we can go for `?=` then.


<!-- Sent from Reviewable.io -->

2019-10-02 20:31 UTC, dimakuv commented
I took ownership of this PR.

2019-10-03 00:16 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 14 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @HW42, @mkow, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LoITlkE1AkU5j5EeV8D:-LqDwA-Z5-a01Czx4LFO:b4e0l5j) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

A lot of files from scripts/ seem to be unused. Do we really want them if we don't run them as a part of `make test`? Asking especially about the `looper`, as it's a binary file and seems to be unused.
</blockquote></details>

Done. Removed unused scripts.

---
___
*[bash/.gitignore, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXWhZMD1TCCRUgP62z:-LqDwXv4ACqhrpxiD-qN:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/.gitignore#L1)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

This is wrong. It ignores committed files.

Please separate the scripts from the runtime test directory. AFAICS all tests files are empty anyway, so they can simply generated before running the tests.
</blockquote></details>

Done.
___
*[bash/Makefile, line 6 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXQxCH-vWMXOOXl797:-LqDB7zq6rKMitzgwxZ-:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L6)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Please clarify the comment that you should choose one of those commands. Not run them in ordner ;]
</blockquote></details>

Done.
___
*[bash/Makefile, line 26 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXREuG8TEvs8LOdzMi:-LqDBHyZ70xSgV-o90Mw:b-tfj049) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L26)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Ok, we can go for `?=` then.
</blockquote></details>

Done. I just removed it, I see no need in this.
___
*[bash/Makefile, line 42 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXVorr-8SXbFZHz8vU:-LqDCxni7mbdbuSQT47o:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L42)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

Explain that this is because they are replaced by the graphene libs. 
</blockquote></details>

Done
___
*[bash/Makefile, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnZVEBq8e9iDeA9Nr-B:-LqDCy_F28DdfKJyDtWV:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L44)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Apache?
</blockquote></details>

Done
___
*[bash/Makefile, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXRmOC9Z12nDiUAP2a:-LqDDsW04oabbRLMqAbi:bctllp7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L45)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

> This is not a course in getting everyone [...] up to speed [...]

My impression was that this is exactly the purpose. I'm fine either way, but then it should be consistent.

> Why is this needed at all?

This question still stands. I.e., why is this declared  as "INTERMEDIATE" in the first place.
</blockquote></details>

`.INTERMEDIATE` is used here so that Bash deletes this file after the build (it's a nice feature actually). I admit that the following code looks like dark magic (and it is), but I am against explaining why this works. Sorry, but I currently don't see what kind of comment to add to explain it succinctly.
___
*[bash/Makefile, line 51 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnZVHEYDxjfPGSiy9J3:-LqDEWUbBPLL3ojUIrNR:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L51)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Apache?
</blockquote></details>

Done
___
*[bash/Makefile, line 92 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXzmDVACP8PNlVWy5T:-LqDGhUv-J4WuFWKSmC5:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L92)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'm also having the key in a non-standard location on one of our servers, would be nice to support it.
</blockquote></details>

Done
___
*[bash/Makefile, line 95 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXUG37EZGfz_BPCQXK:-LqDHK2L287zpyjCTLhl:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L95)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done
___
*[bash/Makefile, line 103 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXUYy99-OekMZL8mwC:-LqDHO4iAL5QRPjAbg2j:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L103)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done
___
*[bash/Makefile, line 129 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnY0dInEG1jH0n7vg86:-LqDwe2F2xDnhdlgZBeO:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/Makefile#L129)):*
<details><summary><i>Previously, HW42 wrote…</i></summary><blockquote>

`OUTPUT` and `scripts/testdir/x`are missing
</blockquote></details>

Done
___
*[bash/manifest.template, line 79 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LnXW7rX8qmymM27aMhs:-LqDwpli9Lam8jtAwr6j:b-ctk1z9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done. Added explanations.
___
*[bash/manifest.template, line 84 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LoISq2IEFZ1WSXIxcUj:-LqDISloEMVfAzyGo2xN:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/manifest.template#L84)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Listing` -> `List` (or the other way, but please be consistent in the whole file)
</blockquote></details>

Done
___
*[bash/README.md, line 17 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-LoIT9cw4vpmvFqZJS-M:-LqDIWIi1kYnecsoIgE3:bb6un1j) ([raw file](https://github.com/oscarlab/graphene-tests/blob/4a0b75e7fe449a14ba1faeb00d1df6d70911d0b6/bash/README.md#L17)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Run` -> `Running`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2019-10-03 14:28 UTC, mkow submitted a review, later dismissed
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 11 unresolved discussions, "fixup! " found in commit messages' one-liners (waiting on @HW42 and @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-10-03 17:24 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 11 unresolved discussions (waiting on @HW42 and @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-10-03 18:06 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 9 unresolved discussions (waiting on @HW42)



<!-- Sent from Reviewable.io -->

2019-10-10 20:30 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 9 unresolved discussions (waiting on @HW42)



<!-- Sent from Reviewable.io -->

2019-10-10 23:25 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: all files reviewed, 9 unresolved discussions (waiting on @HW42)



<!-- Sent from Reviewable.io -->

2019-10-11 00:47 UTC, mkow approved these changes
@hw42 is on vacation, so I reviewed fixes to his comments and resolved them.

> Reviewed 1 of 1 files at r3.
> Dismissed @HW42 from 9 discussions.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39#-:-LqsEUc63_BjgA0sFkHR:b58b357)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-11 17:10 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/39)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-14 17:59 UTC, merged