Lighttpd rewrite continued
oscarlab/graphene-tests pull request #44
Opened 2019-10-01 20:40 UTC by thomasknauth

2019-10-01 20:41 UTC, thomasknauth commented
Continuation of #37.

2019-10-01 21:38 UTC, dimakuv requested changes
> Reviewed 6 of 9 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 28 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq89mua4vJx6l_EkVQ_:-Lq89mua4vJx6l_EkVQa:by0k64o) (no related file):*
Please move `html/` under `$(INSTALL_DIR)/html/`. See Nginx for example. This will simplify gitignore and make-clean and other stuff.

---
___
*[lighttpd/.gitignore, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8A0S-0gGZkKeoNpCE:-Lq8A0S-0gGZkKeoNpCF:b-dwcw5t) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/.gitignore#L1)):*
> ```ignore
> /ab.*
> ```

Is this a real file? I don't think it is produced by any script here.
___
*[lighttpd/.gitignore, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8ADB4AJ_zxy0Ft319:-Lq8ADB4AJ_zxy0Ft31A:byfghfr) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/.gitignore#L7)):*
> ```ignore
> /lighttpd.conf
> /lighttpd-*/
> /*.conf
> ```

Won't this line ignore all changes we want to make to `lighttpd-generic.conf`? Sounds unnecessary here.
___
*[lighttpd/.gitignore, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq89yQ7AHRGVcBy-Bq2:-Lq89yQ82Lfyy6NaDYU5:b-8hfrk8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/.gitignore#L9)):*
> ```ignore
> /*.conf
> /*.tar.gz
> /html
> ```

This won't be needed
___
*[lighttpd/benchmark-http.sh, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq88_i_4Rh-eciIrTjc:-Lq88_i_4Rh-eciIrTjd:bj30w63) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Since we are modifying this file, can you replace all tabs with whitespaces
___
*[lighttpd/benchmark-http.sh, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq88fFa80OeqsuoWPvC:-Lq88fFb9lLeDe0OQU-8:bh35gmp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L5)):*
> ```Shell
> ## On Ubuntu, this script requires apache2-utils for the ab binary.
> # Run like: ./benchmark-http.sh server
> # where server is the host/port running the web server
> ```

Simplify these two lines to `Run as follows: ./benchmark-http.sh host:port`
___
*[lighttpd/lighttpd.manifest.template, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq897E8-zDbVeDQovP5:-Lq897E8-zDbVeDQovP6:b-aun3u1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L29)):*
> ```
> fs.mount.lib.uri = file:$(GRAPHENEDIR)/Runtime
> 
> # Host-level libraries (/lib/x86_64-linux-gnu) required by the Python executable
> ```

Here and below: replace Python with Lighttpd
___
*[lighttpd/lighttpd.manifest.template, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AS8k6IMUmWAqdQG7:-Lq8AS8k6IMUmWAqdQG8:bb12t78) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L47)):*
> ```
> fs.mount.html.type = chroot
> fs.mount.html.path = /html
> fs.mount.html.uri = file:html
> ```

When we move `html` under install dir, this whole mount point won't be needed.
___
*[lighttpd/lighttpd.manifest.template, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AaCWAGWJS_vXMVYQ:-Lq8AaCWAGWJS_vXMVYR:b-hreuy0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L52)):*
> ```
> fs.mount.var_tmp.type = chroot
> fs.mount.var_tmp.path = /var/tmp
> fs.mount.var_tmp.uri = file:/var/tmp
> ```

What is this? Why is this needed? Either remove or make an explicit comment
___
*[lighttpd/lighttpd.manifest.template, line 57 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AhM5DexnjtK5OKKM:-Lq8AhM5DexnjtK5OKKN:b-q95hrm) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L57)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave. For SGX v1, the enclave
> # size must be specified during signing. If Python needs more virtual memory
> ```

Not Python
___
*[lighttpd/lighttpd.manifest.template, line 67 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8E-lc8fEsHRLg6L-o:-Lq8E-ld9BO5S9jp4ud_:b-eu5isd) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L67)):*
> ```
> # thread for asynchronous events. Therefore, the actual number of threads that
> # the application can create is (sgx.thread_num - 2).
> sgx.thread_num = $(THREADS)
> ```

Something doesn't add up here. Lighttpd is single-threaded, no?
___
*[lighttpd/lighttpd.manifest.template, line 87 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AwX36GUpNLqezxBQ:-Lq8AwX36GUpNLqezxBR:b-xlu81v) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L87)):*
> ```
> 
> # SGX untrusted (allowed) files / directories
> sgx.allowed_files.html = file:html
> ```

I don't like that they are allowed. In Nginx, I listed them explicitly as trusted:
```
# Nginx HTTP documents (trusted)
# We only specify those documents used in our tests/benchmarks
sgx.trusted_files.htdocs1 = file:$(INSTALL_DIR)/html/index.html
sgx.trusted_files.htdocs2 = file:$(INSTALL_DIR)/html/random/10K.1.html
```
___
*[lighttpd/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8BCg1E0N2vPLwcfTN:-Lq8BCg278X92Y9CKcxN:btlabn5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L1)):*
> ```Makefile
> # Build the manifest for Lighttpd:
> ```

`Building`
___
*[lighttpd/Makefile, line 16 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8BMF46KBUZIiggrgb:-Lq8BMF46KBUZIiggrgc:b-pmuzip) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L16)):*
> ```Makefile
> 
> # Installation location of Lighttpd
> INSTALL_DIR ?= install
> ```

Not that simple. Please see how it's implemented in Nginx. (Otherwise nested makefiles result in incorrect absolute paths.)
___
*[lighttpd/Makefile, line 30 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8BhUlBclNhJBs0C4d:-Lq8BhUlBclNhJBs0C4e:b3pkwpw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L30)):*
> ```Makefile
> PORT ?= 8001
> THREADS ?= 4
> GRAPHENE_THREADS = 6
> ```

This sounds wrong. Should be dependent on `THREADS + 2`.
___
*[lighttpd/Makefile, line 45 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8CjP-2UHj9F_oRbSi:-Lq8CjP-2UHj9F_oRbSj:b-4j6w4y) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L45)):*
> ```Makefile
> LDD  = ldd
> AWK  = awk
> RM   = rm
> ```

Pretty sure `RM` is already defined in Makefiles
___
*[lighttpd/Makefile, line 82 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8C1Ht41XuMdXn_do9:-Lq8C1Ht41XuMdXn_doA:b-gkajgh) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L82)):*
> ```Makefile
> # The dependencies are generated from the ld [...]

2019-10-01 22:45 UTC, mkow requested changes
> Reviewed 6 of 9 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 40 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @thomasknauth)

___
*[lighttpd/benchmark-http.sh, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8GamZ-eiveBs6ueVQ:-Lq8Gam_1iIz5OfGg1pq:bcce0g2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L32)):*
> ```Shell
> 		THROUGHPUT=$(grep -m1 "Requests per second:" OUTPUT | awk '{ print $4 }')
> 		LATENCY=$(grep -m1 "Time per request:" OUTPUT | awk '{ print $4 }')
>         FAILED=$(grep -m1 "Failed requests:" OUTPUT | awk '{print $3 }')
> ```

This will cause conflicts after merging #43.
___
*[lighttpd/lighttpd.manifest.template, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8Qc4YAnZwcdT8NX1w:-Lq8Qc4ZDXLzQnne_x5R:bxt80n2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L34)):*
> ```
> fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu
> 
> # Host-level directory (/usr) required by the Python executable
> ```

python?
___
*[lighttpd/Makefile, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8RPiMDxfEzmn8iuKn:-Lq8RPiMDxfEzmn8iuKo:boxozu0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L6)):*
> ```Makefile
> # - make DEBUG=1
> # - make SGX=1
> # - make SGX=1 DEBUG=1
> ```

Now this looks like a series of commands which should be executed one-by-one.
___
*[lighttpd/Makefile, line 18 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8RwAxEoer77i4Lg8l:-Lq8RwAxEoer77i4Lg8m:bjhur7n) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L18)):*
> ```Makefile
> INSTALL_DIR ?= install
> 
> # Source code directory and checksum of Lighttpd
> ```

`checksum` -> `hash`
___
*[lighttpd/Makefile, line 22 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8S-5JAUtFm6KihcRo:-Lq8S-5JAUtFm6KihcRp:b-u8ds2q) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L22)):*
> ```Makefile
> LIGHTTPD_CHECKSUM ?= 5151d38cb7c4c40effa13710e77ebdbef899f945b062cf32befc02d128ac424c
> 
> # Mirros for downloading the Lighttpd source code
> ```

`Mirros` -> `Mirrors`
hmm, seems you copied from some old version of one of the other PRs? I remember commenting about this typo some time ago. Could you find it and check all other fixes pointed out in the meantime, and apply them here?
___
*[lighttpd/Makefile, line 45 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8CjP-2UHj9F_oRbSi:-Lq8Sie-AcPPWO7O-bsU:bd77neg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Pretty sure `RM` is already defined in Makefiles
</blockquote></details>

yup, it is defined as `rm -f` by default. please drop it from here and remove `-f` form all the invocations
___
*[lighttpd/Makefile, line 171 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8UAkx-k-mTdTx6aGv:-Lq8UAkx-k-mTdTx6aGw:b9cjp5c) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L171)):*
> ```Makefile
> 	@echo "ssl.engine = \"enable\""                         >> $@
> 	@echo "ssl.pemfile = \"server.pem\""                    >> $@
> 	@echo "ssl.cipher-list = \"ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA\""	>> $@
> ```

Do we need to list all of them here?
___
*[lighttpd/Makefile, line 215 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8UaAM96z-SOmhHw0P:-Lq8UaAM96z-SOmhHw0Q:b-16ek27) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L215)):*
> ```Makefile
> #     Start the Lighttpd server natively in the foreground (using the Worker MPM)
> #
> # - make start-graphene-multithreaded-server:
> ```

same as Dmitrii pointed above
___
*[lighttpd/README.md, line 3 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8JtwM8Vu5B1a7J2sJ:-Lq8JtwM8Vu5B1a7J2sK:bqkewyw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/README.md#L3)):*
> ```Markdown
> # Lighttpd example
> 
> This directory contains an example for running Lighttpd (version 1.4.54)
> ```

Could we drop the version number from here? It won't stay up-to-date for long. The users can check the version looking at the Makefile or downloaded files.
___
*[lighttpd/README.md, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8NJWK9TlrReJ0U8Bn:-Lq8NJWK9TlrReJ0U8Bo:bac9iwb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/README.md#L27)):*
> ```Markdown
> 
> First, start the Lighttpd server. By default, the installed Lighttpd server will use the Prefork
> multi-processing module (MPM). Execute one of the following commands to start lighttpd either natively
> ```

Please wrap this whole file on 100 chars
___
*[lighttpd/README.md, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8OAaq2CYFApg7A5Er:-Lq8OAaq2CYFApg7A5Es:b-5j2ikw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/README.md#L27)):*
> ```Markdown
> 
> First, start the Lighttpd server. By default, the installed Lighttpd server will use the Prefork
> multi-processing module (MPM). Execute one of the following commands to start lighttpd either natively
> ```

`lighttpd` -> `Lighttpd`
___
*[lighttpd/README.md, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8Oog18Bv4FvfHZ4LA:-Lq8Oog18Bv4FvfHZ4LB:b-marp9o) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/README.md#L60)):*
> ```Markdown
> 
> * `make clean`: Clean up manifest, signature, and token files.
> * `make distclean`: Clean up the source code and the installation directory.
> ```

`source code` -> `Lighttpd source code`
___
*[lighttpd/README.md, line 60 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8OtHg4znJrJA-ruEl:-Lq8OtHg4znJrJA-ruEm:bbqupes) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/README.md#L60)):*
> ```Markdown
> 
> * `make clean`: Clean up manifest, signature, and token files.
> * `make distclean`: Clean up the source code and the installation directory.
> ```

`Clean up` -> `Delete` (2x)


<!-- Sent from Reviewable.io -->

2019-10-02 17:07 UTC, thomasknauth reviewed
Hopefully addressed all your comments and didn't mess up anywhere.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-:-LqCR9GJ6k35Bmac8Kg4:bbg2ni5)* status: 6 of 12 files reviewed, 40 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @thomasknauth)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq89mua4vJx6l_EkVQ_:-LqC9jnt5o-vtpoVSIHf:b-896fix) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please move `html/` under `$(INSTALL_DIR)/html/`. See Nginx for example. This will simplify gitignore and make-clean and other stuff.
</blockquote></details>

Done.

---
___
*[lighttpd/.gitignore, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8A0S-0gGZkKeoNpCE:-Lq8QqNxDa0yt24Cj10z:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/.gitignore#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Is this a real file? I don't think it is produced by any script here.
</blockquote></details>

Done.
___
*[lighttpd/.gitignore, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8ADB4AJ_zxy0Ft319:-Lq8ROWy8rcy1-z6ZQJR:bss4a2b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/.gitignore#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Won't this line ignore all changes we want to make to `lighttpd-generic.conf`? Sounds unnecessary here.
</blockquote></details>

Removed.
___
*[lighttpd/.gitignore, line 9 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq89yQ7AHRGVcBy-Bq2:-Lq8RZ-q77sjMKktP1dq:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/.gitignore#L9)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This won't be needed
</blockquote></details>

Done.
___
*[lighttpd/benchmark-http.sh, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq88_i_4Rh-eciIrTjc:-Lq8RhN2DHuLOefZZ_q-:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Since we are modifying this file, can you replace all tabs with whitespaces
</blockquote></details>

Done.
___
*[lighttpd/benchmark-http.sh, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq88fFa80OeqsuoWPvC:-LqC9l-V6HjzAKqEkT-Z:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Simplify these two lines to `Run as follows: ./benchmark-http.sh host:port`
</blockquote></details>

Done.
___
*[lighttpd/benchmark-http.sh, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8GamZ-eiveBs6ueVQ:-LqCA1Fp7x5IYx61_KCn:b5mpc6h) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This will cause conflicts after merging #43.
</blockquote></details>

When merging #43 the individual files must be removed anyhow, no?
___
*[lighttpd/lighttpd.manifest.template, line 29 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq897E8-zDbVeDQovP5:-Lq8ZqWBCIH4LgoHBPEf:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L29)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Here and below: replace Python with Lighttpd
</blockquote></details>

Done.
___
*[lighttpd/lighttpd.manifest.template, line 34 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8Qc4YAnZwcdT8NX1w:-LqCASXg7d7vgpl_5HNa:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L34)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

python?
</blockquote></details>

Done.
___
*[lighttpd/lighttpd.manifest.template, line 47 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AS8k6IMUmWAqdQG7:-Lq8ZrOk9UZ5EoiJpH18:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L47)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

When we move `html` under install dir, this whole mount point won't be needed.
</blockquote></details>

Done.
___
*[lighttpd/lighttpd.manifest.template, line 52 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AaCWAGWJS_vXMVYQ:-Lq8_bUpEIarAwkwTk8I:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L52)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this? Why is this needed? Either remove or make an explicit comment
</blockquote></details>

Done.
___
*[lighttpd/lighttpd.manifest.template, line 57 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AhM5DexnjtK5OKKM:-Lq8_ctaAAUic-vlNrl3:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L57)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Not Python
</blockquote></details>

Done.
___
*[lighttpd/lighttpd.manifest.template, line 67 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8E-lc8fEsHRLg6L-o:-LqCAaAFBjJq-9A7ySeQ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L67)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Something doesn't add up here. Lighttpd is single-threaded, no?
</blockquote></details>

Done.
___
*[lighttpd/lighttpd.manifest.template, line 87 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AwX36GUpNLqezxBQ:-Lq8avLG95BW1uhl0PGV:b-rpdweg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L87)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I don't like that they are allowed. In Nginx, I listed them explicitly as trusted:
```
# Nginx HTTP documents (trusted)
# We only specify those documents used in our tests/benchmarks
sgx.trusted_files.htdocs1 = file:$(INSTALL_DIR)/html/index.html
sgx.trusted_files.htdocs2 = file:$(INSTALL_DIR)/html/random/10K.1.html
```
</blockquote></details>

Dunno. There are many more files in the html directory which will result in a 404 in your model. I prefer just allowing the entire directory.
___
*[lighttpd/Makefile, line 6 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8RPiMDxfEzmn8iuKn:-LqC6cqx2hjiARY_Q3iM:bratys0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now this looks like a series of commands which should be executed one-by-one.
</blockquo [...]

2019-10-02 18:17 UTC, mkow requested changes
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 33 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @thomasknauth)

___
*[lighttpd/benchmark-http.sh, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8GamZ-eiveBs6ueVQ:-LqCa2Ai82erKQeM95DP:b-4f6kyj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L32)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

When merging #43 the individual files must be removed anyhow, no?
</blockquote></details>

#43 was merged. You'll just need to reapply your changes to the file in common_tools after rebasing.
___
*[lighttpd/Makefile, line 18 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8RwAxEoer77i4Lg8l:-LqCasBs8LQPaN1YJ7ED:b-6i4kif) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L18)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

A little too pedantic maybe? The variable is also called *_CHECKSUM. Same in Nginx's makefile. I think the two terms are mostly used as synonyms, no?
</blockquote></details>

Nah, checksum is used for a non-cryptographic digest used for random error detection, hashes are used also for detecting malicious alterations of data. I don't like confusing those two names, because they are quite different and protect against different things ;)
___
*[lighttpd/Makefile, line 45 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8CjP-2UHj9F_oRbSi:-LqCd22Z1LkMhajo3FoG:b-u8gya8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L45)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Wasn't the idea to decouple the app's Makefiles from the main repo's Makefiles? Why would this matter in this case?
</blockquote></details>

We mean that $(RM) is defined by default in Make. See https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html.
___
*[lighttpd/Makefile, line 147 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8CtcS52iaGiku5sBH:-LqCeDBw6t53oxrufDnn:byjgcnj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L147)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Rather $(RM) -r, now?
</blockquote></details>

Not just `$(RM) $@`?
___
*[lighttpd/Makefile, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqCcy1C0WVUBMwU55s9:-LqCcy1DEITDUojGtq62:b7goxw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/Makefile#L14)):*
> ```Makefile
> 	https://download.lighttpd.net/lighttpd/releases-1.4.x/
> 
> # Host and port lighttpd server will listen for requests
> ```

`Host and port lighttpd` -> `Host and port on which lighttpd`
___
*[lighttpd/Makefile, line 136 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqCeIht7-jLkGAYRiNj:-LqCeIht7-jLkGAYRiNk:b-7uy96p) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/Makefile#L136)):*
> ```Makefile
> 
> lighttpd.conf:
> 	@$(RM) -r $@
> ```

`-r`?
___
*[lighttpd/README.md, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8NJWK9TlrReJ0U8Bn:-LqCfWfqDPeipg7cuSTO:byaervm) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/README.md#L27)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Thanks for putting a .dir-locals.el into the root directory!
</blockquote></details>

Hmmm, was this a sarcasm (that it's broken somehow) or has it really helped? ;)
___
*[lighttpd/README.md, line 27 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8OAaq2CYFApg7A5Er:-LqCfwz61SY1j-0cAene:b-6frcwm) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/README.md#L27)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Looking at the lighttpd website, it is always written in all lowercase. I am sticking to their way of writing it.
</blockquote></details>

Ah, right. Thanks for not applying my suggestions blindly! :)
___
*[lighttpd/README.md, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqCf4cHEPkqGDnGzkp4:-LqCf4cHEPkqGDnGzkp5:b-jm37qr) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/README.md#L4)):*
> ```
> The was tested on Ubuntu 16.04.
> ```
Something went wrong here :)


<!-- Sent from Reviewable.io -->

2019-10-02 20:20 UTC, dimakuv requested changes
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @mkow, and @thomasknauth)

___
*[lighttpd/benchmark-http.sh, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8GamZ-eiveBs6ueVQ:-LqD5dn00aOrSSXZVoES:btno2dw) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L32)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

#43 was merged. You'll just need to reapply your changes to the file in common_tools after rebasing.
</blockquote></details>

The rebaser (me, I guess) will do it as part of the final merge.
___
*[lighttpd/lighttpd.manifest.template, line 87 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8AwX36GUpNLqezxBQ:-LqD5uLmA-qX3fNJTDDW:b-otavo2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/lighttpd.manifest.template#L87)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

Dunno. There are many more files in the html directory which will result in a 404 in your model. I prefer just allowing the entire directory.
</blockquote></details>

OK, I have no hard requirement on this.
___
*[lighttpd/Makefile, line 141 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqD70W7-FheZgek-duE:-LqD70W8Dv0QX2AuMlxi:b-uvx2a) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/Makefile#L141)):*
> ```Makefile
> 
> # Generate variously-sized HTML files in $(RANDOM_DIR)
> RANDOM_DIR = install/html/random
> ```

Replace `install/` with `$(INSTALL_DIR)/`
___
*[lighttpd/README.md, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqD7EXo9JNPKzzm8_TM:-LqD7EXo9JNPKzzm8_TN:b-dx6a8d) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/README.md#L3)):*
> ```Markdown
> # Lighttpd Example
> 
> This directory contains an example for running Lighttpd in Graphene, including the Makefile and a
> ```

`Lighttpd` -> should be small case `lighttpd`


<!-- Sent from Reviewable.io -->

2019-10-04 22:33 UTC, thomasknauth reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: 10 of 12 files reviewed, 10 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @mkow)

___
*[lighttpd/benchmark-http.sh, line 32 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8GamZ-eiveBs6ueVQ:-LqNkBW-C3p0O6B6Js64:b-9is1r5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/benchmark-http.sh#L32)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

The rebaser (me, I guess) will do it as part of the final merge.
</blockquote></details>

You can always just ignore the changes. Maybe the script should error out on Failed or Non-2xx responses anyway?
___
*[lighttpd/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8BCg1E0N2vPLwcfTN:-LqNq664EYRDrFnh56DM:b3kre) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Building`
</blockquote></details>

?
___
*[lighttpd/Makefile, line 18 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8RwAxEoer77i4Lg8l:-LqNqMfCBSn7j5Q3-trD:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L18)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Nah, checksum is used for a non-cryptographic digest used for random error detection, hashes are used also for detecting malicious alterations of data. I don't like confusing those two names, because they are quite different and protect against different things ;)
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 45 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8CjP-2UHj9F_oRbSi:-LqNqgAm1T0HjuQzQ1rc:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L45)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

We mean that $(RM) is defined by default in Make. See https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html.
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 14 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqCcy1C0WVUBMwU55s9:-LqNqd0a5ckiDEUujbPi:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/Makefile#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`Host and port lighttpd` -> `Host and port on which lighttpd`
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 136 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqCeIht7-jLkGAYRiNj:-LqNr5410Mn9iMsuxPTk:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/Makefile#L136)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`-r`?
</blockquote></details>

Done.
___
*[lighttpd/Makefile, line 141 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqD70W7-FheZgek-duE:-LqNrw9r6EHlhzGXDVfZ:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/Makefile#L141)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Replace `install/` with `$(INSTALL_DIR)/`
</blockquote></details>

Done.
___
*[lighttpd/README.md, line 3 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqD7EXo9JNPKzzm8_TM:-LqNrMM-AT424LtfiixE:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/README.md#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`Lighttpd` -> should be small case `lighttpd`
</blockquote></details>

Done.
___
*[lighttpd/README.md, line 4 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-LqCf4cHEPkqGDnGzkp4:-LqNrqSAAhOY6fHC6owO:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/1d57fa7e5dbcf7627cb82d4e4b4ff00523bdcf86/lighttpd/README.md#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> ```
> The was tested on Ubuntu 16.04.
> ```
Something went wrong here :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-05 01:03 UTC, dimakuv approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 6 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)

___
*[lighttpd/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8BCg1E0N2vPLwcfTN:-LqOR084C0Lr4dOe3qEd:b-lfbka8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L1)):*
<details><summary><i>Previously, thomasknauth (Thomas Knauth) wrote…</i></summary><blockquote>

?
</blockquote></details>

Ignore this, I'm not sure what it was.


<!-- Sent from Reviewable.io -->

2019-10-06 23:33 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[lighttpd/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8BCg1E0N2vPLwcfTN:-LqYP9T6D5Nx-Dv0iZ2X:byuj5de) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Ignore this, I'm not sure what it was.
</blockquote></details>

@dimakuv Click on the red corner in the right top of this thread. This comment was added on some older revision on a line which were somehow lost in current revision.
The corner is red is such situations.


<!-- Sent from Reviewable.io -->

2019-10-06 23:48 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 1 unresolved discussion (waiting on @mkow)

___
*[lighttpd/Makefile, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/44#-Lq8BCg1E0N2vPLwcfTN:-LqYTNp4C0qnFI31L3M2:bste113) ([raw file](https://github.com/oscarlab/graphene-tests/blob/8728d3e0f64e4728e05572a6b948f3824f41aad5/lighttpd/Makefile#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@dimakuv Click on the red corner in the right top of this thread. This comment was added on some older revision on a line which were somehow lost in current revision.
The corner is red is such situations.
</blockquote></details>

Good to know. Clicked on the red corner.


<!-- Sent from Reviewable.io -->

2019-10-07 21:47 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2019-10-07 23:40 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2019-10-08 00:09 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2019-10-08 11:54 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 3 files at r5, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-08 20:50 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-10-08 21:26 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-08 21:33 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-10-08 21:37 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/44)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-08 22:45 UTC, merged