Disable ltp's clone02 for now.
oscarlab/graphene-tests pull request #46
Opened 2019-10-04 02:30 UTC by thomasknauth

clone02 uses an esoteric combination of clone() flags (CLONE_VM without either CLONE_THREAD or CLONE_VFORK) which only worked by accident so far.

Related to [#1034](https://github.com/oscarlab/graphene/pull/1034) and an upcoming PR on Graphene to filter clone() flags accordingly.

2019-10-04 07:22 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/46)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @thomasknauth)

___
*[ltp/FLAKY, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/46#-LqKdTim9R1yAeMDD8qt:-LqKdTim9R1yAeMDD8qu:b-vo0ool) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e7aaf44efc7ecf4ec7cdd54b73471344b8213696/ltp/FLAKY#L7)):*
> ```
> 
> clone02 - Invokes clone with CLONE_VM but without either of CLONE_THREAD or CLONE_VFORK, i.e., a
> process sharing its parents address space. Graphene doesn't support this exotic model. Bug exposed by #1034.
> ```

`parents` -> `parent's`


<!-- Sent from Reviewable.io -->

2019-10-04 17:04 UTC, mkow submitted a review, later dismissed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/46)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @thomasknauth)



<!-- Sent from Reviewable.io -->

2019-10-05 00:54 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/46)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2019-10-07 17:48 UTC, dimakuv approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/46)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-10-07 17:54 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/46)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2019-10-07 20:34 UTC, omeg approved these changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/46)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-07 20:40 UTC, merged