[Nginx] Add test targets to Makefile for Jenkins
oscarlab/graphene-tests pull request #55
Opened 2019-11-27 19:05 UTC by dimakuv

We are missing Nginx from Jenkins tests for no good reason. This PR adds test targets to Nginx, and the corresponding PR in the main Graphene repo adds it to all Jenkins pipelines.

2019-11-27 20:30 UTC, yamahata submitted a review, later dismissed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-11-28 00:17 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/55)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[nginx/README.md, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/55#-LujMYYJ3u7LzsUbvNmZ:-LujMYYJ3u7LzsUbvNm_:bigk3gx) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3e7993ada209fcd56ce101a6ec8f8a6de933e8d3/nginx/README.md#L46)):*
> ```Markdown
> make start-native-server
> make start-graphene-server
> SGX=1 make start-graphene-server
> ```

I'd prefer `make SGX=1 start-graphene-server` as we have in other places (I think in this case it will still work?)


<!-- Sent from Reviewable.io -->

2019-11-28 13:41 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/55)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow and @yamahata)

___
*[nginx/README.md, line 46 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/55#-LujMYYJ3u7LzsUbvNmZ:-LumEZy452_qUmVvFX7f:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3e7993ada209fcd56ce101a6ec8f8a6de933e8d3/nginx/README.md#L46)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

I'd prefer `make SGX=1 start-graphene-server` as we have in other places (I think in this case it will still work?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-11-28 22:50 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-11-29 02:00 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/55)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2019-11-29 04:16 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/55)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-11-29 07:40 UTC, merged