[Bash] Add trusted libraries required for Ubuntu 18.04
oscarlab/graphene-tests pull request #57
Opened 2019-11-28 02:04 UTC by dimakuv

Adds a couple missing libraries required for Ubuntu 18.04. This is to make Linux-SGX pipeline work on Ubuntu 18.04.

2019-11-29 01:18 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/57)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[bash/Makefile, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/57#-Luois6b-0Z1rQvl7R_N:-Luois6c8vkRI5SQOpvr:b-18oy84) ([raw file](https://github.com/oscarlab/graphene-tests/blob/aa457a62b0bfb0bee4bafe6729b867652c9d4fa0/bash/Makefile#L40)):*
> ```Makefile
> # from the ldd results. This list also contains some runtime deps of Bash.
> GLIBC_DEPS = linux-vdso /lib64/ld-linux-x86-64 libc libm librt libdl libutil libpthread \
> 			 libselinux libpcre libacl libattr
> ```

Please use spaces for wrapping lines, different people have different tab sizes. See e.g. how GitHub renders this file now ;)


<!-- Sent from Reviewable.io -->

2019-11-29 21:56 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/57)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[bash/Makefile, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/57#-Luois6b-0Z1rQvl7R_N:-Lut9YwkCeJKxpBrQ4zq:b7vi81q) ([raw file](https://github.com/oscarlab/graphene-tests/blob/aa457a62b0bfb0bee4bafe6729b867652c9d4fa0/bash/Makefile#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please use spaces for wrapping lines, different people have different tab sizes. See e.g. how GitHub renders this file now ;)
</blockquote></details>

Done. My auto-indent in Vim is set to tabs for Makefiles :)


<!-- Sent from Reviewable.io -->

2019-11-29 22:09 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/57)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

___
*[bash/Makefile, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/57#-Luois6b-0Z1rQvl7R_N:-LutCNc4D1LjwTzlsYkm:b66nr63) ([raw file](https://github.com/oscarlab/graphene-tests/blob/aa457a62b0bfb0bee4bafe6729b867652c9d4fa0/bash/Makefile#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Done. My auto-indent in Vim is set to tabs for Makefiles :)
</blockquote></details>

Yup, code editors rarely get this right


<!-- Sent from Reviewable.io -->

2019-12-02 03:24 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/57)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required)



<!-- Sent from Reviewable.io -->

2019-12-02 08:25 UTC, omeg approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/57)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-12-02 10:21 UTC, merged