Add nodejs example
oscarlab/graphene-tests pull request #58
Opened 2019-11-28 07:34 UTC by pangzi85480

Signed-off-by: jack.wxz <jack.wxz@alibaba-inc.com>

2019-11-29 01:41 UTC, mkow requested changes
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, 17 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @pangzi85480)

___
*[nodejs/Makefile, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuokpOU-Sb7xWwSxwVE:-LuokpOU-Sb7xWwSxwVF:b8x364f) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L10)):*
> ```Makefile
> # Use `make clean` to remove Graphene-generated files.
> #
> # Use `make distclean` to further remove the Nginx tarball, source code,
> ```

nginx?
also, this makefile doesn't have `distclean` target
___
*[nodejs/Makefile, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luokt-V41vFLZwFs_I-:-Luokt-V41vFLZwFs_I0:byme7ta) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L14)):*
> ```Makefile
> 
> THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))
> ifeq ($(THIS_DIR), ./)  # workaround Graphene issue #1044 with allowed_files
> ```

#1044 was merged long time ago ;)
___
*[nodejs/nodejs.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuolFXl6DxqX49VRq6j:-LuolFXl6DxqX49VRq6k:b-n1sdzq) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L1)):*
> ```
> # Nginx manifest example
> ```

nginx?
___
*[nodejs/nodejs.manifest.template, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuoldIX-eA5Os3TbAJc:-LuoldIX-eA5Os3TbAJd:b-n1sdzq) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L38)):*
> ```
> 
> # Set the virtual memory size of the SGX enclave. For SGX v1, the enclave
> # size must be specified during signing. If Nginx needs more virtual memory
> ```

nginx?
___
*[nodejs/nodejs.manifest.template, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luolflt3UIa5MyKV0L4:-Luolflt3UIa5MyKV0L5:b-6vzud0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L40)):*
> ```
> # size must be specified during signing. If Nginx needs more virtual memory
> # than the enclave size, Graphene will not be able to allocate it.
> sgx.enclave_size = 2G
> ```

Do we really need 2G for this helloworld sample?
___
*[nodejs/nodejs.manifest.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuolmHG1CrFsJCo1RtI:-LuolmHG1CrFsJCo1RtJ:b-x4r6er) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L49)):*
> ```
> # the application can create is (sgx.thread_num - 2).
> #
> # We (somewhat arbitrarily) specify 4 threads since Nginx is single-threaded.
> ```

nginx? also, the comment says 4 but the config says 8
___
*[nodejs/nodejs.manifest.template, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuomLI9BWS1Ay5Lkqje:-LuomLI9BWS1Ay5Lkqjf:b-56mywk) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L73)):*
> ```
> sgx.trusted_files.libhttp_parser = file:/usr/lib/x86_64-linux-gnu/libhttp_parser.so.2.7.1
> 
> # jsscript (trusted)
> ```

javascriptscript? ;)
___
*[nodejs/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luomt1k8fcQ1pc563Rp:-Luomt1k8fcQ1pc563Rq:b-upkyz4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L1)):*
> ```Markdown
> # nodejs
> ```

Official name is `Node.js`, not `nodejs`
___
*[nodejs/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuomtlS7sWJcTJhwuRY:-LuomtlS7sWJcTJhwuRZ:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L3)):*
> ```Markdown
> # nodejs
> 
> This directory contains the Makefile and the template manifest for the nodejs
> ```

ditto
___
*[nodejs/README.md, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuomxCk9qaKqu-SvCz0:-LuomxCk9qaKqu-SvCz1:b6xqg7o) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L4)):*
> ```Markdown
> 
> This directory contains the Makefile and the template manifest for the nodejs
> (apt-get install nodejs, version v8.10.0). This
> ```

This comment in parenthesis is weird. How the users should read and interpret it?
___
*[nodejs/README.md, line 8 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuonKO0C75qQwienYgO:-LuonKO0C75qQwienYgP:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L8)):*
> ```Markdown
> 
> The Makefile and the template manifest contain extensive comments. Please review
> them to understand the requirements for nodejs running under Graphene-SGX.
> ```

ditto
___
*[nodejs/README.md, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuonLNpBuGws5Mhae3g:-LuonLNpBuGws5Mhae3h:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L10)):*
> ```Markdown
> them to understand the requirements for nodejs running under Graphene-SGX.
> 
> We install nodejs from apt.
> ```

ditto
___
*[nodejs/README.md, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuonMgq4x4QM_j5hb8r:-LuonMgq4x4QM_j5hb8s:bhfqwes) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L10)):*
> ```Markdown
> them to understand the requirements for nodejs running under Graphene-SGX.
> 
> We install nodejs from apt.
> ```

This sounds weird (is this a recommendation for the user, or description how Graphene maintainers install Node.js?), please reword it. Also, `apt` is Ubuntu/Debian-specific, this first sentence doesn't have to be distro-specific.
___
*[nodejs/README.md, line 11 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luon_l37N3Mb5DXYCGG:-Luon_l37N3Mb5DXYCGH:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L11)):*
> ```Markdown
> 
> We install nodejs from apt.
> On Ubuntu 18.04, Please run the following command to install nodejs:
> ```

ditto
___
*[nodejs/README.md, line 19 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luonp3u1ixk1lByND6i:-Luonp3u1ixk1lByND6j:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L19)):*
> ```Markdown
> 
> ```sh
> # build nodejs and the final manifest
> ```

ditto
___
*[nodejs/README.md, line 22 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuonqJG2ls5HA0WFtOO:-LuonqJG2ls5HA0WFtOP:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L22)):*
> ```Markdown
> make SGX=1
> 
> # run nodejs in non-SGX Graphene
> ```

ditto
___
*[nodejs/README.md, line 25 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuonrAbApfYip-3Vyqm:-LuonrAbApfYip-3Vyqn:b-7ropln) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L25)):*
> ```Markdown
> ./pal_loader nodejs.manifest helloworld.js
> 
> # run nodejs in Graphene-SGX
> ```

ditto


<!-- Sent from Reviewable.io -->

2019-11-29 22:07 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @mkow and @pangzi85480)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutB-T--YsnVcCADRXM:-LutB-T--YsnVcCADRXN:b99lpdv) (no related file):*
A general comment: you took a rather old Nginx example as a baseline. Please look at https://github.com/oscarlab/graphene-tests/pull/56 for a newer, better example of how to write Makefiles and manifests. I also put comments inline.

---
___
*[nodejs/Makefile, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luokt-V41vFLZwFs_I-:-LutAJAC3XRHqa2UOvQa:brxaej) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L14)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

#1044 was merged long time ago ;)
</blockquote></details>

+1, this is outdated. Just remove the whole ifeq (see example in https://github.com/oscarlab/graphene-tests/pull/56/files#diff-566f2050ed531ce1d98a2cd6794e5137).
___
*[nodejs/Makefile, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutAew2AJvob_mT1N-x:-LutAew2AJvob_mT1N-y:b-d63zcg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L43)):*
> ```Makefile
> 	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
> 		-libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
> 		-key $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem \
> ```

In newer PRs, we prefer to use a special variable GRAPHENEKEY instead of hard-coding `enclave-key.pem`. Please see example of https://github.com/oscarlab/graphene-tests/pull/56/files#diff-566f2050ed531ce1d98a2cd6794e5137.
___
*[nodejs/Makefile, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutAtY73rMjJsnZ-HVg:-LutAtY73rMjJsnZ-HVh:bjyyhri) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L50)):*
> ```Makefile
> nodejs.token: nodejs.sig
> 	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
> 		-output nodejs.token -sig nodejs.sig
> ```

It's better to use `-output $@ -sig $^`
___
*[nodejs/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutAytC-tCU0y88sJj8:-LutAytC-tCU0y88sJj9:bgn382b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L58)):*
> ```Makefile
> .PHONY: clean
> clean:
> 	$(RM) *.manifest *.manifest.sgx *.token *.sig pal_loader
> ```

Please add distclean
___
*[nodejs/nodejs.manifest.template, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutBEm741pL0oI9AfUs:-LutBEm741pL0oI9AfUt:bixrnh5) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L5)):*
> ```
> # This manifest was prepared and tested on Ubuntu 18.04.
> #
> # node must be run with the pal_loader:
> ```

`node` -> `Node.js`
___
*[nodejs/nodejs.manifest.template, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutBU100mXpCJE6WVmE:-LutBU100mXpCJE6WVmF:b-cps6we) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L18)):*
> ```
> loader.libos = libsysdb
> loader.env.LD_LIBRARY_PATH = /lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu
> loader.env.PATH = /usr/local/bin:/usr/bin:/bin
> ```

Feels like these are too many directories :) I believe just `/usr/bin` should be enough?
___
*[nodejs/nodejs.manifest.template, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luolflt3UIa5MyKV0L4:-LutBf-u7zfsd5y3jAWy:b-pjiver) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L40)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Do we really need 2G for this helloworld sample?
</blockquote></details>

+1 Do you know the reason why Node.js wants at least 2GB? If it is indeed so, could you put some comment on the reason?


<!-- Sent from Reviewable.io -->

2019-12-02 14:13 UTC, pangzi85480 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: 1 of 5 files reviewed, 23 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @mkow, and @yamahata)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutB-T--YsnVcCADRXM:-Lv5wNnHEgAV_olGRb5Q:bpclugb) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

A general comment: you took a rather old Nginx example as a baseline. Please look at https://github.com/oscarlab/graphene-tests/pull/56 for a newer, better example of how to write Makefiles and manifests. I also put comments inline.
</blockquote></details>

I re-written it with reference to curl, please review it again, thank you.
@dimakuv @mkow @yamahata

---
___
*[nodejs/Makefile, line 10 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuokpOU-Sb7xWwSxwVE:-Lv5wxnREw6-pcJNStu8:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L10)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nginx?
also, this makefile doesn't have `distclean` target
</blockquote></details>

Done.
___
*[nodejs/Makefile, line 14 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luokt-V41vFLZwFs_I-:-Lv5wyefAiqg6rkynNiR:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L14)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1, this is outdated. Just remove the whole ifeq (see example in https://github.com/oscarlab/graphene-tests/pull/56/files#diff-566f2050ed531ce1d98a2cd6794e5137).
</blockquote></details>

Done.
___
*[nodejs/Makefile, line 43 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutAew2AJvob_mT1N-x:-Lv5wzyo7T13T8VaInJ2:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L43)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

In newer PRs, we prefer to use a special variable GRAPHENEKEY instead of hard-coding `enclave-key.pem`. Please see example of https://github.com/oscarlab/graphene-tests/pull/56/files#diff-566f2050ed531ce1d98a2cd6794e5137.
</blockquote></details>

Done.
___
*[nodejs/Makefile, line 50 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutAtY73rMjJsnZ-HVg:-Lv5x-lj3MOj4kIiH9Pz:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L50)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

It's better to use `-output $@ -sig $^`
</blockquote></details>

Done.
___
*[nodejs/Makefile, line 58 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutAytC-tCU0y88sJj8:-Lv5x2kL6ejOpKXu-xer:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/Makefile#L58)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please add distclean
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuolFXl6DxqX49VRq6j:-Lv5x3eQ2lGLSuJt7gHO:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nginx?
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 5 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutBEm741pL0oI9AfUs:-Lv5x6gg5GAT_bVy1LdY:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

`node` -> `Node.js`
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 18 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LutBU100mXpCJE6WVmE:-Lv5x8JD5ikLUWgBTpGD:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L18)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Feels like these are too many directories :) I believe just `/usr/bin` should be enough?
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 38 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuoldIX-eA5Os3TbAJc:-Lv5x9HH8GAqbzJXER-l:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L38)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nginx?
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luolflt3UIa5MyKV0L4:-Lv5xDt_EgfoST3BaK8m:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L40)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

+1 Do you know the reason why Node.js wants at least 2GB? If it is indeed so, could you put some comment on the reason?
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 49 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuolmHG1CrFsJCo1RtI:-Lv5xEcsEtIRUXPolb4H:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L49)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

nginx? also, the comment says 4 but the config says 8
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 73 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuomLI9BWS1Ay5Lkqje:-Lv5xFWi1ANcL14PlnIa:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L73)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

javascriptscript? ;)
</blockquote></details>

Done.
___
*[nodejs/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luomt1k8fcQ1pc563Rp:-Lv5xGbC--X3iZFOq43z:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Official name is `Node.js`, not `nodejs`
</blockquote></details>

Done.
___
*[nodejs/README.md, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuomtlS7sWJcTJhwuRY:-Lv5xH3I24QhdBegdg-c:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L3)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[nodejs/README.md, line 4 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-LuomxCk9qaKqu-SvCz0:-Lv5xHbn43Y3F-p_ZpTX:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/README.md#L4)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This comment in parenthesis is weird. Ho [...]

2019-12-02 19:34 UTC, dimakuv requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, 19 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow and @pangzi85480)

___
*[nodejs.manifest.template, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Lv75d8S1X7AZ-rOwtk5:-Lv75d8S1X7AZ-rOwtk6:b-m0n538) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9501e0f53e7d31d875de37eb506c58fd227a788c/nodejs.manifest.template#L1)):*
> ```
> # Nodejs manifest file example
> ```

Why is this file here? It looks like you accidentally added it. Please remove the file.
___
*[nodejs/nodejs.manifest.template, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Lv75NPw2riTlp1HO6pF:-Lv75NPxCrgzBvZHcxXE:b-t1kolb) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9501e0f53e7d31d875de37eb506c58fd227a788c/nodejs/nodejs.manifest.template#L10)):*
> ```
> 
> # LibOS layer library of Graphene. There is currently only one implementation,
> # so it is always set to libsysdb.so. 
> ```

Please remove trailing whitespaces. On this line, you have one space.


<!-- Sent from Reviewable.io -->

2019-12-02 21:23 UTC, mkow requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @pangzi85480)

___
*[nodejs/nodejs.manifest.template, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luolflt3UIa5MyKV0L4:-Lv7TyTX4Ou2k8XvmgEj:b-5rksl7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L40)):*
<details><summary><i>Previously, pangzi85480 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is still quite a lot and will take considerable amount of time to load under SGX. Have you checked that it's really required to use 1GB for this example?
___
*[nodejs/nodejs.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Lv7T5E386ei0x__gN3O:-Lv7T5E46a8RXMlfRvYG:b-306pin) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9501e0f53e7d31d875de37eb506c58fd227a788c/nodejs/nodejs.manifest.template#L7)):*
> ```
> # Executable to load into Graphene and run.
> loader.exec = file:$(NODEJS_DIR)nodejs
> loader.execname = file:Node.js
> ```

This option is what will be passed in `argv[0]` to the binary, I don't think original Node.js passes this thing, I'd rather expect `nodejs` or `node`? Is specifying this in the manifest required?


<!-- Sent from Reviewable.io -->

2019-12-03 02:47 UTC, pangzi85480 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: 4 of 5 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[nodejs.manifest.template, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Lv75d8S1X7AZ-rOwtk5:-Lv8Yo7h2_H2S66d0tRS:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9501e0f53e7d31d875de37eb506c58fd227a788c/nodejs.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why is this file here? It looks like you accidentally added it. Please remove the file.
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luolflt3UIa5MyKV0L4:-Lv8aD8u41UQOVKlaj6O:bpj5tv0) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L40)):*
> This is still quite a lot and will take considerable amount of time to load under SGX. Have you checked that it's really required to use 1GB for this example?
Yes, I have tried 256M, 512M, 1G, they are not enough.
And I ran native nodejs, running helloworld required 900MB+ virtual memory.

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                 
 50108 root      20   0  922544  24020  11712 R 100.3  0.0   0:08.42 nodejs
```
___
*[nodejs/nodejs.manifest.template, line 7 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Lv7T5E386ei0x__gN3O:-Lv8YznG87JpJSsln-YH:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9501e0f53e7d31d875de37eb506c58fd227a788c/nodejs/nodejs.manifest.template#L7)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

This option is what will be passed in `argv[0]` to the binary, I don't think original Node.js passes this thing, I'd rather expect `nodejs` or `node`? Is specifying this in the manifest required?
</blockquote></details>

Done.
___
*[nodejs/nodejs.manifest.template, line 10 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Lv75NPw2riTlp1HO6pF:-Lv8Z4lM2AXXX2QvNx7T:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9501e0f53e7d31d875de37eb506c58fd227a788c/nodejs/nodejs.manifest.template#L10)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Please remove trailing whitespaces. On this line, you have one space.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-03 11:32 UTC, dimakuv requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[nodejs.manifest.template, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Lv75d8S1X7AZ-rOwtk5:-LvAWpMMAGfYHlZ2ESFi:bysx6q9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9501e0f53e7d31d875de37eb506c58fd227a788c/nodejs.manifest.template#L1)):*
<details><summary><i>Previously, pangzi85480 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see this file.


<!-- Sent from Reviewable.io -->

2019-12-03 11:58 UTC, pangzi85480 reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: 3 of 4 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv and @mkow)

___
*[nodejs.manifest.template, line 1 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Lv75d8S1X7AZ-rOwtk5:-LvAc3N0BTSAZQXDruLK:bujdv77) ([raw file](https://github.com/oscarlab/graphene-tests/blob/9501e0f53e7d31d875de37eb506c58fd227a788c/nodejs.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

I still see this file.
</blockquote></details>

I got it wrong, I just deleted it


<!-- Sent from Reviewable.io -->

2019-12-03 12:05 UTC, dimakuv submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2019-12-03 14:04 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners

___
*[nodejs/nodejs.manifest.template, line 40 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/58#-Luolflt3UIa5MyKV0L4:-LvB3kheCJoay3yhKNez:brm1vn2) ([raw file](https://github.com/oscarlab/graphene-tests/blob/7fd46bca66043d6d7b99f86739670dc90462bde2/nodejs/nodejs.manifest.template#L40)):*
<details><summary><i>Previously, pangzi85480 wrote…</i></summary><blockquote>

> This is still quite a lot and will take considerable amount of time to load under SGX. Have you checked that it's really required to use 1GB for this example?
Yes, I have tried 256M, 512M, 1G, they are not enough.
And I ran native nodejs, running helloworld required 900MB+ virtual memory.

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                                 
 50108 root      20   0  922544  24020  11712 R 100.3  0.0   0:08.42 nodejs
```
</blockquote></details>

huh, interesting


<!-- Sent from Reviewable.io -->

2019-12-03 19:14 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 4 files at r1, 2 of 4 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-12-03 21:11 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-12-03 21:24 UTC, yamahata approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: all files reviewed, all discussions resolved, not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-12-03 21:25 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/58)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-12-03 22:14 UTC, merged