[Redis] Add "start-graphene-server" target for Jenkins and option to use select()
oscarlab/graphene-tests pull request #60
Opened 2019-12-10 23:24 UTC by dimakuv

To test Redis in Jenkins, this PR adds:
1. `make start-graphene-server` target for Jenkins, similar to web-server examples
2. `make USE_SELECT=1` option to build Redis with `select` instead of `epoll`.

2019-12-12 05:50 UTC, mkow requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/60)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

___
*[redis/Makefile, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/60#-LvsdaRO9TFsWw_Zve5f:-LvsdaRPEkZbQOAfZaYA:bl21yj3) ([raw file](https://github.com/oscarlab/graphene-tests/blob/0ca84f50481e511a03ef83959cd645213b853639/redis/Makefile#L44)):*
> ```Makefile
> # is the final executable "src/redis-server".
> 
> $(SRCDIR):
> ```

Please don't depend on directories as targets (it has some weird semantics). The previous version was written this way on purpose.


<!-- Sent from Reviewable.io -->

2019-12-12 07:00 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/60)* status: 1 of 2 files reviewed, 1 unresolved discussion, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

___
*[redis/Makefile, line 44 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/60#-LvsdaRO9TFsWw_Zve5f:-Lvsu3E93LixSoEyZjY9:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/0ca84f50481e511a03ef83959cd645213b853639/redis/Makefile#L44)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please don't depend on directories as targets (it has some weird semantics). The previous version was written this way on purpose.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-12-12 07:09 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/60)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-12-12 18:20 UTC, yamahata submitted a review, later dismissed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/60)* status: all files reviewed, all discussions resolved, "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-12-14 16:21 UTC, mkow submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/60)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2019-12-14 19:43 UTC, yamahata approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/60)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2019-12-16 11:45 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/60)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-12-16 11:49 UTC, merged