Adding Node.js express server hello world with SGX.
oscarlab/graphene-tests pull request #72
Opened 2020-02-12 20:45 UTC by eduardorn

Based on the Node.js helloworld app, I worked on getting a hello world app that uses Node.js express server.

2020-02-13 22:28 UTC, dimakuv requested changes
Thanks for this PR! I left some comments.

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-:-M0-eaNF5H-UUDu5cnEO:bf8l49i)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @eduardorn)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-dr5pE62DFAk-Z52y:-M0-dr5pE62DFAk-Z52z:b-bvp0ut) (no related file):*
You also need a `.gitignore` file here. Please see for example https://github.com/oscarlab/graphene-tests/blob/master/curl/.gitignore.

---
___
*[nodejs-express-server/helloworld.js, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-dFTl1p4taQTDGZkP:-M0-dFTl1p4taQTDGZkQ:be6iy38) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/helloworld.js#L3)):*
> ```JavaScript
> const express = require('express')
> const app = express()
> const port = 3000
> ```

Would it be possible to have port number as an argument from command line? I'd prefer not to hard code it in here.
___
*[nodejs-express-server/helloworld.js, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-d6SaCKikVoBHLmrV:-M0-d6SbBDgzSrqfM3Yj:busvtpj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/helloworld.js#L7)):*
> ```JavaScript
> app.get('/', (req, res) => res.send('Hello World!'))
> 
> app.listen(port, () => console.log(`Example app listening on port ${port}!`))
> ```

Shouldn't this app do something more than just listening on a port? How could it be tested? Could a client connect to it and send/receive some meaningful message?
___
*[nodejs-express-server/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-dZFsAMzzUFx7lqxg:-M0-dZFsAMzzUFx7lqxh:bh5qgjp) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/Makefile#L1)):*
> ```Makefile
> # List all the Node.js dependencies, besides Glibc libraries
> ```

This Makefile looks incomplete (as if the top half of the Makefile is missing). For example, `$(GLIBC_DEPS)` is missing and other variables...

Could you add the `all` target, some initial comments, etc? Similar to for example this: https://github.com/oscarlab/graphene-tests/blob/master/curl/Makefile.
___
*[nodejs-express-server/nodejs.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-e6bi2Js9R7HjZFEg:-M0-e6bi2Js9R7HjZFEh:b-b0pi3t) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/nodejs.manifest.template#L1)):*
> ```
> # Show/hide debug log of Graphene ('inline' or 'none' respectively).
> ```

Again, this file looks incomplete (as if the top half of the file is missing). For example, I don't see `loader.exec` and `loader.preload`. See https://github.com/oscarlab/graphene-tests/blob/master/curl/curl.manifest.template.
___
*[nodejs-express-server/nodejs.manifest.template, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-eJbf0OfaiXd1VMhw:-M0-eJbf0OfaiXd1VMhx:bn723ob) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/nodejs.manifest.template#L45)):*
> ```
> # JavaScript (trusted)
> sgx.trusted_files.javascript = file:helloworld.js
> sgx.allowed_files.modules = file:node_modules
> ```

What is this `node_modules`? Looks like a path with some files. Shouldn't it be added to your example?
___
*[nodejs-express-server/package.json, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-eRzU08m7LohQWBCd:-M0-eRzU08m7LohQWBCe:bb20dhk) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/package.json#L12)):*
> ```JSON
>   "email": "erodrig@us.ibm.com",
>   "license": "ISC"
> }
> ```

Shouldn't this file be listed as `sgx.trusted_files.<blabla>` in the manifest?
___
*[nodejs-express-server/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-coIk761ZMGECJ3Yd:-M0-coIk761ZMGECJ3Ye:bf9iat1) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/README.md#L1)):*
> ```Markdown
> # Running Node.js express server with Graphene SGX
> ```

Could you please wrap this whole file in 100-char limit?


<!-- Sent from Reviewable.io -->

2020-02-13 22:29 UTC, dimakuv reviewed
Please don't forget to use Reviewable to reply and please do *not* rebase your commits but instead add fixup commits.

> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-:-M0-eetC2hq-qEh5aLKr:b-vot8q5)* status: all files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @eduardorn)



<!-- Sent from Reviewable.io -->

2020-02-14 15:47 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 3 of 6 files reviewed, 8 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv and @eduardorn)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-dr5pE62DFAk-Z52y:-M03NWK38cGaSm2SEnD5:b-4cgt0k) (no related file):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You also need a `.gitignore` file here. Please see for example https://github.com/oscarlab/graphene-tests/blob/master/curl/.gitignore.
</blockquote></details>

Added the .gitignore file.

---
___
*[nodejs-express-server/helloworld.js, line 3 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-dFTl1p4taQTDGZkP:-M03MXFV2arDiY4AL0Dm:b-tnfok4) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/helloworld.js#L3)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Would it be possible to have port number as an argument from command line? I'd prefer not to hard code it in here.
</blockquote></details>

I committed this change. Now the user can pass the port number as an argument.
___
*[nodejs-express-server/helloworld.js, line 7 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-d6SaCKikVoBHLmrV:-M03MjNj9xAQ77sb9tl3:bhm443e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/helloworld.js#L7)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this app do something more than just listening on a port? How could it be tested? Could a client connect to it and send/receive some meaningful message?
</blockquote></details>

This is just a server listening on a specific port number. The only way to test it is to just run `curl localhost:3000` for example, and you will see the `Hello World!` message. The idea is that anyone can take this as a start and add more functionality to it.
___
*[nodejs-express-server/nodejs.manifest.template, line 45 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-eJbf0OfaiXd1VMhw:-M03N2wO5Vr6X4MEYhVW:bar1a2y) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/nodejs.manifest.template#L45)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

What is this `node_modules`? Looks like a path with some files. Shouldn't it be added to your example?
</blockquote></details>

When you install the nodejs project, by running `npm install`, then some modules are installed. These modules will show up in your project after running `npm install`, so I should be pushing those with the project.
___
*[nodejs-express-server/package.json, line 12 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-eRzU08m7LohQWBCd:-M03NN813jwEPe4jbieD:b-odqo4n) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/package.json#L12)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Shouldn't this file be listed as `sgx.trusted_files.<blabla>` in the manifest?
</blockquote></details>

This file is used by node when running `npm install`, the execution has nothing to do with it.
___
*[nodejs-express-server/README.md, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-coIk761ZMGECJ3Yd:-M03NIQHD35JPLjGLx0o:b-xgfhbj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/README.md#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Could you please wrap this whole file in 100-char limit?
</blockquote></details>

I modified the README file to comply with this.


<!-- Sent from Reviewable.io -->

2020-02-14 21:21 UTC, dimakuv requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @eduardorn)

___
*[nodejs-express-server/helloworld.js, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M04ZU3aBsHo-l2Zw_-f:-M04ZU3aBsHo-l2Zw_-g:b-bgicr7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2347b857edd86830661c2dfb0428179e3c312099/nodejs-express-server/helloworld.js#L5)):*
> ```JavaScript
> const args = process.argv;
> 
> if (args == null || args.length < 3 || args.length > 3){
> ```

Why not just `args.length != 3`?
___
*[nodejs-express-server/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-dZFsAMzzUFx7lqxg:-M04ZxdJ0EP0apN7TUp7:b-arujzi) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/Makefile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This Makefile looks incomplete (as if the top half of the Makefile is missing). For example, `$(GLIBC_DEPS)` is missing and other variables...

Could you add the `all` target, some initial comments, etc? Similar to for example this: https://github.com/oscarlab/graphene-tests/blob/master/curl/Makefile.
</blockquote></details>

This is still WIP?
___
*[nodejs-express-server/nodejs.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-e6bi2Js9R7HjZFEg:-M04ZzZzC50QaLLkkvVY:b-arujzi) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/nodejs.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Again, this file looks incomplete (as if the top half of the file is missing). For example, I don't see `loader.exec` and `loader.preload`. See https://github.com/oscarlab/graphene-tests/blob/master/curl/curl.manifest.template.
</blockquote></details>

This is still WIP?
___
*[nodejs-express-server/README.md, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M04Zqh79trZd5LgAsEL:-M04Zqh79trZd5LgAsEM:bknlx0h) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2347b857edd86830661c2dfb0428179e3c312099/nodejs-express-server/README.md#L11)):*
> ```Markdown
> ## Requirements
> 
> This project requires Node.js to be installed. 
> ```

You have stray whitespaces at the end of lines. Please remove all trailing whitespaces.


<!-- Sent from Reviewable.io -->

2020-02-17 12:59 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 2 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (3 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv)

___
*[nodejs-express-server/helloworld.js, line 5 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M04ZU3aBsHo-l2Zw_-f:-M0IDZJDDB4VEZlssOA-:b-porvsu) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2347b857edd86830661c2dfb0428179e3c312099/nodejs-express-server/helloworld.js#L5)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Why not just `args.length != 3`?
</blockquote></details>

Made that change, you are right, it's more clear and cleaner.
___
*[nodejs-express-server/Makefile, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-dZFsAMzzUFx7lqxg:-M0IDkDt1oeKnnHi0_JP:by5a1oq) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/Makefile#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is still WIP?
</blockquote></details>

Completed Makefile.
___
*[nodejs-express-server/nodejs.manifest.template, line 1 at r1](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0-e6bi2Js9R7HjZFEg:-M0IDn7s6_8dO_Q8-Rvf:b-o3n20r) ([raw file](https://github.com/oscarlab/graphene-tests/blob/3eb9b273acdbe84b355c92e80e18b982347b6b87/nodejs-express-server/nodejs.manifest.template#L1)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This is still WIP?
</blockquote></details>

Completed manifest.
___
*[nodejs-express-server/README.md, line 11 at r2](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M04Zqh79trZd5LgAsEL:-M0IDpif-awIMl0utJnv:bg69a65) ([raw file](https://github.com/oscarlab/graphene-tests/blob/2347b857edd86830661c2dfb0428179e3c312099/nodejs-express-server/README.md#L11)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

You have stray whitespaces at the end of lines. Please remove all trailing whitespaces.
</blockquote></details>

Removed whitespaces.


<!-- Sent from Reviewable.io -->

2020-02-18 22:49 UTC, dimakuv submitted a review, later dismissed
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M0PUK2hEi64YHq2Q8ar:-M0PUK2hEi64YHq2Q8as:bvxw2j4) (no related file):*
Note to myself: test this locally before rebase and merge.

---


<!-- Sent from Reviewable.io -->

2020-02-29 00:07 UTC, mkow requested changes
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DC0XJBCgnL2D9cSGT:-M1DC0XJBCgnL2D9cSGU:b-mrq5j1) (no related file):*
Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can push-force if you choose the former.

---
___
*[nodejs-express-server/.gitignore, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DCHye5atlapH2keAL:-M1DCHye5atlapH2keAM:b4tzr0f) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/.gitignore#L1)):*
> ```ignore
> node_modules
> ```

should be `/node_modules/`
___
*[nodejs-express-server/helloworld.js, line 5 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DCe08E1H8_isiFJzg:-M1DCe08E1H8_isiFJzh:b-zh3otk) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/helloworld.js#L5)):*
> ```JavaScript
> const args = process.argv;
> 
> if (args == null || args.length != 3){
> ```

Please put space before `{` here and below
___
*[nodejs-express-server/helloworld.js, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DD17ZD2yRFHfZP-8m:-M1DD17ZD2yRFHfZP-8n:b-j6q0jg) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/helloworld.js#L6)):*
> ```JavaScript
> 
> if (args == null || args.length != 3){
>   console.log('The only argument required is the port number.')
> ```

please prepend `Error: ` to the message
___
*[nodejs-express-server/helloworld.js, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DDCcmD9PgxwINn3RF:-M1DDCcmD9PgxwINn3RG:bn5jvym) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/helloworld.js#L13)):*
> ```JavaScript
> 
> if (isNaN(port)){
>   console.log('Port argument is not a number.')
> ```

ditto (error)
___
*[nodejs-express-server/Makefile, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DF_XS4SbsnTXacQUM:-M1DF_XS4SbsnTXacQUN:bce3m6e) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/Makefile#L79)):*
> ```Makefile
> .PHONY: check
> check: all
> 	./pal_loader nodejs.manifest helloworld.js > OUTPUT
> ```

Isn't this invocation missing the port argument? How does this even work?
Also, could we test here that the server is indeed working correctly?


<!-- Sent from Reviewable.io -->

2020-03-02 17:28 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 4 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @eduardorn, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DC0XJBCgnL2D9cSGT:-M1RHOFwDm9x6pvfKM6H:b-9crb2q) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix the email address in your commit so that GitHub can recognize it (either by changing it in the commit or by adding it to your GitHub account). You can push-force if you choose the former.
</blockquote></details>

My email was set in my github profile, but I also added it to my git config.

---
___
*[nodejs-express-server/.gitignore, line 1 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DCHye5atlapH2keAL:-M1RHWgg9kLoQZLQ5xUi:b-sbuiid) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/.gitignore#L1)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

should be `/node_modules/`
</blockquote></details>

Changed.
___
*[nodejs-express-server/helloworld.js, line 5 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DCe08E1H8_isiFJzg:-M1RHYkI69LZXu7jy8UI:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/helloworld.js#L5)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please put space before `{` here and below
</blockquote></details>

Fixed.
___
*[nodejs-express-server/helloworld.js, line 6 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DD17ZD2yRFHfZP-8m:-M1RHZyH2XZEX0LWbVgf:b8diyhj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/helloworld.js#L6)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

please prepend `Error: ` to the message
</blockquote></details>

Added Error:
___
*[nodejs-express-server/helloworld.js, line 13 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DDCcmD9PgxwINn3RF:-M1RHb1C9UAv4fuLIaRF:b8diyhj) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/helloworld.js#L13)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

ditto (error)
</blockquote></details>

Added Error:


<!-- Sent from Reviewable.io -->

2020-03-02 17:33 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 3 of 6 files reviewed, 7 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @eduardorn, and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DF_XS4SbsnTXacQUM:-M1RHlXpD01Vv5E_tP0d:bp69mx6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Isn't this invocation missing the port argument? How does this even work?
Also, could we test here that the server is indeed working correctly?
</blockquote></details>

I have a question here. Yes, I need to add the port number, which I did.
The problem is the test it.
1. For a user to test this app, they have to start the Node.js express server listening to a specific port number, which happens automatically when the application is started.
2. A curl request has to be done from a second command line context, such as "curl localhost:3000/" for us to see the "Hello World" message as a response.
Any suggestions on how other programs achieve this in a test in a Makefile?


<!-- Sent from Reviewable.io -->

2020-03-02 18:27 UTC, dimakuv submitted a review, later dismissed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 7 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DF_XS4SbsnTXacQUM:-M1RUc_R09gN6M6rED_O:bbee37c) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

I have a question here. Yes, I need to add the port number, which I did.
The problem is the test it.
1. For a user to test this app, they have to start the Node.js express server listening to a specific port number, which happens automatically when the application is started.
2. A curl request has to be done from a second command line context, such as "curl localhost:3000/" for us to see the "Hello World" message as a response.
Any suggestions on how other programs achieve this in a test in a Makefile?
</blockquote></details>

Two examples:
- https://github.com/oscarlab/graphene-tests/blob/9185188e7da27f528a4990c037f488bc0dff2068/curl/Makefile#L78 (this is kinda reverse to what you want to do: it opens a Python server in the background and then issues a curl request, but the idea is the same)
- https://github.com/oscarlab/graphene/blob/95c7bbc80339ef170183218a9f8e6ef48bdcee74/Jenkinsfiles/Linux#L96 (this is not Makefile but Jenkins, but it gives an idea)

Basically, just start NodeJS in the the background, sleep for 10-30 seconds (so that SGX version has time to bootstrap itself), and then fire a curl request and check the output.


<!-- Sent from Reviewable.io -->

2020-03-04 17:41 UTC, mkow reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DC0XJBCgnL2D9cSGT:-M1aVz_I6fc-JOKRv4mM:b-ndgnrw) (no related file):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

My email was set in my github profile, but I also added it to my git config.
</blockquote></details>

Thanks. Leaving this discussion open as we'll need to fix the emails during the final fixup squash.

[unrelated to the email issue] btw. you can use `git commit --fixup` in the future to make this process easier for us ;)

---


<!-- Sent from Reviewable.io -->

2020-03-05 15:23 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @eduardorn, and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DF_XS4SbsnTXacQUM:-M1fHlyxACmm6cF8-k-R:b-i35nl8) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

Two examples:
- https://github.com/oscarlab/graphene-tests/blob/9185188e7da27f528a4990c037f488bc0dff2068/curl/Makefile#L78 (this is kinda reverse to what you want to do: it opens a Python server in the background and then issues a curl request, but the idea is the same)
- https://github.com/oscarlab/graphene/blob/95c7bbc80339ef170183218a9f8e6ef48bdcee74/Jenkinsfiles/Linux#L96 (this is not Makefile but Jenkins, but it gives an idea)

Basically, just start NodeJS in the the background, sleep for 10-30 seconds (so that SGX version has time to bootstrap itself), and then fire a curl request and check the output.
</blockquote></details>

Added a check in the Makefile.


<!-- Sent from Reviewable.io -->

2020-03-05 15:24 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @eduardorn, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DC0XJBCgnL2D9cSGT:-M1fHtXODj4bbSLvosT1:b4ehfnq) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Thanks. Leaving this discussion open as we'll need to fix the emails during the final fixup squash.

[unrelated to the email issue] btw. you can use `git commit --fixup` in the future to make this process easier for us ;)
</blockquote></details>

Thanks for the suggestion. I'm new to --fixup.

---


<!-- Sent from Reviewable.io -->

2020-03-05 16:00 UTC, mkow requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @eduardorn, and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DF_XS4SbsnTXacQUM:-M1fQ7VV2Avg5ymeY0_G:b-2eowj6) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

Added a check in the Makefile.
</blockquote></details>

Still doesn't work. Please test your changes before publishing ;)


<!-- Sent from Reviewable.io -->

2020-03-05 16:28 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r3](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DF_XS4SbsnTXacQUM:-M1fW_G85xUda5rbjZ6i:b-a7byp7) ([raw file](https://github.com/oscarlab/graphene-tests/blob/e875261994e1ee43ca3e44186bbc2cbdad0d284c/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Still doesn't work. Please test your changes before publishing ;)
</blockquote></details>

Sorry about that. I did test. Somehow my file replaced spaces for tabs before committing. I pushed changes right now.


<!-- Sent from Reviewable.io -->

2020-03-05 18:33 UTC, mkow requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r6](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1fyDoE52xxH78DzJv2:-M1fyDoE52xxH78DzJv3:b-o222ay) ([raw file](https://github.com/oscarlab/graphene-tests/blob/67b27bb0429beefc2f3b129a08f46afed18e5fa6/nodejs-express-server/Makefile#L79)):*
> ```Makefile
> .PHONY: check
> check: all
> 	./pal_loader SGX nodejs.manifest.sgx helloworld.js 3000 & server_id=$$!; \
> ```

`server_id` -> `SERVER_ID`


<!-- Sent from Reviewable.io -->

2020-03-06 20:45 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 4 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @eduardorn, and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r6](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1fyDoE52xxH78DzJv2:-M1la3Fh6b9jMjOvKAIf:b-a2ujfl) ([raw file](https://github.com/oscarlab/graphene-tests/blob/67b27bb0429beefc2f3b129a08f46afed18e5fa6/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

`server_id` -> `SERVER_ID`
</blockquote></details>

Changed.


<!-- Sent from Reviewable.io -->

2020-03-07 00:58 UTC, dimakuv requested changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r7](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1mUYkn7q-X3_PBQ3we:-M1mUYkn7q-X3_PBQ3wf:b-mtcula) ([raw file](https://github.com/oscarlab/graphene-tests/blob/0cec2c24e0b2af130b5dcb83658df167b4fa6098/nodejs-express-server/Makefile#L79)):*
> ```Makefile
> .PHONY: check
> check: all
> 	./pal_loader SGX nodejs.manifest.sgx helloworld.js 3000 & SERVER_ID=$$!; \
> ```

This target does not allow to test without SGX now. If you revert it back to what it was (`./pal_loader nodejs.manifest ...`), it will support both non-SGX Graphene and SGX-enabled Graphene. Please do that.


<!-- Sent from Reviewable.io -->

2020-03-09 16:36 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @eduardorn, and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r7](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1mUYkn7q-X3_PBQ3we:-M2-8VnS34ULYtDnaz_R:b-mh2hd9) ([raw file](https://github.com/oscarlab/graphene-tests/blob/0cec2c24e0b2af130b5dcb83658df167b4fa6098/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This target does not allow to test without SGX now. If you revert it back to what it was (`./pal_loader nodejs.manifest ...`), it will support both non-SGX Graphene and SGX-enabled Graphene. Please do that.
</blockquote></details>

This is more of a question. If I try to run `./pal_loader nodejs.manifest helloworld.js 3000` for example, I get "pal-Linux is not built, or security mode is not supported". 
Maybe I'm not understanding the steps to run with non-SGX.


<!-- Sent from Reviewable.io -->

2020-03-09 18:08 UTC, dimakuv requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r7](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1mUYkn7q-X3_PBQ3we:-M2-TDZl8AQyOr71WkUG:b9w220) ([raw file](https://github.com/oscarlab/graphene-tests/blob/0cec2c24e0b2af130b5dcb83658df167b4fa6098/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

This is more of a question. If I try to run `./pal_loader nodejs.manifest helloworld.js 3000` for example, I get "pal-Linux is not built, or security mode is not supported". 
Maybe I'm not understanding the steps to run with non-SGX.
</blockquote></details>

This error means that you built Graphene only with SGX (`make SGX=1`). You also need to build "vanilla" Graphene without SGX (`make`). They both can co-exist, so usually I do both (`make && make SGX=1`).

After the step of `make`, you will have `pal-Linux` (which is a vanilla Graphene), and the error will go away.


<!-- Sent from Reviewable.io -->

2020-03-09 18:50 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 5 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @eduardorn, and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r7](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1mUYkn7q-X3_PBQ3we:-M2-cIaI-rcLN7A8l0Rc:b-c2p275) ([raw file](https://github.com/oscarlab/graphene-tests/blob/0cec2c24e0b2af130b5dcb83658df167b4fa6098/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, dimakuv (Dmitrii Kuvaiskii) wrote…</i></summary><blockquote>

This error means that you built Graphene only with SGX (`make SGX=1`). You also need to build "vanilla" Graphene without SGX (`make`). They both can co-exist, so usually I do both (`make && make SGX=1`).

After the step of `make`, you will have `pal-Linux` (which is a vanilla Graphene), and the error will go away.
</blockquote></details>

Thanks for this information, I was not aware of it. I just pushed the change to support non-SGX.


<!-- Sent from Reviewable.io -->

2020-03-09 19:03 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)



<!-- Sent from Reviewable.io -->

2020-03-10 14:26 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1DC0XJBCgnL2D9cSGT:-M23pi1LAyDSA69A0kMI:b-896fix) (no related file):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

Thanks for the suggestion. I'm new to --fixup.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-03-10 14:26 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)

___
*[nodejs-express-server/Makefile, line 79 at r6](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M1fyDoE52xxH78DzJv2:-M23pmsW2_ZaWrcQ6XqW:b-896fix) ([raw file](https://github.com/oscarlab/graphene-tests/blob/67b27bb0429beefc2f3b129a08f46afed18e5fa6/nodejs-express-server/Makefile#L79)):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

Changed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-03-10 15:14 UTC, mkow requested changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)

___
*[nodejs-express-server/nodejs.manifest.template, line 37 at r8](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M24-cdS6SJAopEsnOSR:-M24-cdS6SJAopEsnOSS:b-sd5wbl) ([raw file](https://github.com/oscarlab/graphene-tests/blob/58619a857aa4be73c70cbc723caf4766673318e1/nodejs-express-server/nodejs.manifest.template#L37)):*
> ```
> # Set enclave size (somewhat arbitrarily) to 1GB. Recall that SGX v1 requires
> # to specify enclave size at enclave creation time.
> sgx.enclave_size = 2G
> ```

Now the text above is wrong.


<!-- Sent from Reviewable.io -->

2020-03-12 18:46 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 5 of 6 files reviewed, 3 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ), "fixup! " found in commit messages' one-liners (waiting on @dimakuv, @eduardorn, and @mkow)

___
*[nodejs-express-server/nodejs.manifest.template, line 37 at r8](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M24-cdS6SJAopEsnOSR:-M2F3QrLApab3owg2aw1:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/58619a857aa4be73c70cbc723caf4766673318e1/nodejs-express-server/nodejs.manifest.template#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Now the text above is wrong.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2020-03-13 00:32 UTC, dimakuv submitted a review, later dismissed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @eduardorn and @mkow)



<!-- Sent from Reviewable.io -->

2020-03-14 01:20 UTC, mkow requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 3 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M2LbfDm1Oh_DBqNYSCb:-M2LbfDm1Oh_DBqNYSCc:bunnfvj) (no related file):*
@eduardorn: Please don't add merge commits to the PR. We work in the rebase workflow (see https://github.com/oscarlab/graphene/blob/9e5980955b659579e713df90db5c65b2dbb54824/CONTRIBUTING.md#pr-life-cycle) and we'll need to remove them anyway.

---
___
*[nodejs-express-server/nodejs.manifest.template, line 37 at r8](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M24-cdS6SJAopEsnOSR:-M2Lb-AP12uAhr9msexN:boqy194) ([raw file](https://github.com/oscarlab/graphene-tests/blob/58619a857aa4be73c70cbc723caf4766673318e1/nodejs-express-server/nodejs.manifest.template#L37)):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

Fixed.
</blockquote></details>

Please fix wrapping (to 80 characters/line limit) of this comment after removing that parenthesis.


<!-- Sent from Reviewable.io -->

2020-03-18 18:16 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M2iqLk47rF0arRwd1LZ:-M2iqLk50oonOn0hCaG5:bxaab0) (no related file):*
@eduardorn: Do you plan to continue working on this PR?
We plan to get rid of this whole repository and merge it back to the main repo, so that we don't have to fight with git submodules. If you don't have time to finish the PR we can do this for you, if you're ok with this.

---


<!-- Sent from Reviewable.io -->

2020-03-18 19:18 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M2iqLk47rF0arRwd1LZ:-M2j4CAc-h4cGP2wjPEn:b-1hrn8a) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

@eduardorn: Do you plan to continue working on this PR?
We plan to get rid of this whole repository and merge it back to the main repo, so that we don't have to fight with git submodules. If you don't have time to finish the PR we can do this for you, if you're ok with this.
</blockquote></details>

Not sure what I need to do next here. I think I replied to all of the comments. Am I missing anything?

---


<!-- Sent from Reviewable.io -->

2020-03-18 20:04 UTC, mkow reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 4 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M2iqLk47rF0arRwd1LZ:-M2jEcorDGwr8y9y7se-:bbfboh0) (no related file):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

Not sure what I need to do next here. I think I replied to all of the comments. Am I missing anything?
</blockquote></details>

There's one discussion waiting for your fix, you should see it on reviewable (about wrapping).

---


<!-- Sent from Reviewable.io -->

2020-03-18 20:16 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 5 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @eduardorn, and @mkow)

___
*[nodejs-express-server/nodejs.manifest.template, line 37 at r8](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M24-cdS6SJAopEsnOSR:-M2jHQui5uC7U3rephMY:bt2vr1b) ([raw file](https://github.com/oscarlab/graphene-tests/blob/58619a857aa4be73c70cbc723caf4766673318e1/nodejs-express-server/nodejs.manifest.template#L37)):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Please fix wrapping (to 80 characters/line limit) of this comment after removing that parenthesis.
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2020-03-18 20:17 UTC, eduardorn reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: 5 of 6 files reviewed, 4 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (2 more required, approved so far: ) (waiting on @dimakuv, @eduardorn, and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M2iqLk47rF0arRwd1LZ:-M2jHfkT-_vbi6CVsIql:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

There's one discussion waiting for your fix, you should see it on reviewable (about wrapping).
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-03-18 20:22 UTC, mkow submitted a review, later dismissed
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: ITL) (waiting on @eduardorn and @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M2iqLk47rF0arRwd1LZ:-M2jIgMR7QGRXz8qug8Q:b-ucfknh) (no related file):*
<details><summary><i>Previously, eduardorn (Eduardo Rodriguez) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

---


<!-- Sent from Reviewable.io -->

2020-03-18 22:50 UTC, dimakuv submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 2 unresolved discussions, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @eduardorn and @mkow)

___
*[nodejs-express-server/nodejs.manifest.template, line 36 at r16](https://reviewable.io/reviews/oscarlab/graphene-tests/72#-M2jphNa1MUZglaykhpl:-M2jphNa1MUZglaykhpm:b-d8z062) ([raw file](https://github.com/oscarlab/graphene-tests/blob/203aedc7f5b2a1f16116fe643cd02c64d4c9d503/nodejs-express-server/nodejs.manifest.template#L36)):*
> ```
> 
> # Set enclave size to 2GB. Recall that SGX v1 requires
> # to specify enclave size at enclave creation time.
> ```

Somehow wrapping is not fixed, but I'd let it pass.


<!-- Sent from Reviewable.io -->

2020-03-18 23:03 UTC, dimakuv approved these changes
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @mkow)



<!-- Sent from Reviewable.io -->

2020-03-18 23:04 UTC, mkow approved these changes
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/72)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-03-19 13:36 UTC, merged