[LTP] Disable tests that fail on Glibc 2.31
oscarlab/graphene-tests pull request #76
Opened 2020-03-13 08:15 UTC by dimakuv

This commit disables tests that loudly fail on Glibc 2.31:

- semop01 and semop04 -- LTP runs incorrectly on Glibc 2.31, with semaphore syscalls' addresses jumbled in the PLT section. Looks like the combination of upstream LTP and Glibc 2.31 doesn't work.

- settimeofday01 -- it never worked before in Graphene anyway, and Glibc 2.31 code doesn't properly sanitize function arguments. Again, the combination of upstream LTP and Glibc 2.31 is broken.

- sysconf01 -- worked by accident, now that Glibc 2.31 loudly complains about unimplemented _SC_XOPEN_CRYPT, it fails.

Generally, some LTP tests must be re-written to work with Glibc 2.31.

2020-03-15 20:45 UTC, mkow requested changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/76)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel) (waiting on @dimakuv)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/76#-M2UvpXS9wq4L4w1SScJ:-M2UvpXT0ANZN02JIwVv:bvzq4wn) (no related file):*
> Generally, some LTP tests must be re-written to work with Glibc 2.31.

Could you check if corresponding issues are already filed in the LTP repo, and if not, report them? Would be nice to have upstream support for newer glibcs.

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/76#-M2Uw9lD01K06KA4AZpn:-M2Uw9lD01K06KA4AZpo:b7j0taj) (no related file):*
Could you add comments explaining why each of those tests was disabled?

---


<!-- Sent from Reviewable.io -->

2020-03-16 19:18 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/76)* status: 0 of 2 files reviewed, 2 unresolved discussions, not enough approvals from maintainers (2 more required), not enough approvals from different teams (1 more required, approved so far: Intel), "fixup! " found in commit messages' one-liners (waiting on @mkow)

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/76#-M2UvpXS9wq4L4w1SScJ:-M2ZjwiG8RnR36PqPB51:b-2q7lbn) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

> Generally, some LTP tests must be re-written to work with Glibc 2.31.

Could you check if corresponding issues are already filed in the LTP repo, and if not, report them? Would be nice to have upstream support for newer glibcs.
</blockquote></details>

Updates:

1. For `semop`, this was my mistake. The tests work after the fixup in the main PR (I had a bug there). I reverted this.

2. For `settimeofday`, see https://github.com/linux-test-project/ltp/issues/646 -- this one was already reported.

3. For `sysconf01`, this is an unrelated Graphene issue (Graphene doesn't emulate all sysconf parameters, and Glibc 2.31 now loudly complains about not-found `_SC_XOPEN_CRYPT` which leads to LTP fail).

---
*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/76#-M2Uw9lD01K06KA4AZpn:-M2Zm-ae1X6wp_0C1EHr:b-896fix) (no related file):*
<details><summary><i>Previously, mkow (Michał Kowalczyk) wrote…</i></summary><blockquote>

Could you add comments explaining why each of those tests was disabled?
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-03-16 19:27 UTC, mkow submitted a review, later dismissed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/76)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners



<!-- Sent from Reviewable.io -->

2020-03-16 21:35 UTC, dimakuv reviewed
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/76)* status: all files reviewed, 1 unresolved discussion, not enough approvals from maintainers (1 more required), "fixup! " found in commit messages' one-liners

*[a discussion](https://reviewable.io/reviews/oscarlab/graphene-tests/76#-M2_GTiE3LwN2Rr8rgIo:-M2_GTiE3LwN2Rr8rgIp:b-7jj0fr) (no related file):*
NOTE: During rebase, remove `semop` from the commit message.

---


<!-- Sent from Reviewable.io -->

2020-03-17 18:20 UTC, yamahata approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/76)* status: all files reviewed, all discussions resolved, not enough approvals from maintainers (1 more required), not enough approvals from different teams (1 more required, approved so far: Intel)



<!-- Sent from Reviewable.io -->

2020-03-17 18:21 UTC, mkow approved these changes
> *[Reviewable](https://reviewable.io/reviews/oscarlab/graphene-tests/76)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-03-17 21:50 UTC, merged

2020-03-25 16:03 UTC, pevik commented
Note these tests have been fixed in current master (if you have mechanism to use patches).

2020-03-25 16:24 UTC, mkow commented
@pevik Thanks for the info! We use LTP as a submodule, so we can just update the commit we use (assuming it won't cause any new troubles).
We'll test the new version and let you know in case it continues to fail.

2020-03-25 16:28 UTC, pevik commented
@mkow FYI commits https://github.com/linux-test-project/ltp/commit/c9607c152249df9904a90d6f8bcd415e193602e8, https://github.com/linux-test-project/ltp/commit/0c99e15cbbe7715ba632982ff0b9e2f8be20c80e. I tested them on glibc 2.31 in openSUSE. If you find any problems, please report it to LTP.